<?php

namespace Database\Seeders;

use App\Models\Umkm;
use App\Models\UmkmListing;
use Illuminate\Database\Seeder;
// use Illuminate\Support\Facades\URL; // URL tidak terpakai, bisa dihapus

class UmkmListingSeeder extends Seeder
{
    public function run(): void
    {
        $umkms = Umkm::pluck('id', 'slug')->all();

        // UBAH INI: Gunakan jalur relatif dari folder 'storage/app/public/'
        $baseRelativePath = 'uploads/umkm/';

        $dataListings = [
            [
                'slug' => 'warung-makan-om-w',
                'category' => 'Makanan',
                'subtitle' => 'Warung sederhana dengan menu rumahan khas Kudus yang lezat dan terjangkau.',
                'location' => 'Bae',
                'kecamatan_slug' => 'bae',
                'image' => $baseRelativePath . 'omw_hero.webp',
            ],
            [
                'slug' => 'ayam-geprek-jawi',
                'category' => 'Makanan',
                'subtitle' => 'Menyajikan ayam geprek pedas dengan sambal khas yang menggugah selera.',
                'location' => 'Bae',
                'kecamatan_slug' => 'bae',
                'image' => $baseRelativePath . 'geprekjawi_hero.webp',
            ],
            [
                'slug' => 'soto-lamongan-mbak-yuli',
                'category' => 'Makanan',
                'subtitle' => 'Soto Lamongan gurih dengan koya melimpah dan potongan ayam kampung.',
                'location' => 'Bae',
                'kecamatan_slug' => 'bae',
                'image' => $baseRelativePath . 'lamonganyuli_hero.webp',
            ],
            [
                'slug' => 'es-cincau-pasundan',
                'category' => 'Minuman',
                'subtitle' => 'Minuman segar dengan cincau hitam khas Pasundan dan gula merah cair.',
                'location' => 'Bae',
                'kecamatan_slug' => 'bae',
                'image' => $baseRelativePath . 'cincaupasundan_hero.webp',
            ],
            [
                'slug' => 'jasa-tulis-kudus',
                'category' => 'Jasa',
                'subtitle' => 'Melayani jasa pengetikan, cetak dokumen, dan administrasi harian.',
                'location' => 'Bae',
                'kecamatan_slug' => 'bae',
                'image' => $baseRelativePath . 'jasatulis_hero.webp',
            ],
            [
                'slug' => 'resto-mvr-kudus',
                'category' => 'Makanan',
                'subtitle' => 'Restoran modern dengan aneka hidangan lezat dan suasana nyaman untuk berkumpul bersama keluarga dan teman.',
                'location' => 'Bae',
                'kecamatan_slug' => 'bae',
                'image' => $baseRelativePath . 'restomvr_hero.webp',
            ],
            [
                'slug' => 'vjo-cafe-bistro',
                'category' => 'Makanan',
                'subtitle' => 'Cafe dan bistro bergaya modern yang menyajikan aneka hidangan lezat dan minuman kekinian dengan suasana nyaman.',
                'location' => 'Bae',
                'kecamatan_slug' => 'bae',
                'image' => $baseRelativePath . 'vjocafe_hero.webp',
            ],
            [
                'slug' => 'toko-al-maira',
                'category' => 'Barang',
                'subtitle' => 'Toko bahan makanan yang menyediakan berbagai kebutuhan dapur harian dengan harga terjangkau dan kualitas terjamin.',
                'location' => 'Bae',
                'kecamatan_slug' => 'bae',
                'image' => $baseRelativePath . 'tokoalmaira_hero.webp',
            ],
            [
                'slug' => 'siskanuna-boutique',
                'category' => 'Lainnya',
                'subtitle' => 'Toko pakaian wanita yang menawarkan berbagai busana modern, hijab, dan aksesoris dengan desain elegan dan harga terjangkau.',
                'location' => 'Bae',
                'kecamatan_slug' => 'bae',
                'image' => $baseRelativePath . 'siskanuna_hero.webp',
            ],
            [
                'slug' => 'terebatik',
                'category' => 'Lainnya',
                'subtitle' => 'Toko pakaian yang menjual berbagai koleksi batik khas Kudus dengan desain modern dan kualitas terbaik.',
                'location' => 'Bae',
                'kecamatan_slug' => 'bae',
                'image' => $baseRelativePath . 'terebatik_hero.webp',
            ],
            // DAWE
            [
                'slug' => 'swike-dawe-restaurant',
                'category' => 'Makanan',
                'subtitle' => 'Restoran khas Kudus yang menyajikan swike lezat dengan resep tradisional.',
                'location' => 'Dawe',
                'kecamatan_slug' => 'dawe',
                'image' => $baseRelativePath . 'swikedawe_hero.webp',
            ],
            [
                'slug' => 'wekate-gank',
                'category' => 'Minuman',
                'subtitle' => 'Kedai minuman kekinian dengan berbagai pilihan topping dan rasa.',
                'location' => 'Dawe',
                'kecamatan_slug' => 'dawe',
                'image' => $baseRelativePath . 'wekategank_hero.webp',
            ],
            [
                'slug' => 'rumah-makan-mak-kiyem',
                'category' => 'Makanan',
                'subtitle' => 'Tempat makan dengan cita rasa masakan Jawa rumahan yang otentik.',
                'location' => 'Dawe',
                'kecamatan_slug' => 'dawe',
                'image' => $baseRelativePath . 'makkiyem_hero.webp',
            ],
            [
                'slug' => 'jasa-angkut-dan-pasir-bata-merah-jumbo',
                'category' => 'Jasa',
                'subtitle' => 'Menyediakan layanan angkut material bangunan dan kebutuhan konstruksi.',
                'location' => 'Dawe',
                'kecamatan_slug' => 'dawe',
                'image' => $baseRelativePath . 'jasaangkut_hero.webp',
            ],
            [
                'slug' => 'ayam-geprek-sai',
                'category' => 'Makanan',
                'subtitle' => 'Ayam geprek dengan level pedas sesuai selera dan harga bersahabat.',
                'location' => 'Dawe',
                'kecamatan_slug' => 'dawe',
                'image' => $baseRelativePath . 'ayamgepreksai_hero.webp',
            ],
            [
                'slug' => 'warung-makan-sendang-mulia',
                'category' => 'Makanan',
                'subtitle' => 'Rumah makan yang menyajikan aneka hidangan rumahan lezat dengan cita rasa khas dan suasana nyaman.',
                'location' => 'Dawe',
                'kecamatan_slug' => 'dawe',
                'image' => $baseRelativePath . 'sendangmulia_hero.webp',
            ],
            [
                'slug' => 'toko-adib-azka',
                'category' => 'Barang',
                'subtitle' => 'Toko perlengkapan rumah tangga yang menyediakan berbagai kebutuhan harian dengan harga terjangkau.',
                'location' => 'Dawe',
                'kecamatan_slug' => 'dawe',
                'image' => $baseRelativePath . 'tokoadibazka_hero.webp',
            ],
            [
                'slug' => 'toko-sri-dawe',
                'category' => 'Barang',
                'subtitle' => 'Toko bahan makanan yang menyediakan berbagai kebutuhan dapur, bumbu, dan sembako lengkap dengan harga bersahabat.',
                'location' => 'Dawe',
                'kecamatan_slug' => 'dawe',
                'image' => $baseRelativePath . 'tokosridawe_hero.webp',
            ],
            [
                'slug' => 'arfan-outfit-kudus',
                'category' => 'Lainnya',
                'subtitle' => 'Toko pakaian yang menyediakan berbagai busana trendi dan nyaman untuk segala usia.',
                'location' => 'Dawe',
                'kecamatan_slug' => 'dawe',
                'image' => $baseRelativePath . 'arfanoutfitkudus_hero.webp',
            ],
            [
                'slug' => 'dinda-store-ds',
                'category' => 'Lainnya',
                'subtitle' => 'Toko pakaian yang menyediakan berbagai busana trendi, modern, dan nyaman untuk segala usia.',
                'location' => 'Dawe',
                'kecamatan_slug' => 'dawe',
                'image' => $baseRelativePath . 'dindastore_hero.webp',
            ],
            // GEBOG
            [
                'slug' => 'warung-makan-mbah-sapar',
                'category' => 'Makanan',
                'subtitle' => 'Warung makan legendaris dengan menu khas Kudus yang menggugah selera.',
                'location' => 'Gebog',
                'kecamatan_slug' => 'gebog',
                'image' => $baseRelativePath . 'mbahsapar_hero.webp',
            ],
            [
                'slug' => 'nasi-uduk-dan-nasi-kuning-gang-satu',
                'category' => 'Makanan',
                'subtitle' => 'Menyajikan nasi uduk dan nasi kuning dengan lauk variatif setiap hari.',
                'location' => 'Gebog',
                'kecamatan_slug' => 'gebog',
                'image' => $baseRelativePath . 'nasiuduk_hero.webp',
            ],
            [
                'slug' => 'sari-rasa-bakso-malvinas',
                'category' => 'Makanan',
                'subtitle' => 'Bakso urat dengan kuah kaldu gurih dan porsi mengenyangkan.',
                'location' => 'Gebog',
                'kecamatan_slug' => 'gebog',
                'image' => $baseRelativePath . 'baksomalvinas_hero.webp',
            ],
            [
                'slug' => 'warung-makan-mak-ru',
                'category' => 'Makanan',
                'subtitle' => 'Menu masakan rumahan lengkap dengan sambal khas Kudus.',
                'location' => 'Gebog',
                'kecamatan_slug' => 'gebog',
                'image' => $baseRelativePath . 'warungmakanmakru_hero.webp',
            ],
            [
                'slug' => 'kasehito-works',
                'category' => 'Jasa',
                'subtitle' => 'Menyediakan jasa desain, sablon, dan percetakan lokal berkualitas.',
                'location' => 'Gebog',
                'kecamatan_slug' => 'gebog',
                'image' => $baseRelativePath . 'kasehitoworks_hero.webp',
            ],
            [
                'slug' => 'basina-food',
                'category' => 'Makanan',
                'subtitle' => 'Rumah makan yang menyajikan aneka hidangan lezat khas rumahan.',
                'location' => 'Gebog',
                'kecamatan_slug' => 'gebog',
                'image' => $baseRelativePath . 'basina_hero.webp',
            ],
            [
                'slug' => 'campaign-coffee',
                'category' => 'Minuman',
                'subtitle' => 'Kedai kopi modern dengan cita rasa autentik dan suasana nyaman.',
                'location' => 'Gebog',
                'kecamatan_slug' => 'gebog',
                'image' => $baseRelativePath . 'campaigncoffee_hero.webp',
            ],
            [
                'slug' => 'toko-tna-jaya',
                'category' => 'Barang',
                'subtitle' => 'Toko bahan makanan lengkap dengan harga terjangkau dan kualitas terjamin.',
                'location' => 'Gebog',
                'kecamatan_slug' => 'gebog',
                'image' => $baseRelativePath . 'tokotnajaya_hero.webp',
            ],
            [
                'slug' => 'toko-teguh-sudarsono',
                'category' => 'Barang',
                'subtitle' => 'Toko bahan makanan harian yang menyediakan kebutuhan dapur lengkap dan berkualitas.',
                'location' => 'Gebog',
                'kecamatan_slug' => 'gebog',
                'image' => $baseRelativePath . 'tokoteguhsudarsono_hero.webp',
            ],
            [
                'slug' => 'nilna-dion-collection',
                'category' => 'Lainnya',
                'subtitle' => 'Toko pakaian modern yang menyediakan berbagai busana stylish dan nyaman untuk semua kalangan.',
                'location' => 'Gebog',
                'kecamatan_slug' => 'gebog',
                'image' => $baseRelativePath . 'nilnadioncollection_hero.webp',
            ],
            [
                'slug' => 'toko-kastimah',
                'category' => 'Barang',
                'subtitle' => 'Toko bahan makanan harian yang menyediakan kebutuhan dapur lengkap dengan harga terjangkau.',
                'location' => 'Gebog',
                'kecamatan_slug' => 'gebog',
                'image' => $baseRelativePath . 'tokokastimah_hero.webp',
            ],
            // JATI
            [
                'slug' => 'cakrawala-sego-sambel',
                'category' => 'Makanan',
                'subtitle' => 'Sego sambel khas dengan berbagai lauk pedas yang menggoda selera.',
                'location' => 'Jati',
                'kecamatan_slug' => 'jati',
                'image' => $baseRelativePath . 'cakrawala_hero.webp',
            ],
            [
                'slug' => 'nasi-opor-sunggingan',
                'category' => 'Makanan',
                'subtitle' => 'Opor ayam lembut dengan kuah santan kental dan bumbu khas Kudus.',
                'location' => 'Jati',
                'kecamatan_slug' => 'jati',
                'image' => $baseRelativePath . 'oporsungginan_hero.webp',
            ],
            [
                'slug' => 'warung-enthog-pak-badi',
                'category' => 'Makanan',
                'subtitle' => 'Spesialis olahan enthog dengan sambal korek pedas menggugah selera.',
                'location' => 'Jati',
                'kecamatan_slug' => 'jati',
                'image' => $baseRelativePath . 'enthogpakbadi_hero.webp',
            ],
            [
                'slug' => 'jasa-powder-coating-dan-platting-kudus',
                'category' => 'Jasa',
                'subtitle' => 'Melayani coating dan platting untuk berbagai kebutuhan industri dan otomotif.',
                'location' => 'Jati',
                'kecamatan_slug' => 'jati',
                'image' => $baseRelativePath . 'powdercoating_hero.webp',
            ],
            [
                'slug' => 'kedai-es-bang-maman',
                'category' => 'Minuman',
                'subtitle' => 'Es segar berbagai rasa dengan topping buah dan jelly favorit anak muda.',
                'location' => 'Jati',
                'kecamatan_slug' => 'jati',
                'image' => $baseRelativePath . 'esbangmaman_hero.webp',
            ],
            [
                'slug' => 'gravitasi-teras-muria',
                'category' => 'Makanan',
                'subtitle' => 'Restoran dengan pakaian indah di lereng Muria yang menyajikan aneka hidangan lezat dan suasana nyaman.',
                'location' => 'Jati',
                'kecamatan_slug' => 'jati',
                'image' => $baseRelativePath . 'gravitasiterasmuria_hero.webp',
            ],
            [
                'slug' => 'toko-kliwon',
                'category' => 'Barang',
                'subtitle' => 'Toko perlengkapan rumah tangga yang menyediakan berbagai kebutuhan dapur dan alat harian dengan harga terjangkau.',
                'location' => 'Jati',
                'kecamatan_slug' => 'jati',
                'image' => $baseRelativePath . 'tokokliwon_hero.webp',
            ],
            [
                'slug' => 'toko-happy-kids',
                'category' => 'Lainnya',
                'subtitle' => 'Toko pakaian anak yang menyediakan berbagai busana lucu, nyaman, dan berkualitas untuk si kecil.',
                'location' => 'Jati',
                'kecamatan_slug' => 'jati',
                'image' => $baseRelativePath . 'tokohappykids_hero.webp',
            ],
            [
                'slug' => 'nobby-kudus-extension',
                'category' => 'Lainnya',
                'subtitle' => 'Toko pakaian modern yang menawarkan berbagai koleksi busana trendi untuk pria dan wanita dengan gaya kekinian.',
                'location' => 'Jati',
                'kecamatan_slug' => 'jati',
                'image' => $baseRelativePath . 'nobbykudusextension_hero.webp',
            ],
            // JEKULO
            [
                'slug' => 'jus-pojokan',
                'category' => 'Minuman',
                'subtitle' => 'Jus segar berbagai rasa yang cocok dinikmati saat siang hari.',
                'location' => 'Jekulo',
                'kecamatan_slug' => 'jekulo',
                'image' => $baseRelativePath . 'juspojokan_hero.webp',
            ],
            [
                'slug' => 'kedai-twins-seblak-bandung-juice-jekulo',
                'category' => 'Minuman',
                'subtitle' => 'Kedai seblak dan jus kekinian khas Bandung dengan cita rasa lokal.',
                'location' => 'Jekulo',
                'kecamatan_slug' => 'jekulo',
                'image' => $baseRelativePath . 'kedaytwins_hero.webp',
            ],
            [
                'slug' => 'lentog-tanjung-bang-saiful',
                'category' => 'Makanan',
                'subtitle' => 'Lentog khas Kudus dengan cita rasa gurih yang legendaris.',
                'location' => 'Jekulo',
                'kecamatan_slug' => 'jekulo',
                'image' => $baseRelativePath . 'lentogbangsyaiful_hero.webp',
            ],
            [
                'slug' => 'berkah-es-buah',
                'category' => 'Minuman',
                'subtitle' => 'Es buah segar dengan campuran jelly dan susu, favorit semua kalangan.',
                'location' => 'Jekulo',
                'kecamatan_slug' => 'jekulo',
                'image' => $baseRelativePath . 'berkahesbuah_hero.webp',
            ],
            [
                'slug' => 'warnet-jaya-sentosa',
                'category' => 'Jasa',
                'subtitle' => 'Warnet dengan koneksi cepat dan nyaman untuk bermain maupun bekerja.',
                'location' => 'Jekulo',
                'kecamatan_slug' => 'jekulo',
                'image' => $baseRelativePath . 'warnetjayasentosa_hero.webp',
            ],
            [
                'slug' => 'warung-mie-dadat',
                'category' => 'Makanan',
                'subtitle' => 'Warung mie legendaris yang menyajikan aneka mie rebus dan goreng dengan cita rasa khas dan porsi mengenyangkan.',
                'location' => 'Jekulo',
                'kecamatan_slug' => 'jekulo',
                'image' => $baseRelativePath . 'warungmiedadat_hero.webp',
            ],
            [
                'slug' => 'toko-risfan-snack',
                'category' => 'Barang',
                'subtitle' => 'Toko bahan makanan dan grosir snack lengkap yang menyediakan berbagai camilan, makanan ringan, dan kebutuhan dapur dengan harga terjangkau.',
                'location' => 'Jekulo',
                'kecamatan_slug' => 'jekulo',
                'image' => $baseRelativePath . 'tokorisfan_hero.webp',
            ],
            [
                'slug' => 'js-muslim-collection',
                'category' => 'Lainnya',
                'subtitle' => 'Toko pakaian muslim yang menyediakan berbagai busana syar’i, gamis, dan hijab modern dengan desain elegan dan harga bersahabat.',
                'location' => 'Jekulo',
                'kecamatan_slug' => 'jekulo',
                'image' => $baseRelativePath . 'jsmuslim_hero.webp',
            ],
            [
                'slug' => 'kios-hjh',
                'category' => 'Lainnya',
                'subtitle' => 'Toko pakaian yang menyediakan berbagai busana muslim, mukena, dan perlengkapan ibadah dengan kualitas bagus dan harga terjangkau.',
                'location' => 'Jekulo',
                'kecamatan_slug' => 'jekulo',
                'image' => $baseRelativePath . 'kioshjh_hero.webp',
            ],
            // KALIWUNGU
            [
                'slug' => 'jahe-rempah-leggit',
                'category' => 'Minuman',
                'subtitle' => 'Minuman jahe hangat dengan campuran rempah alami khas Kudus.',
                'location' => 'Kaliwungu',
                'kecamatan_slug' => 'kaliwungu',
                'image' => $baseRelativePath . 'jaherempahreggit_hero.webp',
            ],
            [
                'slug' => 'warung-makan-bu-carik',
                'category' => 'Makanan',
                'subtitle' => 'Warung makan sederhana dengan menu rumahan yang lezat dan murah.',
                'location' => 'Kaliwungu',
                'kecamatan_slug' => 'kaliwungu',
                'image' => $baseRelativePath . 'warungmakanbucarik_hero.webp',
            ],
            [
                'slug' => 'tehatea-indonesia',
                'category' => 'Minuman',
                'subtitle' => 'Gerai teh kekinian dengan berbagai varian rasa dan topping menarik.',
                'location' => 'Kaliwungu',
                'kecamatan_slug' => 'kaliwungu',
                'image' => $baseRelativePath . 'tehatea_hero.webp',
            ],
            [
                'slug' => 'warung-makan-2-putra',
                'category' => 'Makanan',
                'subtitle' => 'Tempat makan dengan menu ayam goreng dan sambal khas.',
                'location' => 'Kaliwungu',
                'kecamatan_slug' => 'kaliwungu',
                'image' => $baseRelativePath . 'warungmakan2putra_hero.webp',
            ],
            [
                'slug' => 'jasa-angkut-barang',
                'category' => 'Jasa',
                'subtitle' => 'Layanan angkut cepat dan aman untuk kebutuhan pindahan dan kiriman.',
                'location' => 'Kaliwungu',
                'kecamatan_slug' => 'kaliwungu',
                'image' => $baseRelativePath . 'jasaangkutbarang_hero.webp',
            ],
            [
                'slug' => 'sego-sambel-lek-kas2',
                'category' => 'Makanan',
                'subtitle' => 'Rumah makan yang menyajikan sego sambel pedas nikmat dengan lauk beragam dan cita rasa khas rumahan.',
                'location' => 'Kaliwungu',
                'kecamatan_slug' => 'kaliwungu',
                'image' => $baseRelativePath . 'segosambel_hero.webp',
            ],
            [
                'slug' => 'toko-jamaah',
                'category' => 'Barang',
                'subtitle' => 'Toko bahan makanan yang menyediakan berbagai kebutuhan dapur dan sembako dengan harga terjangkau.',
                'location' => 'Kaliwungu',
                'kecamatan_slug' => 'kaliwungu',
                'image' => $baseRelativePath . 'tokojamaah_hero.webp',
            ],
            [
                'slug' => 'mm-amanah',
                'category' => 'Barang',
                'subtitle' => 'Minimarket yang menyediakan berbagai kebutuhan harian, mulai dari sembako hingga produk rumah tangga dengan harga bersahabat.',
                'location' => 'Kaliwungu',
                'kecamatan_slug' => 'kaliwungu',
                'image' => $baseRelativePath . 'mmamanah_hero.webp',
            ],
            [
                'slug' => 'toko-van-helen',
                'category' => 'Lainnya',
                'subtitle' => 'Toko pakaian yang menawarkan berbagai busana trendi dan aksesori dengan harga terjangkau, hanya Rp35.000-an.',
                'location' => 'Kaliwungu',
                'kecamatan_slug' => 'kaliwungu',
                'image' => $baseRelativePath . 'tokovanhelen_hero.webp',
            ],
            [
                'slug' => 'lina-family',
                'category' => 'Lainnya',
                'subtitle' => 'Toko pakaian yang menyediakan berbagai busana keluarga dengan model modern dan harga bersahabat.',
                'location' => 'Kaliwungu',
                'kecamatan_slug' => 'kaliwungu',
                'image' => $baseRelativePath . 'linafamily_hero.webp',
            ],
            // KOTA KUDUS
            [
                'slug' => 'susu-moeria',
                'category' => 'Minuman',
                'subtitle' => 'Susu murni dengan berbagai varian rasa khas Kudus.',
                'location' => 'Kota Kudus',
                'kecamatan_slug' => 'kota-kudus',
                'image' => $baseRelativePath . 'susumoeria_hero.webp',
            ],
            [
                'slug' => 'ramboo-chicken',
                'category' => 'Makanan',
                'subtitle' => 'Ayam geprek dengan sambal korek yang pedas dan menggugah selera.',
                'location' => 'Kota Kudus',
                'kecamatan_slug' => 'kota-kudus',
                'image' => $baseRelativePath . 'ramboo_hero.webp',
            ],
            [
                'slug' => 'es-gempol-pak-masykur',
                'category' => 'Minuman',
                'subtitle' => 'Minuman tradisional Kudus dengan gempol segar dan santan manis.',
                'location' => 'Kota Kudus',
                'kecamatan_slug' => 'kota-kudus',
                'image' => $baseRelativePath . 'gempol_hero.webp',
            ],
            [
                'slug' => 'sultan-barber-top',
                'category' => 'Jasa',
                'subtitle' => 'Barbershop modern dengan pelayanan profesional, tempat nyaman, dan hasil cukur rapi bergaya kekinian.',
                'location' => 'Kota Kudus',
                'kecamatan_slug' => 'kota-kudus',
                'image' => $baseRelativePath . 'sultanbarbertop_hero.webp',
            ],
            [
                'slug' => 'soto-kudus-bu-jatmi',
                'category' => 'Makanan',
                'subtitle' => 'Warung legendaris dengan cita rasa soto khas Kudus yang gurih dan autentik sejak puluhan tahun.',
                'location' => 'Kota Kudus',
                'kecamatan_slug' => 'kota-kudus',
                'image' => $baseRelativePath . 'sotokudusbujatmi_hero.webp',
            ],
            [
                'slug' => 'treend-steak-kudus',
                'category' => 'Makanan',
                'subtitle' => 'Restoran steak modern yang menyajikan aneka daging premium dengan cita rasa lezat dan harga bersahabat.',
                'location' => 'Kota Kudus',
                'kecamatan_slug' => 'kota-kudus',
                'image' => $baseRelativePath . 'treendsteak_hero.webp',
            ],
            [
                'slug' => 'larees-jaya-electronics',
                'category' => 'Barang',
                'subtitle' => 'Toko elektronik lengkap yang menyediakan berbagai peralatan rumah tangga dan gadget dengan harga bersaing.',
                'location' => 'Kota Kudus',
                'kecamatan_slug' => 'kota-kudus',
                'image' => $baseRelativePath . 'lareesjaya_hero.webp',
            ],
            [
                'slug' => 'es-coklat-cokot-kudus',
                'category' => 'Minuman',
                'subtitle' => 'Minuman coklat kekinian dengan rasa creamy dan manis pas, favorit anak muda Kudus.',
                'location' => 'Kota Kudus',
                'kecamatan_slug' => 'kota-kudus',
                'image' => $baseRelativePath . 'escoklatcokotkudus_hero.webp',
            ],
            [
                'slug' => 'richie-store-kudus',
                'category' => 'Lainnya',
                'subtitle' => 'Toko pakaian trendi yang menyediakan berbagai busana stylish dan nyaman untuk semua usia.',
                'location' => 'Kota Kudus',
                'kecamatan_slug' => 'kota-kudus',
                'image' => $baseRelativePath . 'richiestore_hero.webp',
            ],
            // MEJOBO
            [
                'slug' => 'xgam-tech',
                'category' => 'Jasa',
                'subtitle' => 'Layanan servis laptop, komputer, dan rakit PC profesional.',
                'location' => 'Mejobo',
                'kecamatan_slug' => 'mejobo',
                'image' => $baseRelativePath . 'xgamtech_hero.webp',
            ],
            [
                'slug' => 'jasa-las-dan-bubut-mulyo-rejo',
                'category' => 'Jasa',
                'subtitle' => 'Layanan las dan bubut untuk kebutuhan industri dan rumah tangga.',
                'location' => 'Mejobo',
                'kecamatan_slug' => 'mejobo',
                'image' => $baseRelativePath . 'jasalas_hero.webp',
            ],
            [
                'slug' => 'putra-kalimosodo',
                'category' => 'Jasa',
                'subtitle' => 'Penyedia jasa transportasi dan material bangunan terpercaya.',
                'location' => 'Mejobo',
                'kecamatan_slug' => 'mejobo',
                'image' => $baseRelativePath . 'kalimosodo_hero.webp',
            ],
            [
                'slug' => 'ikan-bakar-nasuky-mubarok-jepang',
                'category' => 'Makanan',
                'subtitle' => 'Ikan bakar khas Kudus dengan sambal pedas menggoda.',
                'location' => 'Mejobo',
                'kecamatan_slug' => 'mejobo',
                'image' => $baseRelativePath . 'ikanbakar_hero.webp',
            ],
            [
                'slug' => 'rm-bu-sarah',
                'category' => 'Makanan',
                'subtitle' => 'Rumah makan keluarga dengan masakan tradisional Jawa.',
                'location' => 'Mejobo',
                'kecamatan_slug' => 'mejobo',
                'image' => $baseRelativePath . 'rmbusarah_hero.webp',
            ],
            [
                'slug' => 'sate-kambing-pak-brewok',
                'category' => 'Makanan',
                'subtitle' => 'Warung sate khas yang menyajikan sate kambing empuk dengan bumbu lezat dan cita rasa khas Kudus.',
                'location' => 'Mejobo',
                'kecamatan_slug' => 'mejobo',
                'image' => $baseRelativePath . 'satekambing_hero.webp',
            ],
            [
                'slug' => 'loh-jinawi',
                'category' => 'Barang',
                'subtitle' => 'Toko barang antik dan unik yang menjual gelang tasbih, aksesoris klasik, serta koleksi bernuansa tradisional.',
                'location' => 'Mejobo',
                'kecamatan_slug' => 'mejobo',
                'image' => $baseRelativePath . 'lohjinawi_hero.webp',
            ],
            [
                'slug' => 'toko-auralia',
                'category' => 'Barang',
                'subtitle' => 'Toko swalayan yang menyediakan berbagai kebutuhan sehari-hari, mulai dari bahan pokok hingga perlengkapan rumah tangga.',
                'location' => 'Mejobo',
                'kecamatan_slug' => 'mejobo',
                'image' => $baseRelativePath . 'tokoauralia_hero.webp',
            ],
            [
                'slug' => 'sekar-modiste',
                'category' => 'Lainnya',
                'subtitle' => 'Toko pakaian yang menyediakan berbagai busana wanita, jasa jahit, dan modifikasi pakaian dengan desain elegan.',
                'location' => 'Mejobo',
                'kecamatan_slug' => 'mejobo',
                'image' => $baseRelativePath . 'sekar_hero.webp',
            ],
            [
                'slug' => 'hasna-fashion',
                'category' => 'Lainnya',
                'subtitle' => 'Toko pakaian yang menyediakan berbagai busana muslim dan modern dengan harga terjangkau.',
                'location' => 'Mejobo',
                'kecamatan_slug' => 'mejobo',
                'image' => $baseRelativePath . 'hasna_hero.webp',
            ],
            // UNDAAN
            [
                'slug' => 'queen-seblak-prasmanan',
                'category' => 'Makanan',
                'subtitle' => 'Seblak dengan berbagai topping dan level pedas yang bisa dipilih.',
                'location' => 'Undaan',
                'kecamatan_slug' => 'undaan',
                'image' => $baseRelativePath . 'queenseblak_hero.webp',
            ],
            [
                'slug' => 'ayam-geprek-mak-ginting',
                'category' => 'Makanan',
                'subtitle' => 'Ayam geprek renyah dengan sambal pedas khas Kudus.',
                'location' => 'Undaan',
                'kecamatan_slug' => 'undaan',
                'image' => $baseRelativePath . 'geprekmakginting_hero.webp',
            ],
            [
                'slug' => 'warung-sate-dan-gule-pak-sugiyo',
                'category' => 'Makanan',
                'subtitle' => 'Sate kambing empuk dan gule gurih khas Kudus.',
                'location' => 'Undaan',
                'kecamatan_slug' => 'undaan',
                'image' => $baseRelativePath . 'warungsatedangule_hero.webp',
            ],
            [
                'slug' => 'mj-teknik',
                'category' => 'Jasa',
                'subtitle' => 'Layanan instalasi listrik dan servis alat rumah tangga.',
                'location' => 'Undaan',
                'kecamatan_slug' => 'undaan',
                'image' => $baseRelativePath . 'mjteknik_hero.webp',
            ],
            [
                'slug' => 'fotocopy-dan-jasa-travel',
                'category' => 'Jasa',
                'subtitle' => 'Layanan fotokopi cepat dan travel antar kota.',
                'location' => 'Undaan',
                'kecamatan_slug' => 'undaan',
                'image' => $baseRelativePath . 'fotocopy_hero.webp',
            ],
            [
                'slug' => 'ngabus-rejo',
                'category' => 'Barang',
                'subtitle' => 'Toko bahan makanan yang menyediakan berbagai kebutuhan dapur lengkap dengan harga bersahabat dan kualitas terbaik.',
                'location' => 'Undaan',
                'kecamatan_slug' => 'undaan',
                'image' => $baseRelativePath . 'ngabusrejo_hero.webp',
            ],
            [
                'slug' => 'nano-distro',
                'category' => 'Lainnya',
                'subtitle' => 'Toko pakaian pria yang menjual berbagai koleksi fashion kasual dan streetwear dengan gaya modern dan harga terjangkau.',
                'location' => 'Undaan',
                'kecamatan_slug' => 'undaan',
                'image' => $baseRelativePath . 'nanodistro_hero.webp',
            ],
            [
                'slug' => 'ilbabalanos',
                'category' => 'Lainnya',
                'subtitle' => 'Toko pakaian yang menyediakan berbagai busana modern dan kasual untuk pria maupun wanita dengan harga bersahabat.',
                'location' => 'Undaan',
                'kecamatan_slug' => 'undaan',
                'image' => $baseRelativePath . 'ilbabalanos_hero.webp',
            ],
        ];

        foreach ($dataListings as $data) {
            if (!isset($umkms[$data['slug']])) {
                $this->command->warn('UMKM (Listing) tidak ditemukan: ' . $data['slug'] . '. Dilewati.');
                continue;
            }

            UmkmListing::updateOrCreate(
                ['umkm_id' => $umkms[$data['slug']]],
                [
                    'category' => $data['category'],
                    'subtitle' => $data['subtitle'],
                    'location' => $data['location'],
                    'kecamatan_slug' => $data['kecamatan_slug'],
                    'image' => $data['image'], // Sekarang hanya menyimpan 'uploads/umkm/namafile.webp'
                    'status' => 'active',
                ]
            );
        }
    }
}
