<?php

namespace Database\Seeders;

use App\Models\Umkm;
use App\Models\Category;
use Illuminate\Database\Seeder;

class UmkmSeeder extends Seeder
{
    public function run(): void
    {
        $baseUrl = 'uploads/umkm/';

        $umkms = [
            // BAE
            [
                'name' => 'Warung Makan Om W',
                'slug' => 'warung-makan-om-w',
                'category' => 'Makanan',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'omw_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Makan Om W"',
                'hero_subtitle' => 'Warung sederhana khas Kudus dengan cita rasa rumahan yang lezat dan harga bersahabat.',
                'description' => 'Warung sederhana dengan menu rumahan khas Kudus yang lezat dan terjangkau.',
                'about' => '<strong>Warung Makan Om W</strong> adalah warung makan di Desa Bacin, Kec. Bae, Kabupaten Kudus yang menyajikan aneka lauk rumahan. Cocok untuk makan sehari-hari dengan suasana santai.',
                'rating' => 4.7,
            ],
            [
                'name' => 'Ayam Geprek Jawi',
                'slug' => 'ayam-geprek-jawi',
                'category' => 'Makanan',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'geprekjawi_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Ayam Geprek Jawi"',
                'hero_subtitle' => 'Menyajikan ayam geprek pedas dengan sambal khas yang menggugah selera.',
                'description' => 'Outlet ayam geprek dengan rasa pedas khas Kudus dan harga mahasiswa.',
                'about' => '<strong>Ayam Geprek Jawi</strong> adalah outlet ayam geprek yang berlokasi di Kota Kudus, dekat kampus UMK, dengan variasi sambal pedas sebagai daya tariknya.',
                'rating' => 4.0,
            ],
            [
                'name' => 'Soto Lamongan Mbak Yuli',
                'slug' => 'soto-lamongan-mbak-yuli',
                'category' => 'Makanan',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'lamonganyuli_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Soto Lamongan Mbak Yuli"',
                'hero_subtitle' => 'Soto Lamongan gurih dengan koya melimpah dan potongan ayam kampung.',
                'description' => 'Warung soto dengan cita rasa Lamongan dan koya melimpah di Kudus.',
                'about' => '<strong>Soto Lamongan Mbak Yuli</strong> adalah warung soto yang menyajikan citarasa Lamongan di Kudus; soto ayam kuah bening dengan koya khas yang menggugah selera.',
                'rating' => 4.3,
            ],
            [
                'name' => 'Es Cincau Pasundan',
                'slug' => 'es-cincau-pasundan',
                'category' => 'Minuman',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'cincaupasundan_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Es Cincau Pasundan"',
                'hero_subtitle' => 'Minuman segar dengan cincau hitam khas Pasundan dan gula merah cair.',
                'description' => 'Minuman cincau hitam khas Pasundan dengan cita rasa segar dan manis alami dari gula merah.',
                'about' => '<strong>Es Cincau Pasundan</strong> di Bendokerep, Bae, Kudus adalah kedai minuman yang populer dengan harga terjangkau dan menu cincau alami.',
                'rating' => 4.7,
            ],
            [
                'name' => 'Jasa Tulis Kudus',
                'slug' => 'jasa-tulis-kudus',
                'category' => 'Jasa',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'jasatulis_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Jasa Tulis Kudus"',
                'hero_subtitle' => 'Melayani jasa pengetikan, cetak dokumen, dan administrasi harian.',
                'description' => 'Layanan pengetikan, cetak dokumen, dan administrasi yang buka 24 jam di Kudus.',
                'about' => '<strong>Jasa Tulis Kudus</strong> merupakan layanan pengetikan dan cetak dokumen yang berlokasi di Panjang, Bae, Kudus. Pelayanan cepat dan buka selama 24 jam membuatnya cocok untuk kebutuhan mendesak seperti tugas sekolah, administrasi, dan cetak cepat.',
                'rating' => 5.0,
            ],

            // DAWE
            [
                'name' => 'Swike Dawe Restaurant',
                'slug' => 'swike-dawe-restaurant',
                'category' => 'Makanan',
                'kecamatan' => 'Dawe',
                'hero_image' => $baseUrl . 'swikedawe_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Swike Dawe Restaurant"',
                'hero_subtitle' => 'Restoran legendaris menawarkan swike (kodok kuah tauco) khas Kudus.',
                'description' => 'Restoran khas Kudus yang menyajikan swike kuah tauco dan berbagai menu tradisional legendaris.',
                'about' => '<strong>Swike Dawe Restaurant</strong> adalah salah satu tempat kuliner khas Kudus yang terkenal dengan menu swike — kodok kuah tauco — dan telah menjadi destinasi lokal sejak lama.',
                'rating' => 4.3,
            ],
            [
                'name' => 'WEKATE GANK',
                'slug' => 'wekate-gank',
                'category' => 'Minuman',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'wekategank_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "WEKATE GANK"',
                'hero_subtitle' => 'Kafe & lounge nongkrong malam dengan suasana kekinian di Kudus.',
                'description' => 'Kafe dan lounge dengan suasana modern dan santai, buka 24 jam penuh untuk menemani waktu nongkrongmu di Kudus.',
                'about' => '<strong>WEKATE GANK</strong> adalah tempat nongkrong malam di Kudus yang menawarkan suasana santai, musik, dan menu kafe/lounge yang cocok untuk anak muda.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Rumah Makan Mak Kiyem',
                'slug' => 'rumah-makan-mak-kiyem',
                'category' => 'Makanan',
                'kecamatan' => 'Dawe',
                'hero_image' => $baseUrl . 'makkiyem_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Rumah Makan Mak Kiyem"',
                'hero_subtitle' => 'Warung makan malam hingga siang dengan aneka menu rumahan dan lodeh khas Kudus.',
                'description' => 'Warung makan khas Kudus yang menyajikan aneka menu rumahan seperti pecel dan rames lodeh dengan harga terjangkau.',
                'about' => '<strong>Rumah Makan Mak Kiyem</strong> adalah warung makan populer di Desa Cendono, Kec. Dawe, Kudus yang menyediakan menu makan malam hingga pagi, dengan suasana santai dan rasa masakan rumahan yang khas.',
                'rating' => 4.2,
            ],
            [
                'name' => 'Jasa Angkut & Pasir & Bata Merah Jumbo',
                'slug' => 'jasa-angkut-dan-pasir-bata-merah-jumbo',
                'category' => 'Jasa',
                'kecamatan' => 'Dawe',
                'hero_image' => $baseUrl . 'jasaangkut_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Jasa Angkut & Pasir & Bata Merah Jumbo"',
                'hero_subtitle' => 'Melayani kebutuhan material bangunan dan pengiriman barang dengan cepat, aman, dan terpercaya.',
                'description' => 'Melayani pengiriman pasir, bata merah jumbo, dan jasa angkut untuk kebutuhan rumah, proyek, maupun toko bangunan dengan harga bersaing dan pelayanan ramah.',
                'about' => '<strong>Jasa Angkut & Pasir & Bata Merah Jumbo</strong> merupakan penyedia layanan pengiriman bahan bangunan dan material konstruksi di wilayah Kudus dan sekitarnya. Layanan meliputi pengantaran pasir, bata merah jumbo, serta jasa angkut berbagai kebutuhan proyek secara efisien dan profesional.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Ayam Geprek Sai',
                'slug' => 'ayam-geprek-sai',
                'category' => 'Makanan',
                'kecamatan' => 'Dawe',
                'hero_image' => $baseUrl . 'ayamgepreksai_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Ayam Geprek Sai"',
                'hero_subtitle' => 'Rasakan sensasi ayam geprek dengan sambal pilihan dan cita rasa khas yang disukai semua kalangan.',
                'description' => 'Nikmati ayam geprek renyah dengan sambal pedas yang bisa kamu pilih sendiri tingkatnya. Cocok untuk makan di tempat maupun pesan antar.',
                'about' => '<strong>Ayam Geprek Sai</strong> menyajikan ayam geprek dengan sambal pedas menggoda dan bumbu khas rumahan yang gurih.',
                'rating' => 4.3,
            ],

            // GEBOG
            [
                'name' => 'Warung Makan Mbah Sapar',
                'slug' => 'warung-makan-mbah-sapar',
                'category' => 'Makanan',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'mbahsapar_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Makan Mbah Sapar"',
                'hero_subtitle' => 'Warung makan rumahan populer untuk sarapan dengan menu khas lokal di Kudus.',
                'description' => 'Warung makan khas Kudus yang menyajikan sop daging kerbau, nasi pecel, dan berbagai jamu tradisional segar.',
                'about' => '<strong>Warung Makan Mbah Sapar</strong> adalah warung makan di Desa Gondosari, Kec. Gebog, Kabupaten Kudus yang dikenal sebagai tempat sarapan favorit.',
                'rating' => 4.5,
            ],
            [
                'name' => 'Nasi Uduk dan Nasi Kuning Gang Satu',
                'slug' => 'nasi-uduk-dan-nasi-kuning-gang-satu',
                'category' => 'Makanan',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'nasiuduk_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Nasi Uduk dan Nasi Kuning Gang Satu"',
                'hero_subtitle' => 'Kedai sarapan pagi menyajikan nasi uduk dan nasi kuning khas Kudus sejak pagi hari.',
                'description' => 'Warung sarapan khas Kudus yang menyajikan nasi uduk dan nasi kuning dengan cita rasa gurih dan lauk lengkap.',
                'about' => '<strong>Nasi Uduk dan Nasi Kuning Gang Satu</strong> adalah warung sarapan populer di Gebog, Kudus yang buka sejak pagi.',
                'rating' => 4.9,
            ],
            [
                'name' => 'Sari Rasa Bakso Malvinas',
                'slug' => 'sari-rasa-bakso-malvinas',
                'category' => 'Makanan',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'baksomalvinas_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Sari Rasa Bakso Malvinas"',
                'hero_subtitle' => 'Nikmati kelezatan bakso khas Kudus dengan kuah gurih, daging pilihan, dan cita rasa yang selalu bikin rindu.',
                'description' => 'Bakso dengan kuah gurih dan daging sapi pilihan, disajikan hangat bersama mie, tahu, dan pangsit.',
                'about' => '<strong>Sari Rasa Bakso Malvinas</strong> merupakan kedai bakso favorit warga Kudus yang dikenal dengan kuah kaldunya yang gurih.',
                'rating' => 4.5,
            ],
            [
                'name' => 'Warung Makan Mak Ru',
                'slug' => 'warung-makan-mak-ru',
                'category' => 'Makanan',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'warungmakanmakru_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Makan Mak Ru"',
                'hero_subtitle' => 'Sajian masakan rumahan khas Kudus dengan cita rasa autentik, harga terjangkau, dan porsi yang memuaskan.',
                'description' => 'Nikmati berbagai pilihan masakan rumahan khas Kudus di Warung Makan Mak Ru.',
                'about' => '<strong>Warung Makan Mak Ru</strong> dikenal dengan hidangan rumahan lezat seperti sayur lodeh, tempe goreng, ayam opor.',
                'rating' => 4.4,
            ],
            [
                'name' => 'Kasehito Works',
                'slug' => 'kasehito-works',
                'category' => 'Jasa',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'kasehitoworks_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Kasehito Works"',
                'hero_subtitle' => 'Membantu kamu mengubah ide menjadi video menarik dengan sentuhan kreatif dan hasil berkualitas tinggi.',
                'description' => 'Layanan Kasehito Works mencakup pemotongan video, color grading, motion graphic, sound design, dan penyesuaian efek visual.',
                'about' => '<strong>Kasehito Works</strong> merupakan penyedia jasa pengeditan video yang berfokus pada hasil berkualitas dan visual storytelling yang kuat.',
                'rating' => 3.3,
            ],

            // JATI
            [
                'name' => 'Cakrawala Sego Sambel',
                'slug' => 'cakrawala-sego-sambel',
                'category' => 'Makanan',
                'kecamatan' => 'Jati',
                'hero_image' => $baseUrl . 'cakrawala_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Cakrawala Sego Sambel"',
                'hero_subtitle' => 'Warung makan malam hingga larut yang populer dengan sego sambel dan lauk goreng-gorengan di Kudus.',
                'description' => 'Warung makan malam khas Kudus yang menyajikan sego sambel dengan lauk goreng seperti ayam kampung, bebek, bandeng, dan entog.',
                'about' => '<strong>Cakrawala Sego Sambel</strong> adalah rumah makan yang berlokasi di Jl. Jend. Ahmad Yani No.1, Getas Pejaten, Kudus.',
                'rating' => 4.4,
            ],
            [
                'name' => 'Nasi Opor Sunggingan',
                'slug' => 'nasi-opor-sunggingan',
                'category' => 'Makanan',
                'kecamatan' => 'Jati',
                'hero_image' => $baseUrl . 'oporsungginan_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Nasi Opor Sunggingan"',
                'hero_subtitle' => 'Nikmati sajian nasi opor dengan kuah santan gurih, ayam empuk, dan cita rasa tradisional yang autentik khas Kudus.',
                'description' => 'Nasi opor ayam dengan kuah santan gurih dan bumbu rempah pilihan, disajikan hangat bersama nasi putih, sambal, dan lauk tambahan.',
                'about' => '<strong>Nasi Opor Sunggingan</strong> merupakan salah satu kuliner khas Kudus yang terkenal dengan opor ayamnya yang gurih dan lembut.',
                'rating' => 4.5,
            ],
            [
                'name' => 'Warung Enthog Pak Badi',
                'slug' => 'warung-enthog-pak-badi',
                'category' => 'Makanan',
                'kecamatan' => 'Jati',
                'hero_image' => $baseUrl . 'enthogpakbadi_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Enthog Pak Badi"',
                'hero_subtitle' => 'Rasakan kelezatan daging enthog empuk dengan bumbu rempah khas Jawa, disajikan dengan nasi hangat dan sambal pedas.',
                'description' => 'Nikmati kelezatan daging enthog yang dimasak dengan santan gurih dan rempah pilihan di Warung Enthog Pak Badi.',
                'about' => '<strong>Warung Enthog Pak Badi</strong> merupakan kuliner legendaris di Kudus yang terkenal dengan olahan enthog berbumbu rempah kuat.',
                'rating' => 4.6,
            ],
            [
                'name' => 'Jasa Powder Coating & Platting Kudus',
                'slug' => 'jasa-powder-coating-dan-platting-kudus',
                'category' => 'Jasa',
                'kecamatan' => 'Jati',
                'hero_image' => $baseUrl . 'powdercoating_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Jasa Powder Coating & Platting Kudus"',
                'hero_subtitle' => 'Layanan pengecatan dan pelapisan logam dengan hasil rapi, kuat, dan tahan karat.',
                'description' => 'Percayakan finishing logam Anda pada Jasa Powder Coating & Platting Kudus. Spesialis powder coating & chrome plating.',
                'about' => '<strong>Jasa Powder Coating & Platting Kudus</strong> adalah solusi lengkap untuk kebutuhan finishing logam berkualitas premium di Kudus dan sekitarnya.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Kedai Es Bang Maman',
                'slug' => 'kedai-es-bang-maman',
                'category' => 'Minuman',
                'kecamatan' => 'Jati',
                'hero_image' => $baseUrl . 'esbangmaman_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Kedai Es Bang Maman"',
                'hero_subtitle' => 'Nikmati kesegaran berbagai varian es buatan Bang Maman, dari es campur, es teler, hingga es buah segar.',
                'description' => 'Kedai Es Bang Maman menyajikan berbagai pilihan minuman segar seperti es campur, es teler, es buah, dan es dawet.',
                'about' => '<strong>Kedai Es Bang Maman</strong> merupakan tempat favorit warga Kudus untuk menikmati minuman dingin segar di siang hari.',
                'rating' => 4.9,
            ],

            // JEKULO
            [
                'name' => 'Jus Pojokan',
                'slug' => 'jus-pojokan',
                'category' => 'Minuman',
                'kecamatan' => 'Jekulo',
                'hero_image' => $baseUrl . 'juspojokan_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Jus Pojokan"',
                'hero_subtitle' => 'Nikmati beragam jus buah segar, kopi susu kekinian, dan camilan ringan dalam suasana santai.',
                'description' => 'Jus Pojokan menawarkan berbagai minuman segar mulai dari jus buah alami seperti alpukat, jeruk, dan mangga.',
                'about' => '<strong>Jus Pojokan</strong> merupakan kedai minuman dan tempat nongkrong populer di Kudus yang menyajikan aneka jus segar.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Kedai Twins Seblak Bandung n Juice Jekulo',
                'slug' => 'kedai-twins-seblak-bandung-juice-jekulo',
                'category' => 'Makanan',
                'kecamatan' => 'Jekulo',
                'hero_image' => $baseUrl . 'kedaytwins_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Kedai Twins Seblak Bandung & Juice Jekulo"',
                'hero_subtitle' => 'Nikmati perpaduan pedas gurih khas Seblak Bandung dan kesegaran jus buah alami.',
                'description' => 'Kedai Twins menghadirkan menu spesial Seblak Bandung dengan cita rasa pedas nikmat serta pilihan jus buah segar.',
                'about' => '<strong>Kedai Twins Seblak Bandung n Juice Jekulo</strong> menyajikan cita rasa khas Seblak Bandung yang pedas, gurih, dan menggugah selera.',
                'rating' => 4.1,
            ],
            [
                'name' => 'Lentog Tanjung Bang Saiful',
                'slug' => 'lentog-tanjung-bang-saiful',
                'category' => 'Makanan',
                'kecamatan' => 'Jekulo',
                'hero_image' => $baseUrl . 'lentogbangsyaiful_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Lentog Tanjung Bang Saiful"',
                'hero_subtitle' => 'Nikmati perpaduan lontong lembut, sayur lodeh gurih, dan sambal khas Kudus yang melegenda.',
                'description' => 'Lentog Tanjung Bang Saiful menyajikan perpaduan sempurna antara lontong, sayur lodeh, dan sambal khas Kudus.',
                'about' => '<strong>Lentog Tanjung Bang Saiful</strong> merupakan salah satu kuliner khas Kudus yang terkenal dengan kelezatan lentognya.',
                'rating' => 4.6,
            ],
            [
                'name' => 'Berkah Es Buah',
                'slug' => 'berkah-es-buah',
                'category' => 'Minuman',
                'kecamatan' => 'Jekulo',
                'hero_image' => $baseUrl . 'berkahesbuah_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Berkah Es Buah"',
                'hero_subtitle' => 'Nikmati kesegaran potongan buah segar dengan sirup manis, susu kental, dan es serut yang menyegarkan.',
                'description' => 'Segelas penuh kesegaran buah-buahan tropis dengan sirup dan susu yang manis dan lembut.',
                'about' => '<strong>Berkah Es Buah</strong> adalah tempat favorit untuk menikmati es buah segar di Kudus.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Warnet Jaya Sentosa',
                'slug' => 'warnet-jaya-sentosa',
                'category' => 'Jasa',
                'kecamatan' => 'Jekulo',
                'hero_image' => $baseUrl . 'warnetjayasentosa_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warnet Jaya Sentosa"',
                'hero_subtitle' => 'Nikmati pengalaman gaming terbaik dengan koneksi cepat, PC gaming lengkap, dan suasana nyaman.',
                'description' => 'Warnet Jaya Sentosa menyediakan fasilitas lengkap mulai dari PC gaming high-end, koneksi internet cepat, printer, hingga minuman dan snack ringan.',
                'about' => '<strong>Warnet Jaya Sentosa</strong> adalah pilihan utama bagi gamer dan pelajar di Kudus.',
                'rating' => 4.8,
            ],

            // KALIWUNGU
            [
                'name' => 'Jahe Rempah Leggit',
                'slug' => 'jahe-rempah-leggit',
                'category' => 'Minuman',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'jaherempahreggit_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Jahe Rempah Leggit"',
                'hero_subtitle' => 'Nikmati sensasi hangat dan sehat dari perpaduan jahe segar, rempah pilihan, dan madu asli.',
                'description' => 'Minuman Jahe Rempah Leggit dibuat dengan jahe segar dan rempah alami yang direbus untuk menghasilkan rasa hangat dan aromatik.',
                'about' => '<strong>Jahe Rempah Leggit</strong> menghadirkan minuman tradisional berbasis jahe dan rempah pilihan.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Warung Makan Bu Carik',
                'slug' => 'warung-makan-bu-carik',
                'category' => 'Makanan',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'warungmakanbucarik_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Makan Bu Carik"',
                'hero_subtitle' => 'Nikmati hidangan tradisional dengan cita rasa autentik, porsi melimpah, dan harga terjangkau.',
                'description' => 'Warung Makan Bu Carik menyediakan hidangan berkualitas dengan porsi yang pas dan harga terjangkau.',
                'about' => '<strong>Warung Makan Bu Carik</strong> menyajikan berbagai masakan tradisional khas Kudus, mulai dari lontong sayur, nasi pecel, hingga lauk pauk rumah.',
                'rating' => 4.1,
            ],
            [
                'name' => 'Tehatea Indonesia',
                'slug' => 'tehatea-indonesia',
                'category' => 'Minuman',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'tehatea_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Tehatea Indonesia"',
                'hero_subtitle' => 'Nikmati berbagai minuman teh hangat maupun dingin dengan rasa autentik, paduan rempah dan bahan alami.',
                'description' => 'Tehatea Indonesia Minuman teh premium dengan varian hangat & dingin, rempah alami, dan topping kekinian.',
                'about' => '<strong>Tehatea Indonesia</strong> adalah gerai minuman teh kekinian yang menggabungkan tradisi rasa Indonesia dengan sentuhan modern.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Warung Makan 2 Putra',
                'slug' => 'warung-makan-2-putra',
                'category' => 'Makanan',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'warungmakan2putra_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Makan 2 Putra"',
                'hero_subtitle' => 'Nikmati hidangan rumahan dengan cita rasa autentik, porsi melimpah, dan harga terjangkau.',
                'description' => 'Warung Makan 2 Putra menawarkan hidangan rumah yang lezat, porsi pas, dan harga terjangkau.',
                'about' => '<strong>Warung Makan 2 Putra</strong> menyajikan berbagai masakan khas Kudus dengan resep rumahan.',
                'rating' => 4.6,
            ],
            [
                'name' => 'Jasa Angkut Barang',
                'slug' => 'jasa-angkut-barang',
                'category' => 'Jasa',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'jasaangkutbarang_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Jasa Angkut Barang"',
                'hero_subtitle' => 'Melayani pengangkutan barang untuk kebutuhan rumah tangga, kantor, atau usaha dengan aman dan tepat waktu.',
                'description' => 'Layanan Jasa Angkut Barang kami menjamin pengiriman barang aman, cepat, dan efisien.',
                'about' => '<strong>Jasa Angkut Barang</strong> menyediakan layanan angkut barang dengan tenaga profesional, kendaraan sesuai kebutuhan, dan harga transparan.',
                'rating' => 5.0,
            ],

            // KOTA KUDUS
            [
                'name' => 'Susu Moeria',
                'slug' => 'susu-moeria',
                'category' => 'Minuman',
                'kecamatan' => 'Kudus Kota',
                'hero_image' => $baseUrl . 'susumoeria_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Susu Moeria"',
                'hero_subtitle' => 'Nikmati kesegaran susu murni pilihan yang diolah higienis dan tersedia dalam berbagai varian rasa.',
                'description' => 'Susu Moeria menyajikan susu murni segar dengan rasa khas yang alami dan menyehatkan.',
                'about' => '<strong>Susu Moeria</strong> merupakan produsen sekaligus penjual susu murni segar yang berlokasi di Kudus.',
                'rating' => 4.4,
            ],
            [
                'name' => 'Ramboo Chicken',
                'slug' => 'ramboo-chicken',
                'category' => 'Makanan',
                'kecamatan' => 'Kudus Kota',
                'hero_image' => $baseUrl . 'ramboo_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Ramboo Chicken"',
                'hero_subtitle' => 'Nikmati cita rasa ayam geprek khas Kudus dengan berbagai pilihan menu lezat dan harga terjangkau.',
                'description' => 'Ramboo Chicken dikenal dengan ayam geprek dan sambal koreknya yang pedas menggugah selera.',
                'about' => '<strong>Ramboo Chicken</strong> adalah sebuah usaha kuliner populer di Kudus yang berlokasi di daerah Krandon.',
                'rating' => 4.5,
            ],
            [
                'name' => 'Es Gempol Pak Masykur',
                'slug' => 'es-gempol-pak-masykur',
                'category' => 'Minuman',
                'kecamatan' => 'Kudus Kota',
                'hero_image' => $baseUrl . 'gempol_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Es Gempol Pak Masykur"',
                'hero_subtitle' => 'Rasakan kesegaran es gempol dengan santan gurih, gula merah manis, dan aroma pandan yang khas.',
                'description' => 'Es Gempol Pak Masykur menawarkan cita rasa klasik yang memadukan manisnya gula merah dan gurihnya santan.',
                'about' => '<strong>Es Gempol Pak Masykur</strong> merupakan salah satu minuman tradisional khas Kudus yang telah melegenda.',
                'rating' => 4.7,
            ],
            [
                'name' => 'Sultan Barber Top',
                'slug' => 'sultan-barber-top',
                'category' => 'Jasa',
                'kecamatan' => 'Kudus Kota',
                'hero_image' => $baseUrl . 'sultanbarbertop_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Sultan Barber Top"',
                'hero_subtitle' => 'Barbershop modern di Kudus yang menawarkan potongan rambut bergaya, layanan premium, dan suasana nyaman.',
                'description' => 'Sultan Barber Top adalah barbershop modern yang menjadi salah satu destinasi perawatan rambut pria terpopuler di Kudus.',
                'about' => '<strong>Sultan Barber Top</strong> adalah barbershop profesional yang mengutamakan kualitas layanan dan kenyamanan pelanggan.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Soto Kud: Soto Kudus Bu Jatmi',
                'slug' => 'soto-kudus-bu-jatmi',
                'category' => 'Makanan',
                'kecamatan' => 'Kudus Kota',
                'hero_image' => $baseUrl . 'sotokudusbujatmi_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Soto Kudus Bu Jatmi"',
                'hero_subtitle' => 'Warung soto legendaris yang menjadi ikon kuliner khas Kudus, menyajikan cita rasa autentik.',
                'description' => 'Soto Kudus Bu Jatmi merupakan salah satu kuliner paling terkenal di Kudus yang telah melayani pelanggan selama bertahun-tahun.',
                'about' => '<strong>Soto Kudus Bu Jatmi</strong> adalah warung makan yang telah lama dikenal masyarakat Kudus karena kelezatan soto khasnya.',
                'rating' => 4.5,
            ],

            // MEJOBO
            [
                'name' => 'XGAM_Tech',
                'slug' => 'xgam-tech',
                'category' => 'Jasa',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'xgamtech_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "XGAM Tech"',
                'hero_subtitle' => 'Layanan profesional untuk perbaikan, upgrade, dan perawatan komputer maupun laptop dengan harga bersahabat.',
                'description' => 'XGAM_Tech melayani servis komputer dan laptop, instal ulang sistem, upgrade RAM atau SSD, pembersihan kipas.',
                'about' => '<strong>XGAM_Tech</strong> adalah penyedia jasa servis komputer dan laptop yang berlokasi di Kudus.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Jasa Las dan Bubut Mulyo Rejo',
                'slug' => 'jasa-las-dan-bubut-mulyo-rejo',
                'category' => 'Jasa',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'jasalas_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Jasa Las dan Bubut Mulyo Rejo"',
                'hero_subtitle' => 'Melayani berbagai pekerjaan las, bubut, dan perakitan logam dengan hasil kuat, rapi, dan presisi.',
                'description' => 'Jasa Las dan Bubut Mulyo Rejo melayani pembuatan pagar, kanopi, tralis, dan komponen mesin dengan hasil rapi dan tahan lama.',
                'about' => '<strong>Jasa Las dan Bubut Mulyo Rejo</strong> merupakan bengkel logam profesional di Kudus yang melayani berbagai kebutuhan pengerjaan logam.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Putra Kalimosodo',
                'slug' => 'putra-kalimosodo',
                'category' => 'Jasa',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'kalimosodo_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Putra Kalimosodo"',
                'hero_subtitle' => 'Menyediakan berbagai bahan bangunan serta layanan angkut material dengan armada lengkap dan tepat waktu.',
                'description' => 'Putra Kalimosodo melayani penjualan berbagai jenis material seperti pasir, batu, semen, dan sirtu.',
                'about' => '<strong>Putra Kalimosodo</strong> merupakan penyedia material bangunan dan jasa transportasi yang berpengalaman di wilayah Kudus.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Ikan Bakar Nasuky Mubarok Jepang',
                'slug' => 'ikan-bakar-nasuky-mubarok-jepang',
                'category' => 'Makanan',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'ikanbakar_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Ikan Bakar Nasuky Mubarok Jepang"',
                'hero_subtitle' => 'Nikmati ikan bakar lezat dengan bumbu rempah khas dan suasana makan nyaman di daerah Jepang, Kudus.',
                'description' => 'Ikan Bakar Nasuky Mubarok Jepang dikenal dengan sajian ikan bakar segar yang dimasak menggunakan bumbu rempah tradisional khas Nusantara.',
                'about' => '<strong>Ikan Bakar Nasuky Mubarok Jepang</strong> adalah tempat makan populer di kawasan Jepang, Kudus, yang menyajikan ikan bakar segar dengan bumbu khas.',
                'rating' => 4.1,
            ],
            [
                'name' => 'RM Bu Sarah',
                'slug' => 'rm-bu-sarah',
                'category' => 'Makanan',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'rmbusarah_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "RM Bu Sarah"',
                'hero_subtitle' => 'Nikmati berbagai hidangan rumahan khas Jawa dengan cita rasa autentik dan suasana nyaman seperti di rumah sendiri.',
                'description' => 'Rumah Makan Bu Sarah dikenal sebagai tempat makan yang menyajikan aneka masakan rumahan khas Jawa dengan rasa lezat.',
                'about' => '<strong>Rumah Makan Bu Sarah</strong> merupakan salah satu rumah makan populer di Kudus yang menyajikan menu masakan rumahan khas Jawa.',
                'rating' => 4.3,
            ],
            [
                'name' => 'Queen Seblak Prasmanan',
                'slug' => 'queen-seblak-prasmanan',
                'category' => 'Makanan',
                'kecamatan' => 'Undaan',
                'hero_image' => $baseUrl . 'queenseblak_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Queen Seblak Prasmanan"',
                'hero_subtitle' => 'Rasakan sensasi seblak pedas gurih dengan berbagai pilihan topping yang bisa kamu ambil sesuka hati.',
                'description' => 'Queen Seblak Prasmanan menawarkan konsep seblak prasmanan pertama di Kudus.',
                'about' => '<strong>Queen Seblak Prasmanan</strong> hadir untuk pecinta seblak dengan konsep unik dan modern.',
                'rating' => 4.4,
            ],
            [
                'name' => 'Ayam Geprek Mak Ginting',
                'slug' => 'ayam-geprek-mak-ginting',
                'category' => 'Makanan',
                'kecamatan' => 'Undaan',
                'hero_image' => $baseUrl . 'geprekmakginting_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Ayam Geprek Mak Ginting"',
                'hero_subtitle' => 'Ayam goreng renyah yang digeprek dengan sambal super pedas khas Mak Ginting.',
                'description' => 'Ayam Geprek Mak Ginting dikenal dengan sambalnya yang meledak di lidah tapi tetap nikmat.',
                'about' => '<strong>Ayam Geprek Mak Ginting</strong> menyajikan ayam goreng tepung yang digeprek bersama sambal ulek khas.',
                'rating' => 4.9,
            ],
            [
                'name' => 'Warung Sate & Flor Pak Sugiyo',
                'slug' => 'warung-sate-dan-gule-pak-sugiyo',
                'category' => 'Makanan',
                'kecamatan' => 'Undaan',
                'hero_image' => $baseUrl . 'warungsatedangule_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Sate & Gule Pak Sugiyo"',
                'hero_subtitle' => 'Nikmati sate kambing empuk dan gule gurih beraroma rempah yang selalu bikin pelanggan datang lagi.',
                'description' => 'Warung Sate & Gule Pak Sugiyo sudah dikenal luas di Kudus sebagai tempat legendaris untuk menikmati sate kambing dan gule.',
                'about' => '<strong>Warung Sate & Gule Pak Sugiyo</strong> adalah destinasi kuliner legendaris di Undaan, Kudus, yang telah bertahan selama puluhan tahun.',
                'rating' => 4.9,
            ],
            [
                'name' => 'MJ Teknik',
                'slug' => 'mj-teknik',
                'category' => 'Jasa',
                'kecamatan' => 'Undaan',
                'hero_image' => $baseUrl . 'mjteknik_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "MJ Teknik"',
                'hero_subtitle' => 'Melayani instalasi listrik, servis pompa air, dan perbaikan berbagai peralatan rumah tangga.',
                'description' => 'MJ Teknik menyediakan layanan profesional untuk instalasi listrik, perbaikan pompa air, servis sible, serta perbaikan peralatan rumah tangga.',
                'about' => '<strong>MJ Teknik</strong> melayani berbagai kebutuhan teknis rumah tangga, mulai dari instalasi listrik baru, perbaikan pompa air dan sible.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Fotocopy & Jasa Travel',
                'slug' => 'fotocopy-dan-jasa-travel',
                'category' => 'Jasa',
                'kecamatan' => 'Undaan',
                'hero_image' => $baseUrl . 'fotocopy_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Fotocopy & Jasa Travel"',
                'hero_subtitle' => 'Melayani jasa fotokopi, print, scan, serta layanan travel antar kota dengan pelayanan ramah.',
                'description' => 'Fotocopy & Jasa Travel menyediakan berbagai layanan harian seperti fotokopi dokumen, cetak berwarna, penjilidan, hingga layanan travel cepat.',
                'about' => '<strong>Fotocopy & Jasa Travel</strong> hadir untuk memenuhi kebutuhan masyarakat akan layanan percetakan dokumen dan transportasi.',
                'rating' => 5.0,
            ],
        ];

        foreach ($umkms as $data) {
            $category = Category::where('name', $data['category'])->first();

            if ($category) {
                Umkm::updateOrCreate(
                    ['slug' => $data['slug']],
                    [
                        'category_id' => $category->id,
                        'kecamatan' => $data['kecamatan'],
                        'name' => $data['name'],
                        'hero_image' => $data['hero_image'],
                        'hero_title' => $data['hero_title'],
                        'hero_subtitle' => $data['hero_subtitle'],
                        'description' => $data['description'],
                        'about' => $data['about'],
                        'rating' => $data['rating'],
                        'status' => 'active',
                    ]
                );
            }
        }
    }
}