<?php

namespace Database\Seeders;

use App\Models\Umkm;
use App\Models\Category;
use Illuminate\Database\Seeder;

class UmkmSeeder extends Seeder
{
    public function run(): void
    {
        $baseUrl = 'uploads/umkm/';

        $umkms = [
            [
                'name' => 'Warung Makan Om W',
                'slug' => 'warung-makan-om-w',
                'category' => 'Makanan',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'omw_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Makan Om W"',
                'hero_subtitle' => 'Warung sederhana khas Kudus dengan cita rasa rumahan yang lezat dan harga bersahabat.',
                'description' => 'Warung sederhana dengan menu rumahan khas Kudus yang lezat dan terjangkau.',
                'about' => '<strong>Warung Makan Om W</strong> adalah warung makan di Desa Bacin, Kec. Bae, Kabupaten Kudus yang menyajikan aneka lauk rumahan. Cocok untuk makan sehari-hari dengan suasana santai.',
                'rating' => 4.7,
            ],
            [
                'name' => 'Ayam Geprek Jawi',
                'slug' => 'ayam-geprek-jawi',
                'category' => 'Makanan',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'geprekjawi_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Ayam Geprek Jawi"',
                'hero_subtitle' => 'Menyajikan ayam geprek pedas dengan sambal khas yang menggugah selera.',
                'description' => 'Outlet ayam geprek dengan rasa pedas khas Kudus dan harga mahasiswa.',
                'about' => '<strong>Ayam Geprek Jawi</strong> adalah outlet ayam geprek yang berlokasi di Kudus Kota, dekat kampus UMK, dengan variasi sambal pedas sebagai daya tariknya.',
                'rating' => 4.0,
            ],
            [
                'name' => 'Soto Lamongan Mbak Yuli',
                'slug' => 'soto-lamongan-mbak-yuli',
                'category' => 'Makanan',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'lamonganyuli_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Soto Lamongan Mbak Yuli"',
                'hero_subtitle' => 'Soto Lamongan gurih dengan koya melimpah dan potongan ayam kampung.',
                'description' => 'Warung soto dengan cita rasa Lamongan dan koya melimpah di Kudus.',
                'about' => '<strong>Soto Lamongan Mbak Yuli</strong> adalah warung soto yang menyajikan citarasa Lamongan di Kudus; soto ayam kuah bening dengan koya khas yang menggugah selera.',
                'rating' => 4.3,
            ],
            [
                'name' => 'Es Cincau Pasundan',
                'slug' => 'es-cincau-pasundan',
                'category' => 'Minuman',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'cincaupasundan_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Es Cincau Pasundan"',
                'hero_subtitle' => 'Minuman segar dengan cincau hitam khas Pasundan dan gula merah cair.',
                'description' => 'Minuman cincau hitam khas Pasundan dengan cita rasa segar dan manis alami dari gula merah.',
                'about' => '<strong>Es Cincau Pasundan</strong> di Bendokerep, Bae, Kudus adalah kedai minuman yang populer dengan harga terjangkau dan menu cincau alami.',
                'rating' => 4.7,
            ],
            [
                'name' => 'Jasa Tulis Kudus',
                'slug' => 'jasa-tulis-kudus',
                'category' => 'Jasa',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'jasatulis_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Jasa Tulis Kudus"',
                'hero_subtitle' => 'Melayani jasa pengetikan, cetak dokumen, dan administrasi harian.',
                'description' => 'Layanan pengetikan, cetak dokumen, dan administrasi yang buka 24 jam di Kudus.',
                'about' => '<strong>Jasa Tulis Kudus</strong> merupakan layanan pengetikan dan cetak dokumen yang berlokasi di Panjang, Bae, Kudus. Pelayanan cepat dan buka selama 24 jam membuatnya cocok untuk kebutuhan mendesak seperti tugas sekolah, administrasi, dan cetak cepat.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Resto MVR Kudus',
                'slug' => 'resto-mvr-kudus',
                'category' => 'Makanan',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'restomvr_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Resto MVR Kudus"',
                'hero_subtitle' => 'Restoran modern dengan suasana nyaman yang menyajikan aneka hidangan lezat khas Nusantara.',
                'description' => 'Resto MVR Kudus menghadirkan pengalaman kuliner yang memadukan cita rasa tradisional dan modern. Setiap hidangan diolah dari bahan berkualitas, menjadikannya pilihan tepat bagi pecinta kuliner di Kudus.',
                'about' => '<strong>Resto MVR Kudus</strong> adalah restoran keluarga yang berlokasi di Kudus, menyajikan berbagai hidangan lezat dengan cita rasa khas Indonesia. Dikenal dengan pelayanan ramah dan tempat yang nyaman, cocok untuk makan bersama keluarga maupun acara santai.',
                'rating' => 4.4,
            ],
            [
                'name' => 'VJO Cafe and Bistro',
                'slug' => 'vjo-cafe-bistro',
                'category' => 'Makanan',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'vjocafe_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "VJO Cafe dan Bistro"',
                'hero_subtitle' => 'Cafe dan bistro modern dengan suasana nyaman, menyajikan aneka hidangan dan minuman kekinian.',
                'description' => 'VJO Cafe dan Bistro menghadirkan konsep kuliner kekinian dengan pilihan menu kopi, pasta, hingga hidangan khas Nusantara yang disajikan secara modern.',
                'about' => '<strong>VJO Cafe dan Bistro</strong> merupakan tempat nongkrong favorit di Kudus yang menawarkan beragam menu makanan dan minuman lezat dengan cita rasa modern. Suasananya nyaman dan estetik, cocok untuk bersantai, rapat santai, maupun kumpul bersama teman.',
                'rating' => 3.5,
            ],
            [
                'name' => 'Toko Al Maira',
                'slug' => 'toko-al-maira',
                'category' => 'Barang',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'tokoalmaira_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Toko Al Maira"',
                'hero_subtitle' => 'Toko bahan makanan lengkap yang menyediakan berbagai kebutuhan dapur harian dengan harga terjangkau.',
                'description' => 'Toko Al Maira melayani pembelian bahan makanan dan kebutuhan rumah tangga harian. Cocok untuk belanja keluarga maupun kebutuhan usaha kuliner di sekitar Kudus.',
                'about' => '<strong>Toko Al Maira</strong> merupakan toko bahan makanan yang berlokasi di Kudus. Menyediakan berbagai kebutuhan dapur seperti beras, gula, minyak, tepung, bumbu dapur, dan kebutuhan pokok lainnya dengan kualitas terjamin dan harga bersahabat.',
                'rating' => 4.9,
            ],
            [
                'name' => 'Siskanuna Boutique',
                'slug' => 'siskanuna-boutique',
                'category' => 'Lainnya',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'siskanuna_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Siskanuna Boutique"',
                'hero_subtitle' => 'Butik pakaian wanita yang menyediakan berbagai busana modis, elegan, dan nyaman untuk segala kesempatan.',
                'description' => 'Siskanuna Boutique menghadirkan beragam pakaian wanita dengan gaya kekinian, mulai dari dress, tunik, hijab, hingga aksesori fashion pendukung dengan harga terjangkau.',
                'about' => '<strong>Siskanuna Boutique</strong> merupakan toko pakaian wanita di Kudus yang menawarkan koleksi busana modern, mulai dari pakaian kasual hingga formal. Dengan desain terkini dan bahan berkualitas, butik ini menjadi pilihan tepat bagi wanita yang ingin tampil stylish dan percaya diri.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Terebatik',
                'slug' => 'terebatik',
                'category' => 'Lainnya',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'terebatik_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Terebatik"',
                'hero_subtitle' => 'Butik pakaian wanita yang menghadirkan koleksi busana batik modern, elegan, dan nyaman untuk berbagai acara.',
                'description' => 'Terebatik menyediakan aneka busana batik seperti dress, blouse, outer, hingga setelan kerja dengan bahan berkualitas dan desain kekinian. Cocok untuk acara formal maupun kasual.',
                'about' => '<strong>Terebatik</strong> merupakan butik batik wanita di Kudus yang menawarkan berbagai pilihan busana dengan sentuhan motif batik khas Nusantara. Menggabungkan gaya tradisional dan modern, Terebatik cocok bagi wanita yang ingin tampil anggun dan berkelas.',
                'rating' => 5.0,
            ],
            // DAWE
            [
                'name' => 'Swike Dawe Restaurant',
                'slug' => 'swike-dawe-restaurant',
                'category' => 'Makanan',
                'kecamatan' => 'Dawe',
                'hero_image' => $baseUrl . 'swikedawe_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Swike Dawe Restaurant"',
                'hero_subtitle' => 'Restoran legendaris menawarkan swike (kodok kuah tauco) khas Kudus.',
                'description' => 'Restoran khas Kudus yang menyajikan swike kuah tauco dan berbagai menu tradisional legendaris.',
                'about' => '<strong>Swike Dawe Restaurant</strong> adalah salah satu tempat kuliner khas Kudus yang terkenal dengan menu swike — kodok kuah tauco — dan telah menjadi destinasi lokal sejak lama.',
                'rating' => 4.3,
            ],
            [
                'name' => 'WEKATE GANK',
                'slug' => 'wekate-gank',
                'category' => 'Minuman',
                'kecamatan' => 'Dawe',
                'hero_image' => $baseUrl . 'wekategank_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "WEKATE GANK"',
                'hero_subtitle' => 'Kafe & lounge nongkrong malam dengan suasana kekinian di Kudus.',
                'description' => 'Kafe dan lounge dengan suasana modern dan santai, buka 24 jam penuh untuk menemani waktu nongkrongmu di Kudus.',
                'about' => '<strong>WEKATE GANK</strong> adalah tempat nongkrong malam di Kudus yang menawarkan suasana santai, musik, dan menu kafe/lounge yang cocok untuk anak muda.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Rumah Makan Mak Kiyem',
                'slug' => 'rumah-makan-mak-kiyem',
                'category' => 'Makanan',
                'kecamatan' => 'Dawe',
                'hero_image' => $baseUrl . 'makkiyem_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Rumah Makan Mak Kiyem"',
                'hero_subtitle' => 'Warung makan malam hingga siang dengan aneka menu rumahan dan lodeh khas Kudus.',
                'description' => 'Warung makan khas Kudus yang menyajikan aneka menu rumahan seperti pecel dan rames lodeh dengan harga terjangkau.',
                'about' => '<strong>Rumah Makan Mak Kiyem</strong> adalah warung makan populer di Desa Cendono, Kec. Dawe, Kudus yang menyediakan menu makan malam hingga pagi, dengan suasana santai dan rasa masakan rumahan yang khas.',
                'rating' => 4.2,
            ],
            [
                'name' => 'Jasa Angkut & Pasir & Bata Merah Jumbo',
                'slug' => 'jasa-angkut-dan-pasir-bata-merah-jumbo',
                'category' => 'Jasa',
                'kecamatan' => 'Dawe',
                'hero_image' => $baseUrl . 'jasaangkut_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Jasa Angkut & Pasir & Bata Merah Jumbo"',
                'hero_subtitle' => 'Melayani kebutuhan material bangunan dan pengiriman barang dengan cepat, aman, dan terpercaya.',
                'description' => 'Melayani pengiriman pasir, bata merah jumbo, dan jasa angkut untuk kebutuhan rumah, proyek, maupun toko bangunan dengan harga bersaing dan pelayanan ramah.',
                'about' => '<strong>Jasa Angkut & Pasir & Bata Merah Jumbo</strong> merupakan penyedia layanan pengiriman bahan bangunan dan material konstruksi di wilayah Kudus dan sekitarnya. Layanan meliputi pengantaran pasir, bata merah jumbo, serta jasa angkut berbagai kebutuhan proyek secara efisien dan profesional.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Ayam Geprek Sai',
                'slug' => 'ayam-geprek-sai',
                'category' => 'Makanan',
                'kecamatan' => 'Dawe',
                'hero_image' => $baseUrl . 'ayamgepreksai_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Ayam Geprek Sai"',
                'hero_subtitle' => 'Rasakan sensasi ayam geprek dengan sambal pilihan dan cita rasa khas yang disukai semua kalangan. Cocok untuk makan siang, malam, atau pesanan bersama teman dan keluarga.',
                'description' => 'Nikmati ayam geprek renyah dengan sambal pedas yang bisa kamu pilih sendiri tingkatnya. Disajikan dengan nasi hangat dan lauk pendamping, cocok untuk makan di tempat maupun pesan antar. Ayam Geprek Sai Dawe siap jadi pilihan favorit pecinta kuliner pedas di Kudus!',
                'about' => '<strong>Ayam Geprek Sai</strong> menyajikan ayam geprek dengan sambal pedas menggoda dan bumbu khas rumahan yang gurih. Setiap potongan ayam digoreng renyah lalu digeprek dengan sambal segar yang bisa disesuaikan tingkat kepedasannya. Kami berkomitmen memberikan rasa terbaik dengan bahan berkualitas dan pelayanan cepat.',
                'rating' => 4.3,
            ],
            [
                'name' => 'Warung Makan Sendang Mulia',
                'slug' => 'warung-makan-sendang-mulia',
                'category' => 'Makanan',
                'kecamatan' => 'Dawe',
                'hero_image' => $baseUrl . 'sendangmulia_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Makan Sendang Mulia"',
                'hero_subtitle' => 'Warung makan keluarga di Kudus yang menyajikan aneka masakan rumahan lezat dengan cita rasa khas Jawa.',
                'description' => 'Warung makan di Kudus dengan sajian masakan rumahan khas Jawa yang enak, terjangkau, dan cocok untuk makan bersama keluarga.',
                'about' => '<strong>Warung Makan Sendang Mulia</strong> menghadirkan berbagai menu masakan rumahan yang lezat, mulai dari ayam goreng, sayur lodeh, hingga sambal terasi yang menggugah selera. Dikenal dengan rasa autentik dan suasana nyaman, tempat ini menjadi pilihan favorit warga Kudus untuk makan bersama keluarga.',
                'rating' => 4.5,
            ],
            [
                'name' => 'Toko ADIB AZKA',
                'slug' => 'toko-adib-azka',
                'category' => 'Barang',
                'kecamatan' => 'Dawe',
                'hero_image' => $baseUrl . 'tokoadibazka_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Toko ADIB AZKA"',
                'hero_subtitle' => 'Toko perlengkapan rumah tangga di Kudus yang menyediakan berbagai kebutuhan dapur, alat kebersihan, dan perlengkapan harian dengan harga terjangkau.',
                'description' => 'Toko perlengkapan rumah tangga di Kudus dengan berbagai produk kebutuhan harian berkualitas dan harga terjangkau.',
                'about' => '<strong>Toko ADIB AZKA</strong> adalah toko perlengkapan rumah tangga yang menyediakan berbagai produk kebutuhan sehari-hari, mulai dari peralatan dapur, alat kebersihan, hingga perlengkapan mandi dan laundry. Dengan pelayanan ramah dan harga bersahabat, toko ini menjadi pilihan warga sekitar untuk memenuhi kebutuhan rumah tangga mereka.',
                'rating' => 4.1,
            ],
            [
                'name' => 'Toko Sri Dawe',
                'slug' => 'toko-sri-dawe',
                'category' => 'Barang',
                'kecamatan' => 'Dawe',
                'hero_image' => $baseUrl . 'tokosridawe_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Toko Sri Dawe"',
                'hero_subtitle' => 'Toko bahan makanan di Kudus yang menyediakan berbagai kebutuhan dapur seperti beras, minyak, gula, dan bahan pokok lainnya dengan harga terjangkau.',
                'description' => 'Toko bahan makanan di Kudus yang menyediakan kebutuhan pokok dan bumbu dapur lengkap dengan harga terjangkau dan kualitas terjamin.',
                'about' => '<strong>Toko ADIB AZKA</strong> merupakan toko bahan makanan yang melayani kebutuhan pokok sehari-hari masyarakat Kudus. Tersedia beragam bahan dapur seperti beras, minyak goreng, telur, tepung, hingga bumbu dapur lengkap. Dengan pelayanan cepat dan harga bersahabat, toko ini menjadi pilihan utama warga sekitar untuk berbelanja kebutuhan rumah tangga.',
                'rating' => 4.8,
            ],
            [
                'name' => 'Arfan Outfit Kudus',
                'slug' => 'arfan-outfit-kudus',
                'category' => 'Lainnya',
                'kecamatan' => 'Dawe',
                'hero_image' => $baseUrl . 'arfanoutfitkudus_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Arfan Outfit Kudus"',
                'hero_subtitle' => 'Toko pakaian di Kudus yang menyediakan berbagai outfit pria, wanita, dan anak dengan model kekinian dan harga terjangkau.',
                'description' => 'Toko pakaian di Kudus yang menjual berbagai outfit trendi dan berkualitas untuk segala usia, cocok untuk gaya kasual maupun formal.',
                'about' => '<strong>Arfan Outfit Kudus</strong> adalah toko pakaian yang menghadirkan beragam busana modern dan nyaman untuk seluruh keluarga. Tersedia pakaian pria, wanita, dan anak-anak, mulai dari kaos, kemeja, celana, gamis, hingga jilbab. Dengan koleksi fashion terkini dan pelayanan ramah, Arfan Outfit Kudus menjadi destinasi favorit warga Kudus untuk berbelanja pakaian.',
                'rating' => 4.7,
            ],
            [
                'name' => 'Dinda Store DS',
                'slug' => 'dinda-store-ds',
                'category' => 'Lainnya',
                'kecamatan' => 'Dawe',
                'hero_image' => $baseUrl . 'dindastore_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Dinda Store DS"',
                'hero_subtitle' => 'Toko pakaian pria di Kudus yang menyediakan berbagai outfit trendi seperti kaos, kemeja, celana jeans, dan tas dengan harga terjangkau.',
                'description' => 'Toko pakaian pria di Kudus yang menyediakan berbagai model kaos, kemeja, jeans, dan tas dengan gaya kekinian dan harga ramah di kantong.',
                'about' => '<strong>Dinda Store DS</strong> merupakan toko pakaian pria di Kudus yang menawarkan berbagai koleksi fashion modern, mulai dari kaos kasual, kemeja formal, hingga celana jeans berkualitas. Selain itu, tersedia juga berbagai tas dan aksesoris pria yang stylish. Dengan harga bersahabat dan pelayanan ramah, toko ini menjadi pilihan favorit pria muda untuk tampil keren setiap hari.',
                'rating' => 4.4,
            ],
            // GEBOG
            [
                'name' => 'Warung Makan Mbah Sapar',
                'slug' => 'warung-makan-mbah-sapar',
                'category' => 'Makanan',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'mbahsapar_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Makan Mbah Sapar"',
                'hero_subtitle' => 'Warung makan rumahan populer untuk sarapan dengan menu khas lokal di Kudus.',
                'description' => 'Warung makan khas Kudus yang menyajikan sop daging kerbau, nasi pecel, dan berbagai jamu tradisional segar.',
                'about' => '<strong>Warung Makan Mbah Sapar</strong> adalah warung makan di Desa Gondosari, Kec. Gebog, Kabupaten Kudus yang dikenal sebagai tempat sarapan favorit dengan suasana sederhana namun ramai oleh pengunjung lokal.',
                'rating' => 4.5,
            ],
            [
                'name' => 'Nasi Uduk dan Nasi Kuning Gang Satu',
                'slug' => 'nasi-uduk-dan-nasi-kuning-gang-satu',
                'category' => 'Makanan',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'nasiuduk_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Nasi Uduk dan Nasi Kuning Gang Satu"',
                'hero_subtitle' => 'Kedai sarapan pagi menyajikan nasi uduk dan nasi kuning khas Kudus sejak pagi hari.',
                'description' => 'Warung sarapan khas Kudus yang menyajikan nasi uduk dan nasi kuning dengan cita rasa gurih dan lauk lengkap.',
                'about' => '<strong>Nasi Uduk dan Nasi Kuning Gang Satu</strong> adalah warung sarapan populer di Gebog, Kudus yang buka sejak pagi dan menjadi favorit banyak pengunjung untuk menikmati nasi uduk serta nasi kuning cepat saji.',
                'rating' => 4.9,
            ],
            [
                'name' => 'Sari Rasa Bakso Malvinas',
                'slug' => 'sari-rasa-bakso-malvinas',
                'category' => 'Makanan',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'baksomalvinas_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Sari Rasa Bakso Malvinas"',
                'hero_subtitle' => 'Nikmati kelezatan bakso khas Kudus dengan kuah gurih, daging pilihan, dan cita rasa yang selalu bikin rindu.',
                'description' => 'Bakso dengan kuah gurih dan daging sapi pilihan, disajikan hangat bersama mie, tahu, dan pangsit. Cocok dinikmati kapan saja, terutama saat ingin hidangan yang mengenyangkan dan lezat. Sari Rasa Bakso Malvinas siap memanjakan lidah pecinta bakso di Kudus!',
                'about' => '<strong>Sari Rasa Bakso Malvinas</strong> merupakan kedai bakso favorit warga Kudus yang dikenal dengan kuah kaldunya yang gurih dan bakso daging sapi yang kenyal. Disajikan dengan mie, tahu, dan pangsit, menciptakan kombinasi rasa yang pas untuk semua kalangan. Tempat nyaman dan pelayanan ramah membuat pelanggan betah untuk datang kembali.',
                'rating' => 4.5,
            ],
            [
                'name' => 'Warung Makan Mak Ru',
                'slug' => 'warung-makan-mak-ru',
                'category' => 'Makanan',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'warungmakanmakru_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Makan Mak Ru"',
                'hero_subtitle' => 'Sajian masakan rumahan khas Kudus dengan cita rasa autentik, harga terjangkau, dan porsi yang memuaskan. Cocok untuk makan siang maupun santai bersama keluarga.Sajian masakan rumahan khas Kudus dengan cita rasa autentik, harga terjangkau, dan porsi yang memuaskan. Cocok untuk makan siang maupun santai bersama keluarga.',
                'description' => 'Nikmati berbagai pilihan masakan rumahan khas Kudus di Warung Makan Mak Ru. Mulai dari sayur, lauk pauk, hingga sambal pedas yang selalu menggoda selera. Cocok untuk makan bersama keluarga, teman, atau sekadar menikmati hidangan hangat di suasana yang akrab dan bersahaja.',
                'about' => '<strong>Warung Makan Mak Ru</strong> dikenal dengan hidangan rumahan lezat seperti sayur lodeh, tempe goreng, ayam opor, dan berbagai lauk khas Jawa yang menggugah selera. Semua masakan dimasak dengan bumbu tradisional dan disajikan hangat, menciptakan rasa seperti masakan ibu di rumah. Pelayanan ramai ramah dan suasana sederhana membuat pelanggan merasa nyaman dan betah.',
                'rating' => 4.4,
            ],
            [
                'name' => 'Kasehito Works',
                'slug' => 'kasehito-works',
                'category' => 'Jasa',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'kasehitoworks_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Kasehito Works"',
                'hero_subtitle' => 'Membantu kamu mengubah ide menjadi video menarik dengan sentuhan kreatif dan hasil berkualitas tinggi. Cocok untuk konten bisnis, event, YouTube, hingga media sosial.',
                'description' => 'Layanan Kasehito Works mencakup pemotongan video, color grading, motion graphic, sound design, dan penyesuaian efek visual sesuai kebutuhan klien. Setiap proyek dikerjakan dengan detail dan komunikasi yang terbuka agar hasil akhir sesuai harapan. Cocok bagi bisnis, kreator, maupun individu yang ingin tampil lebih profesional melalui video berkualitas.',
                'about' => '<strong>Kasehito Works</strong> merupakan penyedia jasa pengeditan video yang berfokus pada hasil berkualitas dan visual storytelling yang kuat. Kami melayani berbagai kebutuhan editing, mulai dari video promosi, dokumentasi acara, konten YouTube, hingga video sinematik. Dengan teknik editing modern dan pemahaman estetika visual, kami siap membantu kamu menciptakan karya yang menarik dan berkesan.',
                'rating' => 3.3,
            ],
            [
                'name' => 'Basina Food',
                'slug' => 'basina-food',
                'category' => 'Makanan',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'basina_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Basina Food"',
                'hero_subtitle' => 'Rumah makan di Kudus yang menyajikan aneka masakan rumahan dan lauk pauk lezat dengan cita rasa khas Jawa, cocok untuk makan siang maupun acara keluarga.',
                'description' => 'Rumah makan di Kudus yang menyediakan beragam menu masakan rumahan khas Jawa dengan rasa lezat dan harga bersahabat.',
                'about' => '<strong>Basina Food</strong> merupakan rumah makan yang menghadirkan berbagai menu masakan rumahan dengan cita rasa autentik dan bahan-bahan segar. Tersedia beragam lauk seperti ayam goreng, ikan bakar, sayur asem, sambal terasi, dan berbagai pilihan minuman segar. Dengan suasana nyaman dan pelayanan ramah, Basina Food menjadi pilihan favorit warga Kudus untuk menikmati hidangan sehari-hari maupun acara keluarga.',
                'rating' => 4.0,
            ],
            [
                'name' => 'Campaign Coffee',
                'slug' => 'campaign-coffee',
                'category' => 'Minuman',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'campaigncoffee_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Campaign Coffee"',
                'hero_subtitle' => 'Kedai kopi di Kudus yang menyajikan berbagai pilihan kopi dan minuman kekinian seperti espresso, latte, dan teh dengan suasana nyaman untuk bersantai atau bekerja.',
                'description' => 'Kedai kopi di Kudus yang menghadirkan berbagai varian kopi dan minuman non-kopi dengan cita rasa khas dan suasana nyaman.',
                'about' => '<strong>Campaign Coffee</strong> merupakan kedai kopi modern di Kudus yang menjadi tempat favorit bagi pecinta kopi dan penikmat suasana santai. Menyediakan berbagai jenis kopi mulai dari espresso, cappuccino, latte, hingga minuman manual brew seperti V60 dan tubruk. Selain kopi, tersedia juga aneka minuman non-kopi seperti teh, cokelat, dan minuman dingin lainnya. Dengan interior estetik dan pelayanan ramah, Campaign Coffee menjadi destinasi pas untuk nongkrong, bekerja, atau sekadar menikmati secangkir kopi hangat.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Toko TNA JAYA',
                'slug' => 'toko-tna-jaya',
                'category' => 'Barang',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'tokotnajaya_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Toko TNA JAYA"',
                'hero_subtitle' => 'Toko bahan makanan di Kudus yang menyediakan berbagai kebutuhan dapur, mulai dari sembako, bumbu dapur, hingga makanan ringan dengan harga terjangkau dan kualitas terjamin.',
                'description' => 'Toko bahan makanan lengkap di Kudus yang menawarkan sembako, bumbu dapur, makanan ringan, dan berbagai produk rumah tangga lainnya dengan harga terjangkau dan pelayanan cepat.',
                'about' => '<strong>Toko TNA JAYA</strong> merupakan toko bahan makanan yang telah lama melayani masyarakat Kudus dengan menyediakan berbagai kebutuhan dapur dan rumah tangga. Di sini tersedia beragam produk seperti beras, minyak goreng, gula, tepung, bumbu masak, mie instan, serta aneka makanan ringan dan minuman. Dengan pelayanan yang ramah dan harga yang kompetitif, TNA JAYA menjadi pilihan utama bagi warga sekitar untuk berbelanja kebutuhan sehari-hari.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Toko Teguh Sudarsono',
                'slug' => 'toko-teguh-sudarsono',
                'category' => 'Barang',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'tokoteguhsudarsono_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Toko Teguh Sudarsono"',
                'hero_subtitle' => 'Toko bahan makanan di Kudus yang menyediakan berbagai kebutuhan dapur, mulai dari sembako, bumbu dapur, hingga makanan ringan dengan harga terjangkau dan kualitas terjamin.',
                'description' => 'Toko bahan makanan lengkap di Kudus yang menawarkan sembako, bumbu dapur, dan berbagai kebutuhan pokok dengan harga terjangkau dan pelayanan cepat.',
                'about' => '<strong>Toko Teguh Sudarsono</strong> merupakan toko bahan makanan yang telah lama melayani masyarakat Kudus dengan menyediakan berbagai kebutuhan dapur dan rumah tangga. Di sini tersedia beragam produk seperti beras, minyak goreng, gula, tepung, bumbu masak, mie instan, serta aneka makanan ringan dan minuman. Dengan pelayanan yang ramah dan harga yang kompetitif, toko ini menjadi pilihan utama bagi warga sekitar untuk berbelanja kebutuhan sehari-hari.',
                'rating' => 4.8,
            ],
            [
                'name' => 'Nilna Dion Collection',
                'slug' => 'nilna-dion-collection',
                'category' => 'Lainnya',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'nilnadioncollection_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Nilna Dion Collection"',
                'hero_subtitle' => 'Butik pakaian muslim wanita di Kudus yang menyediakan berbagai busana syar’i, gamis, hijab, dan outfit elegan dengan model kekinian serta harga terjangkau.',
                'description' => 'Butik pakaian muslim wanita di Kudus yang menawarkan berbagai pilihan gamis, hijab, dan busana syar’i bergaya modern dengan kualitas unggul dan harga bersahabat.',
                'about' => '<strong>Nilna Dion Collection</strong> adalah butik fashion muslim wanita di Kudus yang menghadirkan koleksi busana syar’i, gamis modern, tunik, dan hijab dengan desain yang anggun dan nyaman dikenakan. Mengutamakan kualitas bahan dan keanggunan gaya, butik ini menjadi pilihan bagi para wanita muslimah yang ingin tampil modis namun tetap sopan. Pelayanan ramah dan koleksi yang selalu up-to-date membuat Nilna Dion Collection semakin digemari pelanggan.',
                'rating' => 4.3,
            ],
            [
                'name' => 'Toko Kastimah',
                'slug' => 'toko-kastimah',
                'category' => 'Barang',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'tokokastimah_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Toko Kastimah"',
                'hero_subtitle' => 'Toko bahan makanan di Kudus yang menyediakan berbagai kebutuhan pokok, mulai dari beras, minyak, gula, hingga bumbu dapur dengan harga terjangkau dan kualitas terjamin.',
                'description' => 'Toko bahan makanan lengkap di Kudus yang menyediakan sembako, bumbu dapur, dan berbagai kebutuhan rumah tangga dengan harga terjangkau dan pelayanan cepat.',
                'about' => '<strong>Toko Kastimah</strong> merupakan toko bahan makanan yang melayani masyarakat Kudus dengan menyediakan berbagai kebutuhan dapur sehari-hari. Di sini tersedia beragam produk seperti beras, tepung, minyak goreng, mie instan, gula, kopi, teh, hingga makanan ringan. Dengan pelayanan ramah dan harga bersahabat, Toko Kastimah menjadi tempat belanja favorit warga sekitar untuk memenuhi kebutuhan rumah tangga.',
                'rating' => 4.3,
            ],
            // JATI
            [
                'name' => 'Cakrawala Sego Sambel',
                'slug' => 'cakrawala-sego-sambel',
                'category' => 'Makanan',
                'kecamatan' => 'Jati',
                'hero_image' => $baseUrl . 'cakrawala_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Cakrawala Sego Sambel"',
                'hero_subtitle' => 'Warung makan malam hingga larut yang populer dengan sego sambel dan lauk goreng-gorengan di Kudus.',
                'description' => 'Warung makan malam khas Kudus yang menyajikan sego sambel dengan lauk goreng seperti ayam kampung, bebek, bandeng, dan entog.',
                'about' => '<strong>Cakrawala Sego Sambel</strong> adalah rumah makan yang berlokasi di Jl. Jend. Ahmad Yani No.1, Getas Pejaten, Kudus. Tempat ini buka sejak sore hingga tengah malam dan menjadi pilihan favorit untuk menikmati kuliner malam hari di Kudus.',
                'rating' => 4.4,
            ],
            [
                'name' => 'Nasi Opor Sunggingan',
                'slug' => 'nasi-opor-sunggingan',
                'category' => 'Makanan',
                'kecamatan' => 'Jati',
                'hero_image' => $baseUrl . 'oporsungginan_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Nasi Opor Sunggingan"',
                'hero_subtitle' => 'Nikmati sajian nasi opor dengan kuah santan gurih, ayam empuk, dan cita rasa tradisional yang autentik khas Kudus.',
                'description' => 'Nasi opor ayam dengan kuah santan gurih dan bumbu rempah pilihan, disajikan hangat bersama nasi putih, sambal, dan lauk tambahan. Cocok untuk sarapan, makan siang, maupun santapan keluarga di setiap kesempatan. Nasi Opor Sunggingan siap memanjakan lidah pecinta kuliner khas Kudus!',
                'about' => '<strong>Nasi Opor Sunggingan</strong> merupakan salah satu kuliner khas Kudus yang terkenal dengan opor ayamnya yang gurih dan lembut. Disajikan bersama nasi putih hangat, sambal, dan pelengkap lainnya, menciptakan cita rasa khas yang selalu dirindukan pelanggan. Dimasak dengan bumbu tradisional turun-temurun, menjadikan setiap suapan penuh kelezatan rumahan.',
                'rating' => 4.5,
            ],
            [
                'name' => 'Warung Enthog Pak Badi',
                'slug' => 'warung-enthog-pak-badi',
                'category' => 'Makanan',
                'kecamatan' => 'Jati',
                'hero_image' => $baseUrl . 'enthogpakbadi_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Enthog Pak Badi"',
                'hero_subtitle' => 'Rasakan kelezatan daging enthog empuk dengan bumbu rempah khas Jawa, disajikan dengan nasi hangat dan sambal pedas yang menggugah selera.',
                'description' => 'Nikmati kelezatan daging enthog yang dimasak dengan santan gurih dan rempah pilihan di Warung Enthog Pak Badi. Disajikan dengan nasi hangat, sambal, dan lalapan segar, cocok untuk pecinta kuliner pedas dan tradisional. Warung Enthog Pak Badi menjadi pilihan tepat untuk menikmati cita rasa khas Kudus yang otentik dan memanjakan lidah.',
                'about' => '<strong>Warung Enthog Pak Badi</strong> merupakan kuliner legendaris di Kudus yang terkenal dengan olahan enthog (entok) berbumbu rempah kuat dan cita rasa khas rumahan. Daging enthog yang empuk dimasak perlahan dengan santan gurih dan bumbu tradisional, menghasilkan rasa kaya dan lezat di setiap suapan. Suasana warung yang sederhana serta pelayanan ramah membuat pelanggan selalu ingin kembali.',
                'rating' => 4.6,
            ],
            [
                'name' => 'Jasa Powder Coating & Platting Kudus',
                'slug' => 'jasa-powder-coating-dan-platting-kudus',
                'category' => 'Jasa',
                'kecamatan' => 'Jati',
                'hero_image' => $baseUrl . 'powdercoating_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Jasa Powder Coating & Platting Kudus"',
                'hero_subtitle' => 'Layanan pengecatan dan pelapisan logam dengan hasil rapi, kuat, dan tahan karat. Cocok untuk komponen otomotif, furniture, hingga industri.',
                'description' => 'Percayakan finishing logam Anda pada Jasa Powder Coating & Platting Kudus. Spesialis powder coating & chrome plating dengan hasil halus, tahan karat, dan warna custom. Cocok untuk otomotif, industri, dan rumah tangga.',
                'about' => '<strong>Jasa Powder Coating & Platting Kudus</strong> adalah solusi lengkap untuk kebutuhan finishing logam berkualitas premium di Kudus dan sekitarnya. Kami mengkhususkan diri dalam <em>powder coating</em> dan <em>chrome plating</em> menggunakan teknologi modern serta bahan baku impor yang ramah lingkungan. Proses pelapisan dilakukan di fasilitas berstandar industri dengan kontrol kualitas ketat pada setiap tahap — mulai dari pembersihan permukaan (sandblasting), aplikasi cat bubuk elektrostatis, hingga pengeringan di oven suhu tinggi (180–200°C) untuk hasil lapisan yang sempurna, merata, dan tahan lama. Kami melayani berbagai jenis material logam seperti besi, aluminium, stainless steel, hingga kuningan, untuk beragam aplikasi: spare part motor & mobil, rangka mebel, komponen mesin, pagar, aksesoris interior, hingga barang custom sesuai desain Anda. Dengan pengalaman lebih dari 10 tahun, tim teknisi tersertifikasi, dan jaminan ketahanan terhadap karat, panas, serta benturan, kami siap memberikan hasil akhir yang tidak hanya estetis, tetapi juga fungsional dan bernilai investasi jangka panjang. Hubungi kami sekarang untuk konsultasi gratis dan penawaran khusus!',
                'rating' => 5.0,
            ],
            [
                'name' => 'Kedai Es Bang Maman',
                'slug' => 'kedai-es-bang-maman',
                'category' => 'Minuman',
                'kecamatan' => 'Jati',
                'hero_image' => $baseUrl . 'esbangmaman_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Kedai Es Bang Maman"',
                'hero_subtitle' => 'Nikmati kesegaran berbagai varian es buatan Bang Maman, dari es campur, es teler, hingga es buah segar yang manis dan menyegarkan di setiap tegukan.',
                'description' => 'Kedai Es Bang Maman menyajikan berbagai pilihan minuman segar seperti es campur, es teler, es buah, dan es dawet. Dengan bahan segar dan sirup racikan khas, setiap minuman dijamin menyegarkan dan bikin ketagihan. Cocok dinikmati kapan pun, terutama saat cuaca panas di Kudus!',
                'about' => '<strong>Kedai Es Bang Maman</strong> merupakan tempat favorit warga Kudus untuk menikmati minuman dingin segar di siang hari. Dikenal dengan bahan-bahan alami dan racikan sirup khas buatan sendiri, setiap sajian es di sini menghadirkan kesejukan dan rasa manis yang pas di lidah. Suasana kedai yang santai membuat tempat ini cocok untuk nongkrong bersama teman maupun keluarga.',
                'rating' => 4.9,
            ],
            [
                'name' => 'Gravitasi Teras Muria',
                'slug' => 'gravitasi-teras-muria',
                'category' => 'Makanan',
                'kecamatan' => 'Jati',
                'hero_image' => $baseUrl . 'gravitasiterasmuria_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Gravitasi Teras Muria"',
                'hero_subtitle' => 'Tempat makan nyaman di Kudus yang menyajikan beragam menu khas nusantara dengan cita rasa rumahan dan suasana santai di bawah rindangnya Teras Muria.',
                'description' => 'Restoran keluarga di Kudus dengan konsep alam terbuka, menyuguhkan makanan khas nusantara dan minuman segar dalam suasana nyaman dan tenang. Cocok untuk makan bersama keluarga, teman, atau acara kecil di akhir pekan.',
                'about' => '<strong>Gravitasi Teras Muria</strong> adalah restoran keluarga yang menghadirkan suasana hangat dan alami khas pegunungan Muria. Menyajikan berbagai hidangan tradisional seperti ayam bakar, nasi goreng, sop iga, dan menu minuman segar, restoran ini menjadi tempat favorit untuk bersantai dan menikmati kelezatan kuliner lokal. Dengan pelayanan ramah dan pemandangan yang asri, setiap kunjungan ke Gravitasi Teras Muria selalu meninggalkan kesan hangat.',
                'rating' => 4.5,
            ],
            [
                'name' => 'Toko Kliwon',
                'slug' => 'toko-kliwon',
                'category' => 'Barang',
                'kecamatan' => 'Jati',
                'hero_image' => $baseUrl . 'tokokliwon_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Toko Kliwon"',
                'hero_subtitle' => 'Toko perlengkapan rumah tangga di Kudus yang menyediakan berbagai kebutuhan sehari-hari seperti peralatan dapur, kebersihan, hingga perlengkapan rumah dengan harga terjangkau.',
                'description' => 'Toko perlengkapan rumah tangga di Kudus yang menawarkan berbagai produk seperti alat dapur, peralatan kebersihan, dan kebutuhan rumah tangga lainnya dengan harga terjangkau dan pelayanan ramah.',
                'about' => '<strong>Toko Kliwon</strong> merupakan toko perlengkapan rumah tangga yang sudah dikenal masyarakat Kudus karena menyediakan berbagai kebutuhan rumah tangga lengkap di satu tempat. Di sini tersedia berbagai produk seperti ember, sapu, alat masak, piring, gelas, rak plastik, hingga perlengkapan kebersihan rumah. Dengan kualitas produk yang baik dan harga yang ramah di kantong, Toko Kliwon menjadi solusi praktis untuk melengkapi kebutuhan rumah Anda.',
                'rating' => 4.6,
            ],
            [
                'name' => 'Toko Happy Kids',
                'slug' => 'toko-happy-kids',
                'category' => 'Lainnya',
                'kecamatan' => 'Jati',
                'hero_image' => $baseUrl . 'tokohappykids_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Toko Happy Kids"',
                'hero_subtitle' => 'Toko pakaian anak di Kudus yang menyediakan berbagai busana lucu, nyaman, dan berkualitas untuk anak laki-laki maupun perempuan.',
                'description' => 'Toko Happy Kids menyediakan pakaian anak dengan beragam model dan ukuran, cocok untuk kebutuhan sekolah, bermain, atau acara spesial. Mengutamakan kenyamanan, kualitas bahan, dan desain yang ceria.',
                'about' => '<strong>Toko Happy Kids</strong> merupakan toko pakaian anak yang berlokasi di Kudus. Menawarkan berbagai pilihan busana anak mulai dari pakaian harian, baju pesta, hingga perlengkapan bayi dengan desain menarik dan bahan yang lembut di kulit. Dengan koleksi terbaru dan harga bersahabat, Toko Happy Kids menjadi pilihan tepat bagi orang tua yang ingin anaknya tampil modis dan nyaman.',
                'rating' => 4.5,
            ],
            [
                'name' => 'Nobby Kudus Extension Mall',
                'slug' => 'nobby-kudus-extension',
                'category' => 'Lainnya',
                'kecamatan' => 'Jati',
                'hero_image' => $baseUrl . 'nobbykudusextension_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Nobby Kudus Extension Mall"',
                'hero_subtitle' => 'Butik busana muslim wanita modern yang menyediakan berbagai koleksi hijab, gamis, dan pakaian modest fashion berkualitas di Kudus.',
                'description' => 'Nobby Kudus Extension Mall menghadirkan busana muslim wanita dengan berbagai pilihan gaya — mulai dari kasual hingga formal — yang memadukan desain modern dengan sentuhan syar’i, cocok untuk berbagai aktivitas dan acara spesial.',
                'about' => '<strong>Nobby Kudus Extension Mall</strong> merupakan butik busana muslim wanita yang berlokasi di Kudus. Menawarkan berbagai koleksi pakaian seperti gamis, tunik, hijab, dan dress modern dengan desain elegan dan bahan nyaman. Toko ini menjadi destinasi belanja favorit bagi wanita yang ingin tampil anggun dan modis sesuai syariat.',
                'rating' => 5.0,
            ],
            // JEKULO
            [
                'name' => 'Jus Pojokan',
                'slug' => 'jus-pojokan',
                'category' => 'Minuman',
                'kecamatan' => 'Jekulo',
                'hero_image' => $baseUrl . 'juspojokan_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Jus Pojokan"',
                'hero_subtitle' => 'Nikmati beragam jus buah segar, kopi susu kekinian, dan camilan ringan dalam suasana santai di pojokan favorit warga Kudus.',
                'description' => 'Jus Pojokan menawarkan berbagai minuman segar mulai dari jus buah alami seperti alpukat, jeruk, dan mangga, hingga minuman kekinian seperti kopi susu dan matcha latte. Cocok untuk melepas penat di sore hari atau menemani obrolan ringan. Tempat nyaman, rasa enak, dan harga bersahabat membuat Jus Pojokan jadi pilihan pas di Kudus!',
                'about' => '<strong>Jus Pojokan</strong> merupakan kedai minuman dan tempat nongkrong populer di Kudus yang menyajikan aneka jus segar, kopi susu, serta minuman dingin kekinian. Dengan bahan buah pilihan dan racikan rasa yang pas, setiap sajian di Jus Pojokan menghadirkan kesejukan alami dan suasana hangat untuk bersantai bersama teman atau keluarga.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Kedai Twins Seblak Bandung n Juice Jekulo',
                'slug' => 'kedai-twins-seblak-bandung-juice-jekulo',
                'category' => 'Minuman',
                'kecamatan' => 'Jekulo',
                'hero_image' => $baseUrl . 'kedaytwins_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Kedai Twins Seblak Bandung & Juice Jekulo"',
                'hero_subtitle' => 'Nikmati perpaduan pedas gurih khas Seblak Bandung dan kesegaran jus buah alami dalam satu tempat yang nyaman dan ramah di Jekulo, Kudus.',
                'description' => 'Kedai Twins menghadirkan menu spesial Seblak Bandung dengan cita rasa pedas nikmat serta pilihan jus buah segar yang menyegarkan. Tersedia berbagai level pedas dan topping sesuai selera. Cocok dinikmati kapan saja, baik untuk makan siang, malam, maupun sekadar bersantai. Suasana santai dan harga bersahabat menjadikan Kedai Twins Seblak Bandung n Juice Jekulo pilihan pas bagi pecinta kuliner pedas di Kudus.',
                'about' => '<strong>Kedai Twins Seblak Bandung n Juice Jekulo</strong> menyajikan cita rasa khas Seblak Bandung yang pedas, gurih, dan menggugah selera, dipadukan dengan aneka jus segar pilihan. Dimasak dengan bumbu Bandung asli dan topping beragam seperti kerupuk, sosis, ceker, dan makaroni, setiap porsi menghadirkan sensasi nikmat yang pas di lidah. Kedai ini juga menyediakan berbagai minuman segar sebagai pelengkap, cocok untuk nongkrong santai bersama teman.',
                'rating' => 4.1,
            ],
            [
                'name' => 'Lentog Tanjung Bang Saiful',
                'slug' => 'lentog-tanjung-bang-saiful',
                'category' => 'Makanan',
                'kecamatan' => 'Jekulo',
                'hero_image' => $baseUrl . 'lentogbangsyaiful_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Lentog Tanjung Bang Saiful"',
                'hero_subtitle' => 'Nikmati perpaduan lontong lembut, sayur lodeh gurih, dan sambal khas Kudus yang melegenda. Cita rasa tradisional yang tetap autentik sejak dulu.',
                'description' => 'Lentog Tanjung Bang Saiful menyajikan perpaduan sempurna antara lontong, sayur lodeh, dan sambal khas Kudus. Dengan kuah santan gurih dan bumbu tradisional, setiap porsi menghadirkan kehangatan rasa rumahan. Cocok dinikmati untuk sarapan atau makan siang, terutama bagi pencinta kuliner khas Jawa Tengah.',
                'about' => '<strong>Lentog Tanjung Bang Saiful</strong> merupakan salah satu kuliner khas Kudus yang terkenal dengan kelezatan lentognya. Terbuat dari potongan lontong lembut, disiram dengan sayur lodeh gurih dan sambal pedas manis yang khas, menciptakan rasa yang nikmat di setiap suapan. Dimasak dengan resep turun-temurun, Lentog Tanjung Bang Saiful menjadi favorit warga lokal maupun wisatawan yang ingin menikmati cita rasa Kudus asli.',
                'rating' => 4.6,
            ],
            [
                'name' => 'Berkah Es Buah',
                'slug' => 'berkah-es-buah',
                'category' => 'Minuman',
                'kecamatan' => 'Jekulo',
                'hero_image' => $baseUrl . 'berkahesbuah_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Berkah Es Buah"',
                'hero_subtitle' => 'Nikmati kesegaran potongan buah segar dengan sirup manis, susu kental, dan es serut yang menyegarkan. Cocok dinikmati di siang hari atau saat cuaca panas.',
                'description' => 'Segelas penuh kesegaran buah-buahan tropis dengan sirup dan susu yang manis dan lembut. Berkah Es Buah cocok untuk menemani waktu istirahat, melepas dahaga, atau sekadar menikmati manisnya kesegaran alami di tengah hari yang panas.',
                'about' => '<strong>Berkah Es Buah</strong> adalah tempat favorit untuk menikmati es buah segar di Kudus. Menggunakan berbagai buah pilihan seperti melon, semangka, nanas, pepaya, dan kolang-kaling, disajikan dengan campuran sirup manis dan susu yang pas di lidah. Selain rasanya yang segar, porsi melimpah dan harga terjangkau menjadikannya pilihan tepat untuk semua kalangan.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Warnet Jaya Sentosa',
                'slug' => 'warnet-jaya-sentosa',
                'category' => 'Jasa',
                'kecamatan' => 'Jekulo',
                'hero_image' => $baseUrl . 'warnetjayasentosa_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warnet Jaya Sentosa"',
                'hero_subtitle' => 'Nikmati pengalaman gaming terbaik dengan koneksi cepat, PC gaming lengkap, dan suasana nyaman untuk teman atau kerja sekolah.',
                'description' => 'Warnet Jaya Sentosa menyediakan fasilitas lengkap mulai dari PC gaming high-end, koneksi internet cepat, printer, hingga minuman dan snack ringan. Cocok untuk sesi gaming panjang, belajar kelompok, atau sekadar nongkrong sambil online. Staf ramah siap membantu agar pengalaman Anda selalu menyenangkan.',
                'about' => '<strong>Warnet Jaya Sentosa</strong> adalah pilihan utama bagi gamer dan pelajar di Kudus. Dilengkapi PC gaming terbaru, koneksi internet cepat, dan ruang nyaman, cocok untuk bermain game, browsing, atau belajar. Harga terjangkau membuat semua kalangan bisa menikmati layanan terbaik tanpa khawatir kantong jebol.',
                'rating' => 4.8,
            ],
            [
                'name' => 'Warung Mie Dadat Pak Karnan',
                'slug' => 'warung-mie-dadat',
                'category' => 'Makanan',
                'kecamatan' => 'Jekulo',
                'hero_image' => $baseUrl . 'warungmiedadat_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Mie Dadat Pak Karnan"',
                'hero_subtitle' => 'Warung mie populer di Kudus yang menyajikan berbagai olahan mie lezat dengan cita rasa khas dan harga bersahabat.',
                'description' => 'Warung ini menawarkan beragam menu mie, mulai dari mie goreng, mie rebus, hingga mie pedas spesial. Semua dibuat dari bahan segar dan racikan bumbu pilihan yang menggugah selera. Dengan harga terjangkau, Warung Mie Dadat Pak Karnan menjadi destinasi kuliner yang wajib dicoba di Kudus.',
                'about' => '<strong>Warung Mie Dadat Pak Karnan</strong> merupakan tempat makan yang terkenal di Kudus karena menyajikan aneka mie dengan rasa gurih dan bumbu khas rumahan. Warung ini menjadi favorit banyak pelanggan karena porsinya pas, rasanya konsisten, dan suasananya nyaman untuk makan santai bersama keluarga maupun teman.',
                'rating' => 4.7,
            ],
            [
                'name' => 'Toko Risfan Snack - Pusat Grosir Snack Lengkap di Kudus',
                'slug' => 'toko-risfan-snack',
                'category' => 'Barang',
                'kecamatan' => 'Jekulo',
                'hero_image' => $baseUrl . 'tokorisfan_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Toko Risfan Snack"',
                'hero_subtitle' => 'Toko bahan makanan dan camilan di Kudus yang menyediakan berbagai kebutuhan dapur, jajanan, serta bahan kue dengan harga terjangkau.',
                'description' => 'Toko Risfan Snack menjadi pilihan praktis bagi masyarakat Kudus yang ingin belanja bahan makanan, bumbu dapur, dan camilan dalam satu tempat. Pelayanan ramah dan stok barang yang selalu tersedia menjadikan toko ini salah satu destinasi belanja favorit di daerahnya.',
                'about' => '<strong>Toko Risfan Snack</strong> merupakan toko bahan makanan yang berlokasi di Kudus. Menyediakan berbagai bahan pokok, bumbu dapur, bahan kue, hingga aneka snack kemasan. Toko ini dikenal dengan produknya yang lengkap, berkualitas, dan harga yang bersahabat, cocok untuk kebutuhan rumah tangga maupun usaha kecil.',
                'rating' => 4.3,
            ],
            [
                'name' => 'Js Muslim Collection Kudus',
                'slug' => 'js-muslim-collection',
                'category' => 'Lainnya',
                'kecamatan' => 'Jekulo',
                'hero_image' => $baseUrl . 'jsmuslim_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Js Muslim Collection Kudus"',
                'hero_subtitle' => 'Toko busana muslim di Kudus yang menyediakan berbagai pilihan pakaian syar’i, gamis, hijab, dan aksesori muslimah dengan desain modern dan harga terjangkau.',
                'description' => 'JS Muslim Collection Kudus menghadirkan busana muslim berkualitas dengan harga bersahabat, menjadikannya destinasi belanja favorit bagi masyarakat yang ingin tampil modis dan tetap syar’i.',
                'about' => '<strong>JS Muslim Collection Kudus</strong> merupakan toko pakaian muslim yang berlokasi di Kudus. Menyediakan berbagai koleksi busana muslim seperti gamis, tunik, hijab, dan koko dengan bahan nyaman serta model kekinian. Cocok untuk kebutuhan harian maupun acara spesial.',
                'rating' => 4.9,
            ],
            [
                'name' => 'Kios Hjh Zaroah',
                'slug' => 'kios-hjh',
                'category' => 'Lainnya',
                'kecamatan' => 'Jekulo',
                'hero_image' => $baseUrl . 'kioshjh_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Kios Hjh Zaroah"',
                'hero_subtitle' => 'Toko busana muslim di Kudus yang menyediakan berbagai pilihan pakaian syar’i, gamis, hijab, dan aksesori muslimah dengan desain modern dan harga terjangkau.',
                'description' => 'Kios Hjh Zaroah menghadirkan busana muslim berkualitas dengan harga bersahabat, cocok untuk kegiatan sehari-hari, ibadah, maupun acara spesial.',
                'about' => '<strong>Kios Hjh Zaroah</strong> merupakan toko pakaian muslim yang berlokasi di Kudus. Menawarkan beragam koleksi busana muslim seperti gamis, tunik, hijab, dan koko dengan bahan nyaman serta model yang mengikuti tren. Tempat ini menjadi pilihan tepat bagi keluarga yang ingin tampil sopan namun tetap stylish.',
                'rating' => 4.2,
            ],
            [
                'name' => 'Jahe Rempah Leggit',
                'slug' => 'jahe-rempah-leggit',
                'category' => 'Minuman',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'jaherempahreggit_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Jahe Rempah Leggit"',
                'hero_subtitle' => 'Nikmati sensasi hangat dan sehat dari perpaduan jahe segar, rempah pilihan, dan madu asli. Cocok dinikmati kapan saja untuk tubuh yang lebih bugar.',
                'description' => 'Minuman Jahe Rempah Leggit dibuat dengan jahe segar dan rempah alami yang direbus untuk menghasilkan rasa hangat dan aromatik. Setiap gelas memberikan sensasi pedas manis yang menenangkan, cocok untuk menjaga stamina dan kesehatan tubuh.',
                'about' => '<strong>Jahe Rempah Leggit</strong> menghadirkan minuman tradisional berbasis jahe dan rempah pilihan. Menggunakan bahan-bahan alami seperti jahe, kayu manis, cengkeh, dan madu, setiap tegukan memberikan kehangatan sekaligus kesegaran. Cocok untuk dinikmati saat cuaca dingin atau sebagai minuman sehat harian.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Warung Makan Bu Carik',
                'slug' => 'warung-makan-bu-carik',
                'category' => 'Makanan',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'warungmakanbucarik_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Makan Bu Carik"',
                'hero_subtitle' => 'Nikmati hidangan tradisional dengan cita rasa autentik, porsi melimpah, dan harga terjangkau. Cocok untuk sarapan, makan siang, atau makan malam.',
                'description' => 'Warung Makan Bu Carik menyediakan hidangan berkualitas dengan porsi yang pas dan harga terjangkau. Suasana warung yang nyaman dan pelayanan ramah membuat pengalaman makan Anda menyenangkan setiap kali berkunjung.',
                'about' => '<strong>Warung Makan Bu Carik</strong> menyajikan berbagai masakan tradisional khas Kudus, mulai dari lontong sayur, nasi pecel, hingga lauk pauk rumah yang segar dan lezat. Setiap menu dibuat dengan resep turun-temurun, menjadikan cita rasa tetap autentik dan memuaskan.',
                'rating' => 4.1,
            ],
            [
                'name' => 'Tehatea Indonesia',
                'slug' => 'tehatea-indonesia',
                'category' => 'Minuman',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'tehatea_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Tehatea Indonesia"',
                'hero_subtitle' => 'Nikmati berbagai minuman teh hangat maupun dingin dengan rasa autentik, paduan rempah dan bahan alami. Cocok untuk dinikmati kapan saja sebagai teman santai atau melepas dahaga.',
                'description' => 'Tehatea Indonesia Minuman teh premium dengan varian hangat & dingin, rempah alami, dan topping kekinian. Segar, sehat, dan penuh cita rasa Indonesia.',
                'about' => '<strong>Tehatea Indonesia</strong> adalah gerai minuman teh kekinian yang menggabungkan tradisi rasa Indonesia dengan sentuhan modern dalam setiap tegukan. Kami menghadirkan lebih dari 30 varian minuman berbasis teh premium, mulai dari <em>classic milk tea</em>, <em>teh tarik khas Melayu</em>, hingga inovasi lokal seperti <em>teh rempah jahe sereh</em>, <em>teh hijau pandan</em>, dan <em>fruit tea tropis</em> dengan potongan buah segar. Semua bahan dipilih langsung: daun teh asli dari perkebunan Jawa dan Sumatera, rempah organik, susu segar, serta gula aren murni tanpa pemanis buatan. Proses pembuatan dilakukan secara higienis dengan takaran presisi untuk menjaga konsistensi rasa — apakah Anda memilih versi hangat yang menenangkan di pagi hari atau es blend yang menyegarkan saat siang terik. Selain minuman, kami juga menyediakan <em>topping premium</em> seperti black boba, crystal jelly, aloe vera, dan cheese foam yang creamy. Cocok untuk nongkrong santai, meeting ringan, atau oleh-oleh khas Kudus. Dengan konsep gerai yang instagramable, pelayanan ramah, dan harga terjangkau, <strong>Tehatea Indonesia</strong> hadir untuk menjadi teman setia dalam setiap momen Anda. Kunjungi kami di Kaliwungu dan rasakan bedanya secangkir teh yang dibuat dengan hati!',
                'rating' => 5.0,
            ],
            [
                'name' => 'Warung Makan 2 Putra',
                'slug' => 'warung-makan-2-putra',
                'category' => 'Makanan',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'warungmakan2putra_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Makan 2 Putra"',
                'hero_subtitle' => 'Nikmati hidangan rumahan dengan cita rasa autentik, porsi melimpah, dan harga terjangkau. Cocok untuk sarapan, makan siang, atau makan malam.',
                'description' => 'Warung Makan 2 Putra menawarkan hidangan rumah yang lezat, porsi pas, dan harga terjangkau. Suasana warung nyaman dengan pelayanan ramah menjadikan setiap kunjungan menyenangkan.',
                'about' => '<strong>Warung Makan 2 Putra</strong> menyajikan berbagai masakan khas Kudus dengan resep rumahan. Mulai dari nasi rames, lauk pauk segar, hingga sayur dan sambal rumah, semua disiapkan dengan bahan berkualitas untuk rasa yang lezat dan memuaskan.',
                'rating' => 4.6,
            ],
            [
                'name' => 'Jasa Angkut Barang',
                'slug' => 'jasa-angkut-barang',
                'category' => 'Jasa',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'jasaangkutbarang_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Jasa Angkut Barang"',
                'hero_subtitle' => 'Melayani pengangkutan barang untuk kebutuhan rumah tangga, kantor, atau usaha dengan aman dan tepat waktu.',
                'description' => 'Layanan Jasa Angkut Barang kami menjamin pengiriman barang aman, cepat, dan efisien. Dengan armada kendaraan lengkap dan tenaga ahli, setiap pengangkutan dilakukan dengan hati-hati dan sesuai jadwal.',
                'about' => '<strong>Jasa Angkut Barang</strong> menyediakan layanan angkut barang dengan tenaga profesional, kendaraan sesuai kebutuhan, dan harga transparan. Cocok untuk pindahan rumah, pengiriman barang dagangan, atau kebutuhan logistik lainnya.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Sego Sambel Lek Kas 2',
                'slug' => 'sego-sambel-lek-kas2',
                'category' => 'Makanan',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'segosambel_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Sego Sambel Lek Kas 2"',
                'hero_subtitle' => 'Rumah makan khas Nusantara yang menyajikan hidangan sambel pedas dan lauk goreng favorit dengan cita rasa autentik.',
                'description' => 'Nikmati sensasi pedas gurih dari sambel racikan khas kami, dipadukan dengan lauk goreng pilihan dan nasi hangat. Semua menu disajikan dengan bumbu rempah asli Indonesia, halal, dan selalu segar.',
                'about' => '<strong>Sego Sambel Lek Kas 2</strong> menghadirkan masakan rumahan dengan rasa pedas khas sambel tradisional. Tersedia beragam paket lauk goreng seperti entok, bebek, dan lele, cocok untuk makan siang maupun malam.',
                'rating' => 4.4,
            ],
            [
                'name' => 'Toko Jamaah',
                'slug' => 'toko-jamaah',
                'category' => 'Barang',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'tokojamaah_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Toko Jamaah"',
                'hero_subtitle' => 'Toko bahan makanan di Kudus yang menyediakan berbagai kebutuhan dapur, bumbu masak, dan bahan kue dengan harga terjangkau.',
                'description' => 'Toko Jamaah dikenal dengan produknya yang lengkap, harga bersahabat, dan pelayanan ramah. Menjadi pilihan praktis bagi warga Kudus untuk memenuhi kebutuhan dapur sehari-hari.',
                'about' => '<strong>Toko Jamaah</strong> merupakan toko bahan makanan yang berlokasi di Kudus. Menyediakan aneka bahan pokok, bumbu dapur, tepung, minyak, hingga cemilan ringan. Cocok untuk kebutuhan rumah tangga maupun usaha kuliner.',
                'rating' => 4.0,
            ],
            [
                'name' => 'MM Amanah',
                'slug' => 'mm-amanah',
                'category' => 'Barang',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'mmamanah_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "MM Amanah"',
                'hero_subtitle' => 'Minimarket di Kudus yang menyediakan berbagai kebutuhan harian, bahan makanan, dan perlengkapan rumah tangga dengan harga terjangkau.',
                'description' => 'MM Amanah menawarkan pengalaman belanja yang nyaman dengan produk lengkap dan harga kompetitif. Cocok untuk memenuhi kebutuhan rumah tangga maupun usaha kecil.',
                'about' => '<strong>MM Amanah</strong> merupakan minimarket yang berlokasi di Kudus. Menyediakan berbagai kebutuhan sehari-hari seperti sembako, bahan dapur, makanan ringan, minuman, serta produk kebersihan rumah tangga. Dengan pelayanan ramah dan harga bersahabat, MM Amanah menjadi pilihan belanja praktis untuk keluarga.',
                'rating' => 4.4,
            ],
            [
                'name' => 'Toko Van Helen Serba 35000',
                'slug' => 'toko-van-helen',
                'category' => 'Lainnya',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'tokovanhelen_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Toko Van Helen Serba 35000"',
                'hero_subtitle' => 'Toko pakaian di Kudus yang menawarkan busana trendi dan aksesori gaya dengan harga terjangkau hanya Rp 35.000-an.',
                'description' => 'Toko Van Helen Serba 35000 menghadirkan koleksi fashion terbaru dengan harga tetap Rp 35.000-an — pilihan ideal untuk belanja cepat, hemat, dan modis.',
                'about' => '<strong>Toko Van Helen Serba 35000</strong> merupakan toko pakaian yang berlokasi di Kudus. Menyediakan berbagai pilihan busana kasual, fashion pria dan wanita, serta aksesori dengan harga satu harga Rp 35.000-an. Cocok untuk Anda yang ingin tampil stylish tanpa merogoh kocek dalam-dalam.',
                'rating' => 4.1,
            ],
            [
                'name' => 'Lina Family',
                'slug' => 'lina-family',
                'category' => 'Lainnya',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'linafamily_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Lina Family"',
                'hero_subtitle' => 'Toko pakaian keluarga di Kudus yang menyediakan busana trendi untuk pria, wanita, dan anak-anak dengan harga bersahabat.',
                'description' => 'Lina Family menghadirkan pilihan fashion lengkap untuk keluarga dengan model modern dan harga yang bersahabat. Cocok untuk belanja seluruh anggota keluarga dalam satu kunjungan.',
                'about' => '<strong>Lina Family</strong> merupakan toko pakaian yang berlokasi di Kudus, Jl. Kudus-Jepara Km. 5, Mijen, Kec. Kaliwungu. Menawarkan koleksi lengkap untuk seluruh keluarga — mulai busana harian hingga acara khusus. Fokus pada kenyamanan, gaya, dan harga kompetitif.',
                'rating' => 4.3,
            ],
            [
                'name' => 'Susu Moeria',
                'slug' => 'susu-moeria',
                'category' => 'Minuman',
                'kecamatan' => 'Kudus Kota',
                'hero_image' => $baseUrl . 'susumoeria_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Susu Moeria"',
                'hero_subtitle' => 'Nikmati kesegaran susu murni 0pilihan yang diolah higienis dan tersedia dalam berbagai varian rasa. Cocok untuk semua usia dan waktu.',
                'description' => 'Susu Moeria menyajikan susu murni segar dengan rasa khas yang alami dan menyehatkan. Setiap botol diproses dengan standar kebersihan tinggi untuk menjaga kualitas gizi dan kesegarannya. Cocok diminum kapan saja untuk menambah energi dan menjaga kesehatan tubuh.',
                'about' => '<strong>Susu Moeria</strong> merupakan produsen sekaligus penjual susu murni segar yang berlokasi di Kudus. Produk susu ini dibuat dari bahan alami tanpa pengawet, menjaga rasa dan kualitas terbaik. Tersedia dalam berbagai varian seperti original, cokelat, stroberi, dan vanila. Dengan cita rasa lembut dan kemasan praktis, Susu Moeria menjadi pilihan favorit bagi pencinta minuman sehat dan bergizi.',
                'rating' => 4.4,
            ],
            [
                'name' => 'Ramboo Chicken',
                'slug' => 'ramboo-chicken',
                'category' => 'Makanan',
                'kecamatan' => 'Kudus Kota',
                'hero_image' => $baseUrl . 'ramboo_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Ramboo Chicken"',
                'hero_subtitle' => 'Nikmati cita rasa ayam geprek khas Kudus dengan berbagai pilihan menu lezat dan harga terjangkau.',
                'description' => 'Ramboo Chicken dikenal dengan ayam geprek dan sambal koreknya yang pedas menggugah selera. Menggunakan bahan segar dan bumbu khas Kudus yang autentik.',
                'about' => '<strong>Ramboo Chicken</strong> adalah sebuah usaha kuliner populer di Kudus yang berlokasi di daerah Krandon. Tempat makan ini mengkhususkan diri pada sajian aneka hidangan olahan ayam yang beragam, menjadikannya pilihan favorit bagi warga lokal. Menu andalan mereka berfokus pada ayam geprek dan rice bowl dengan berbagai saus khas.',
                'rating' => 4.8,
            ],
            [
                'name' => 'Es Gempol Pak Masykur',
                'slug' => 'es-gempol-pak-masykur',
                'category' => 'Minuman',
                'kecamatan' => 'Kudus Kota',
                'hero_image' => $baseUrl . 'gempol_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Es Gempol Pak Masykur"',
                'hero_subtitle' => 'Rasakan kesegaran es gempol dengan santan gurih, gula merah manis, dan aroma pandan yang khas. Minuman tradisional yang menyegarkan di setiap tegukan.',
                'description' => 'Es Gempol Pak Masykur menawarkan cita rasa klasik yang memadukan manisnya gula merah dan gurihnya santan. Cocok dinikmati kapan pun untuk melepas dahaga. Racikan tradisionalnya yang autentik menjadikan minuman ini tetap menjadi favorit lintas generasi di Kudus.',
                'about' => '<strong>Es Gempol Pak Masykur</strong> merupakan salah satu minuman tradisional khas Kudus yang telah melegenda. Terbuat dari gempol (bola-bola tepung beras) lembut, disajikan dengan kuah santan gurih dan sirup gula merah alami yang harum pandan. Kesegarannya menjadikan Es Gempol Pak Masykur selalu diburu pelanggan, terutama di hari yang panas.',
                'rating' => 4.7,
            ],
            [
                'name' => 'Sultan Barber Top',
                'slug' => 'sultan-barber-top',
                'category' => 'Jasa',
                'kecamatan' => 'Kudus Kota',
                'hero_image' => $baseUrl . 'sultanbarbertop_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Sultan Barber Top"',
                'hero_subtitle' => 'Barbershop modern di Kudus yang menawarkan potongan rambut bergaya, layanan premium, dan suasana nyaman untuk semua kalangan.',
                'description' => 'Sultan Barber Top adalah barbershop modern yang menjadi salah satu destinasi perawatan rambut pria terpopuler di Kudus. Dengan tim barber berpengalaman, tempat ini menghadirkan berbagai gaya potongan rambut terkini, pelayanan ramah, serta suasana santai dan bersih yang membuat pelanggan merasa nyaman.',
                'about' => '<strong>Sultan Barber Top</strong> adalah barbershop profesional yang mengutamakan kualitas layanan dan kenyamanan pelanggan. Berlokasi strategis di pusat Kudus Kota, Sultan Barber Top menyediakan layanan potong rambut modern, shaving, hair wash, hingga styling dengan produk perawatan rambut terbaik. Mengusung konsep tempat yang cozy dan bergaya urban, barbershop ini menjadi pilihan utama bagi pria yang ingin tampil rapi dan stylish setiap hari.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Soto Kudus Bu Jatmi',
                'slug' => 'soto-kudus-bu-jatmi',
                'category' => 'Makanan',
                'kecamatan' => 'Kudus Kota',
                'hero_image' => $baseUrl . 'sotokudusbujatmi_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Soto Kudus Bu Jatmi"',
                'hero_subtitle' => 'Warung soto legendaris yang menjadi ikon kuliner khas Kudus, menyajikan cita rasa autentik dengan pilihan daging kerbau maupun ayam.',
                'description' => 'Soto Kudus Bu Jatmi merupakan salah satu kuliner paling terkenal di Kudus yang telah melayani pelanggan selama bertahun-tahun. Dikenal dengan kuah bening gurih dan taburan bawang goreng melimpah, warung ini menjadi destinasi wajib bagi pecinta kuliner tradisional.',
                'about' => '<strong>Soto Kudus Bu Jatmi</strong> adalah warung makan yang telah lama dikenal masyarakat Kudus karena kelezatan soto khasnya. Menggunakan resep turun-temurun dengan bumbu rempah pilihan, Soto Kudus Bu Jatmi menawarkan dua varian utama yaitu soto daging kerbau dan soto ayam. Tempatnya sederhana namun selalu ramai pengunjung dari pagi hingga malam hari, baik warga lokal maupun wisatawan yang ingin mencicipi cita rasa asli Kudus.',
                'rating' => 4.5,
            ],
            [
                'name' => 'Treend Steak Kudus',
                'slug' => 'treend-steak-kudus',
                'category' => 'Makanan',
                'kecamatan' => 'Kudus Kota',
                'hero_image' => $baseUrl . 'treendsteak_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang Restoran "Treend Steak Kudus"',
                'hero_subtitle' => 'Restoran steak di Kudus yang menyajikan berbagai pilihan steak lezat dengan cita rasa khas dan harga terjangkau.',
                'description' => 'Nikmati pengalaman kuliner terbaik di Treend Steak Kudus dengan menu steak daging sapi, ayam, dan seafood dengan saus istimewa buatan sendiri.',
                'about' => '<strong>Treend Steak Kudus</strong> adalah restoran yang menyajikan aneka steak premium dengan suasana santai dan nyaman, cocok untuk makan bersama keluarga atau teman. Menggunakan bahan berkualitas dan saus khas yang menggugah selera.',
                'rating' => 4.3,
            ],
            [
                'name' => 'Larees Jaya Electronics',
                'slug' => 'larees-jaya-electronics',
                'category' => 'Barang',
                'kecamatan' => 'Kudus Kota',
                'hero_image' => $baseUrl . 'lareesjaya_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang Toko "Larees Jaya Electronics"',
                'hero_subtitle' => 'Toko elektronik terpercaya di Kudus yang menyediakan berbagai kebutuhan rumah tangga dan peralatan elektronik modern.',
                'description' => 'Tempat terpercaya untuk mendapatkan produk elektronik berkualitas di Kudus. Menyediakan layanan ramah dan garansi resmi.',
                'about' => '<strong>Larees Jaya Electronics</strong> merupakan toko yang menjual beragam produk elektronik seperti TV, kulkas, mesin cuci, kipas angin, dan perlengkapan rumah tangga lainnya dengan harga bersaing.',
                'rating' => 4.9,
            ],
            [
                'name' => 'Es Coklat Cokot Kudus',
                'slug' => 'es-coklat-cokot-kudus',
                'category' => 'Minuman',
                'kecamatan' => 'Kudus Kota',
                'hero_image' => $baseUrl . 'escoklatcokotkudus_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang "Es Coklat Cokot Kudus"',
                'hero_subtitle' => 'Kafe cokelat di Kudus dengan minuman cokelat dingin dan varian topping kekinian.',
                'description' => 'Tempat nongkrong favorit anak muda Kudus dengan harga terjangkau dan suasana santai.',
                'about' => '<strong>Es Coklat Cokot Kudus</strong> menghadirkan minuman cokelat dengan rasa autentik dan topping beragam seperti keju, oreo, dan boba. Cocok untuk penggemar cokelat sejati.',
                'rating' => 4.1,
            ],
            [
                'name' => 'Richie Store Kudus',
                'slug' => 'richie-store-kudus',
                'category' => 'Lainnya',
                'kecamatan' => 'Kudus Kota',
                'hero_image' => $baseUrl . 'richiestore_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang Toko "Richie Store Kudus"',
                'hero_subtitle' => 'Toko pakaian muslim dan fashion modern di Kudus dengan koleksi trendi dan harga bersahabat.',
                'description' => 'Toko fashion pilihan masyarakat Kudus untuk pakaian bergaya modern namun tetap sopan.',
                'about' => '<strong>Richie Store Kudus</strong> menyediakan busana muslim dan kasual untuk pria dan wanita. Koleksinya mencakup gamis, kemeja, dan kaus dengan desain simpel namun elegan.',
                'rating' => 4.9,
            ],
            [
                'name' => 'XGAM_Tech',
                'slug' => 'xgam-tech',
                'category' => 'Jasa',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'xgamtech_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "XGAM Tech"',
                'hero_subtitle' => 'Layanan profesional untuk perbaikan, upgrade, dan perawatan komputer maupun laptop dengan harga bersahabat.',
                'description' => 'XGAM_Tech melayani servis komputer dan laptop, instal ulang sistem, upgrade RAM atau SSD, pembersihan kipas, serta perbaikan software dan hardware. Mengutamakan kejujuran, ketelitian, dan kepuasan pelanggan, menjadikan XGAM_Tech sebagai mitra terpercaya untuk menjaga performa perangkat Anda tetap optimal.',
                'about' => '<strong>XGAM_Tech</strong> adalah penyedia jasa servis komputer dan laptop yang berlokasi di Kudus. Menawarkan layanan seperti instalasi sistem operasi, perbaikan hardware, pembersihan perangkat, hingga upgrade komponen. Dengan tenaga teknisi berpengalaman dan pelayanan cepat, XGAM_Tech menjadi pilihan tepat untuk kebutuhan perangkat kerja maupun gaming Anda.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Jasa Las dan Bubut Mulyo Rejo',
                'slug' => 'jasa-las-dan-bubut-mulyo-rejo',
                'category' => 'Jasa',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'jasalas_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Jasa Las dan Bubut Mulyo Rejo"',
                'hero_subtitle' => 'Melayani berbagai pekerjaan las, bubut, dan perakitan logam dengan hasil kuat, rapi, dan presisi.',
                'description' => 'Layanan las dan bubut untuk kebutuhan industri dan rumah tangga.',
                'about' => '<strong>Jasa Las dan Bubut Mulyo Rejo</strong> merupakan bengkel logam profesional di Kudus yang melayani berbagai kebutuhan pengerjaan logam, mulai dari las besi, stainless, hingga bubut komponen mesin. Dengan tenaga ahli berpengalaman dan peralatan lengkap, Mulyo Rejo siap memberikan hasil pengerjaan yang kuat, rapi, dan sesuai permintaan pelanggan.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Putra Kalimosodo',
                'slug' => 'putra-kalimosodo',
                'category' => 'Jasa',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'kalimosodo_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Putra Kalimosodo"',
                'hero_subtitle' => 'Menyediakan berbagai bahan bangunan serta layanan angkut material dengan armada lengkap dan tepat waktu.',
                'description' => 'Putra Kalimosodo melayani penjualan berbagai jenis material seperti pasir, batu, semen, dan sirtu. Selain itu juga menyediakan jasa transportasi material ke berbagai wilayah Kudus dan sekitarnya dengan pelayanan cepat, aman, dan profesional.',
                'about' => '<strong>Putra Kalimosodo</strong> merupakan penyedia material bangunan dan jasa transportasi yang berpengalaman di wilayah Kudus. Dengan armada kendaraan yang terawat dan tenaga kerja berpengalaman, kami berkomitmen memberikan layanan terbaik dalam pengiriman bahan bangunan, baik untuk proyek kecil maupun besar.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Ikan Bakar Nasuky Mubarok Jepang',
                'slug' => 'ikan-bakar-nasuky-mubarok-jepang',
                'category' => 'Makanan',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'ikanbakar_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Ikan Bakar Nasuky Mubarok Jepang"',
                'hero_subtitle' => 'Nikmati ikan bakar lezat dengan bumbu rempah khas dan suasana makan nyaman di daerah Jepang, Kudus.',
                'description' => 'Ikan Bakar Nasuky Mubarok Jepang dikenal dengan sajian ikan bakar segar yang dimasak menggunakan bumbu rempah tradisional khas Nusantara. Selain ikan bakar, tersedia pula berbagai pilihan menu laut lainnya dengan cita rasa gurih dan pedas yang menggugah selera.',
                'about' => '<strong>Ikan Bakar Nasuky Mubarok Jepang</strong> adalah tempat makan populer di kawasan Jepang, Kudus, yang menyajikan ikan bakar segar dengan bumbu khas. Setiap hidangan disajikan dengan sambal dan lalapan segar, menjadikannya favorit bagi keluarga maupun rombongan yang ingin menikmati hidangan laut dengan cita rasa autentik.',
                'rating' => 4.1,
            ],
            [
                'name' => 'RM Bu Sarah',
                'slug' => 'rm-bu-sarah',
                'category' => 'Makanan',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'rmbusarah_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "RM Bu Sarah"',
                'hero_subtitle' => 'Nikmati berbagai hidangan rumahan khas Jawa dengan cita rasa autentik dan suasana nyaman seperti di rumah sendiri.',
                'description' => 'Rumah Makan Bu Sarah dikenal sebagai tempat makan yang menyajikan aneka masakan rumahan khas Jawa dengan rasa lezat, porsi pas, dan harga terjangkau. Menu favorit seperti ayam goreng, sayur lodeh, tempe bacem, dan sambal terasi selalu menjadi pilihan pelanggan setia.',
                'about' => '<strong>Rumah Makan Bu Sarah</strong> merupakan salah satu rumah makan populer di Kudus yang menyajikan menu masakan rumahan khas Jawa. Dengan cita rasa yang otentik dan suasana santai, tempat ini menjadi pilihan tepat untuk makan siang bersama keluarga atau rekan kerja.',
                'rating' => 4.3,
            ],
            [
                'name' => 'Sate Kambing Pak Brewok Pekeng',
                'slug' => 'sate-kambing-pak-brewok',
                'category' => 'Makanan',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'satekambing_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Sate Kambing Pak Brewok Pekeng"',
                'hero_subtitle' => 'Warung sate kambing di Kudus yang menyajikan sate kambing empuk dengan bumbu lezat dan cita rasa khas lokal.',
                'description' => 'Nikmati sate kambing empuk dan gule kambing gurih di Sate Kambing Pak Brewok Pekeng — cocok untuk makan bersama keluarga maupun teman.',
                'about' => '<strong>Sate Kambing Pak Brewok Pekeng</strong> merupakan rumah makan yang berlokasi di Jl. Budi Utomo No.158, Pekeng, Gulang, Kec. Mejobo, Kabupaten Kudus. Menyajikan sate kambing dan gule kambing dengan resep tradisional dan pelayanan hangat.',
                'rating' => 4.3,
            ],
            [
                'name' => 'Loh Jinawi Olshop (Lapak Gelang Tasbih)',
                'slug' => 'loh-jinawi',
                'category' => 'Barang',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'lohjinawi_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Loh Jinawi Olshop (Lapak Gelang Tasbih)"',
                'hero_subtitle' => 'Toko barang antik dan aksesoris tradisional di Kudus yang menawarkan gelang tasbih dan koleksi unik lainnya.',
                'description' => 'Menjelajahi koleksi unik barang antik dan aksesoris tradisional di Loh Jinawi Olshop — cocok bagi kolektor maupun penggemar item tradisional.',
                'about' => '<strong>Loh Jinawi Olshop (Lapak Gelang Tasbih)</strong> merupakan toko yang berlokasi di Bancak, Payaman, Mejobo, Kabupaten Kudus. Menyediakan gelang tasbih, barang antik, dan aksesoris tradisional dengan harga bersahabat dan koleksi eksklusif.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Toko Auralia Jaya',
                'slug' => 'toko-auralia',
                'category' => 'Barang',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'tokoauralia_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Toko Auralia Jaya"',
                'hero_subtitle' => 'Toko swalayan di Kudus yang menyediakan berbagai kebutuhan sehari-hari mulai dari sembako hingga perlengkapan rumah tangga.',
                'description' => 'Toko Auralia Jaya menawarkan belanja praktis dan cepat dengan produk lengkap untuk kebutuhan keluarga, mulai dari bahan makanan hingga alat kebersihan rumah.',
                'about' => '<strong>Toko Auralia Jaya</strong> merupakan swalayan yang berlokasi di Mejobo, Kudus. Menyediakan berbagai bahan pokok, alat rumah tangga, minuman, dan kebutuhan harian lengkap dalam satu tempat.',
                'rating' => 4.3,
            ],
            [
                'name' => 'Sekar Modiste',
                'slug' => 'sekar-modiste',
                'category' => 'Lainnya',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'sekar_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Sekar Modiste"',
                'hero_subtitle' => 'Toko pakaian wanita di Kudus yang menyediakan berbagai busana dan layanan jahit/modifikasi dengan desain elegan.',
                'description' => 'Sekar Modiste membantu Anda tampil percaya diri dengan model pakaian wanita yang disesuaikan, mulai dari casual hingga formal, lengkap dengan layanan jahit profesional.',
                'about' => '<strong>Sekar Modiste</strong> merupakan butik dan jasa jahit yang berlokasi di Mejobo, Kudus. Menyediakan busana wanita siap pakai, serta layanan jahit dan modifikasi sesuai permintaan pelanggan.',
                'rating' => 4.8,
            ],
            [
                'name' => 'Hasna Fashion 01',
                'slug' => 'hasna-fashion',
                'category' => 'Lainnya',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'hasna_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Hasna Fashion 01"',
                'hero_subtitle' => 'Toko pakaian muslim dan modern di Kudus yang menyediakan koleksi busana wanita dengan harga terjangkau.',
                'description' => 'Hasna Fashion 01 hadir untuk melengkapi gaya wanita muslimah dengan pilihan busana syar’i dan kasual dalam satu tempat belanja yang nyaman.',
                'about' => '<strong>Hasna Fashion 01</strong> merupakan toko pakaian muslim yang berlokasi di Mejobo, Kudus. Menyediakan gamis, tunik, dan hijab dengan desain modern serta bahan nyaman untuk wanita muda hingga dewasa.',
                'rating' => 4.5,
            ],
            [
                'name' => 'Queen Seblak Prasmanan',
                'slug' => 'queen-seblak-prasmanan',
                'category' => 'Makanan',
                'kecamatan' => 'Undaan',
                'hero_image' => $baseUrl . 'queenseblak_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Queen Seblak Prasmanan"',
                'hero_subtitle' => 'Rasakan sensasi seblak pedas gurih dengan berbagai pilihan topping yang bisa kamu ambil sesuka hati.',
                'description' => 'Queen Seblak Prasmanan menawarkan konsep seblak prasmanan pertama di Kudus, di mana pelanggan bisa memilih sendiri bahan dan tingkat kepedasannya. Dengan kuah gurih pedas khas Bandung dan topping melimpah seperti bakso, sosis, ceker, siomay, hingga kerupuk, tempat ini jadi favorit anak muda dan pencinta pedas.',
                'about' => '<strong>Queen Seblak Prasmanan</strong> hadir untuk pecinta seblak dengan konsep unik dan modern. Setiap pengunjung bisa meracik seblak sesuai selera, mulai dari tingkat pedas, jenis kuah, hingga topping. Dengan suasana tempat yang santai dan harga bersahabat, Queen Seblak jadi pilihan tepat untuk nongkrong sambil menikmati seblak pedas nikmat.',
                'rating' => 4.4,
            ],
            [
                'name' => 'Ayam Geprek Mak Ginting',
                'slug' => 'ayam-geprek-mak-ginting',
                'category' => 'Makanan',
                'kecamatan' => 'Undaan',
                'hero_image' => $baseUrl . 'geprekmakginting_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Ayam Geprek Mak Ginting"',
                'hero_subtitle' => 'Ayam goreng renyah yang digeprek dengan sambal super pedas khas Mak Ginting. Cocok buat pecinta pedas sejati!',
                'description' => 'Ayam Geprek Mak Ginting dikenal dengan sambalnya yang meledak di lidah tapi tetap nikmat. Dengan pilihan level pedas, lauk tambahan seperti tahu tempe, dan harga yang ramah di kantong, tempat ini jadi favorit anak muda Kudus untuk makan siang maupun malam.',
                'about' => '<strong>Ayam Geprek Mak Ginting</strong> menyajikan ayam goreng tepung yang digeprek bersama sambal ulek khas yang pedasnya bisa disesuaikan selera. Selain ayam, tersedia juga berbagai lauk pelengkap seperti tempe, tahu, dan terong goreng yang makin lezat jika disantap dengan nasi hangat.',
                'rating' => 4.9,
            ],
            [
                'name' => 'Warung Sate & Gule Pak Sugiyo',
                'slug' => 'warung-sate-dan-gule-pak-sugiyo',
                'category' => 'Makanan',
                'kecamatan' => 'Undaan',
                'hero_image' => $baseUrl . 'warungsatedangule_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Sate & Gule Pak Sugiyo"',
                'hero_subtitle' => 'Nikmati sate kambing empuk dan gule gurih beraroma rempah yang selalu bikin pelanggan datang lagi.',
                'description' => 'Warung Sate & Gule Pak Sugiyo sudah dikenal luas di Kudus sebagai tempat legendaris untuk menikmati sate kambing dan gule yang kaya rasa. Dagingnya empuk, bumbu kacangnya gurih manis, dan kuah gulenya kental beraroma rempah. Cocok untuk makan siang maupun malam bersama keluarga.',
                'about' => '<strong>Warung Sate & Gule Pak Sugiyo</strong> adalah destinasi kuliner legendaris di Undaan, Kudus, yang telah bertahan selama puluhan tahun berkat resep turun-temurun dan komitmen pada kualitas. Kami hanya menggunakan daging kambing muda pilihan — segar, tanpa bau, dan dipotong langsung setiap pagi — untuk menghasilkan sate yang empuk dan beraroma khas saat dibakar di atas arang. Bumbu kacangnya diracik secara tradisional dengan campuran kacang tanah sangrai, bawang, cabe, dan rempah rahasia, menghasilkan rasa gurih manis yang pas di lidah. Sedangkan gule kambing kami dimasak perlahan selama berjam-jam dengan santan kental, kapulaga, cengkeh, dan kayu manis, sehingga kuahnya kaya rempah, hangat, dan sangat cocok disantap dengan nasi putih atau lontong. Setiap porsi disajikan dengan acar mentimun, bawang merah, dan sambal kecap yang menambah kesegaran. Warung kami buka dari pagi hingga malam, selalu ramai dikunjungi keluarga, pekerja kantor, hingga wisatawan yang ingin merasakan kuliner asli Kudus. Datanglah dan nikmati tradisi rasa yang terjaga — karena di sini, setiap tusuk sate dan sendok gule adalah cerita tentang rumah dan kebersamaan.',
                'rating' => 4.9,
            ],
            [
                'name' => 'MJ Teknik',
                'slug' => 'mj-teknik',
                'category' => 'Jasa',
                'kecamatan' => 'Undaan',
                'hero_image' => $baseUrl . 'mjteknik_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "MJ Teknik"',
                'hero_subtitle' => 'Melayani instalasi listrik, servis pompa air, dan perbaikan berbagai peralatan rumah tangga dengan tenaga ahli berpengalaman.',
                'description' => 'MJ Teknik menyediakan layanan profesional untuk instalasi listrik, perbaikan pompa air, servis sible, serta perbaikan peralatan rumah tangga dan tukang. Dengan tenaga teknisi berpengalaman dan pelayanan cepat, MJ Teknik menjadi mitra andalan untuk kebutuhan servis harian Anda di Kudus.',
                'about' => '<strong>MJ Teknik</strong> melayani berbagai kebutuhan teknis rumah tangga, mulai dari instalasi listrik baru, perbaikan pompa air dan sible, hingga servis peralatan rumah dan alat tukang. Didukung oleh teknisi yang ahli dan berpengalaman, MJ Teknik selalu mengutamakan ketepatan, keamanan, dan kepuasan pelanggan.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Fotocopy & Jasa Travel',
                'slug' => 'fotocopy-dan-jasa-travel',
                'category' => 'Jasa',
                'kecamatan' => 'Undaan',
                'hero_image' => $baseUrl . 'fotocopy_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Fotocopy & Jasa Travel"',
                'hero_subtitle' => 'Melayani jasa fotokopi, print, scan, serta layanan travel antar kota dengan pelayanan ramah dan harga terjangkau.',
                'description' => 'Fotocopy & Jasa Travel menyediakan berbagai layanan harian seperti fotokopi dokumen, cetak berwarna, penjilidan, hingga layanan travel cepat dan aman ke berbagai kota tujuan. Dengan peralatan modern dan layanan profesional, pelanggan dapat menikmati kemudahan dalam satu tempat.',
                'about' => '<strong>Fotocopy & Jasa Travel</strong> hadir untuk memenuhi kebutuhan masyarakat akan layanan percetakan dokumen dan transportasi. Menyediakan jasa fotokopi cepat, print warna, scan dokumen, hingga layanan travel dengan armada nyaman dan jadwal fleksibel. Tempat ini cocok bagi pelajar, pekerja, dan masyarakat umum yang butuh solusi praktis dan efisien setiap hari.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Ngabus Rejo',
                'slug' => 'ngabus-rejo',
                'category' => 'Barang',
                'kecamatan' => 'Undaan',
                'hero_image' => $baseUrl . 'ngabusrejo_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Ngabus Rejo"',
                'hero_subtitle' => 'Toko bahan makanan di Kudus yang menyediakan berbagai kebutuhan harian dengan harga bersahabat.',
                'description' => 'Ngabus Rejo menawarkan berbagai bahan makanan dari sembako, sayur, hingga kebutuhan dapur lainnya. Cocok untuk belanja kebutuhan rumah tangga sehari-hari.',
                'about' => '<strong>Ngabus Rejo</strong> adalah toko bahan makanan yang berlokasi di Kudus. Menyediakan kebutuhan pokok harian, bumbu, dan produk segar dengan kualitas baik dan harga kompetitif.',
                'rating' => 3.7,
            ],
            [
                'name' => 'Nano Distro',
                'slug' => 'nano-distro',
                'category' => 'Lainnya',
                'kecamatan' => 'Undaan',
                'hero_image' => $baseUrl . 'nanodistro_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Nano Distro"',
                'hero_subtitle' => 'Toko pakaian pria di Kudus yang menyediakan fashion casual dan trendi untuk anak muda.',
                'description' => 'Nano Distro menghadirkan koleksi pakaian pria dengan desain kekinian, nyaman dipakai, dan harga bersahabat.',
                'about' => '<strong>Nano Distro</strong> merupakan toko pakaian pria yang berlokasi di Kudus. Menyediakan pakaian casual, kaos, kemeja, dan aksesoris untuk gaya modern.',
                'rating' => 4.3,
            ],
            [
                'name' => 'Ilbabalanos Store',
                'slug' => 'ilbabalanos',
                'category' => 'Lainnya',
                'kecamatan' => 'Undaan',
                'hero_image' => $baseUrl . 'ilbabalanos_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Ilbabalanos Store"',
                'hero_subtitle' => 'Toko pakaian di Kudus yang menyediakan berbagai model fashion untuk pria dan wanita.',
                'description' => 'Ilbabalanos Store menghadirkan busana stylish untuk pria dan wanita dengan harga yang kompetitif.',
                'about' => '<strong>Ilbabalanos Store</strong> adalah toko pakaian di Kudus. Menyediakan pakaian pria dan wanita dengan kualitas baik dan desain kekinian.',
                'rating' => 4.9,
            ],
        ];

        foreach ($umkms as $data) {
            $category = Category::where('name', $data['category'])->first();

            if ($category) {
                Umkm::updateOrCreate(
                    ['slug' => $data['slug']],
                    [
                        'category_id' => $category->id,
                        'kecamatan' => $data['kecamatan'],
                        'name' => $data['name'],
                        'hero_image' => $data['hero_image'],
                        'hero_title' => $data['hero_title'],
                        'hero_subtitle' => $data['hero_subtitle'],
                        'description' => $data['description'],
                        'about' => $data['about'],
                        'rating' => $data['rating'],
                        'status' => 'active',
                    ]
                );
            }
        }
    }
}
