<?php

namespace Database\Seeders;

use App\Models\Umkm;
use App\Models\Category;
use Illuminate\Database\Seeder;

class UmkmSeeder extends Seeder
{
    public function run(): void
    {
        $baseUrl = 'uploads/umkm/';

        $umkms = [
            // BAE
            [
                'name' => 'Warung Makan Om W',
                'slug' => 'warung-makan-om-w',
                'category' => 'Makanan',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'omw_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Makan Om W"',
                'hero_subtitle' => 'Warung sederhana dengan menu rumahan khas Kudus yang lezat dan terjangkau.',
                'description' => 'Warung sederhana dengan menu rumahan khas Kudus yang lezat dan terjangkau.',
                'about' => '<strong>Warung Makan Om W</strong> adalah warung makan di Desa Bacin, Kec. Bae, Kabupaten Kudus yang menyajikan aneka lauk rumahan. Cocok untuk makan sehari-hari dengan suasana santai.',
                'rating' => 4.7,
            ],
            [
                'name' => 'Ayam Geprek Jawi',
                'slug' => 'ayam-geprek-jawi',
                'category' => 'Makanan',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'geprekjawi_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Ayam Geprek Jawi"',
                'hero_subtitle' => 'Menyajikan ayam geprek pedas dengan sambal khas yang menggugah selera.',
                'description' => 'Outlet ayam geprek dengan rasa pedas khas Kudus dan harga mahasiswa.',
                'about' => '<strong>Ayam Geprek Jawi</strong> adalah outlet ayam geprek yang berlokasi di Kota Kudus, dekat kampus UMK, dengan variasi sambal pedas sebagai daya tariknya.',
                'rating' => 4.0,
            ],
            [
                'name' => 'Soto Lamongan Mbak Yuli',
                'slug' => 'soto-lamongan-mbak-yuli',
                'category' => 'Makanan',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'lamonganyuli_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Soto Lamongan Mbak Yuli"',
                'hero_subtitle' => 'Soto Lamongan gurih dengan koya melimpah dan potongan ayam kampung.',
                'description' => 'Warung soto dengan cita rasa Lamongan dan koya melimpah di Kudus.',
                'about' => '<strong>Soto Lamongan Mbak Yuli</strong> adalah warung soto yang menyajikan citarasa Lamongan di Kudus; soto ayam kuah bening dengan koya khas yang menggugah selera.',
                'rating' => 4.3,
            ],
            [
                'name' => 'Es Cincau Pasundan',
                'slug' => 'es-cincau-pasundan',
                'category' => 'Minuman',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'cincaupasundan_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Es Cincau Pasundan"',
                'hero_subtitle' => 'Minuman segar dengan cincau hitam khas Pasundan dan gula merah cair.',
                'description' => 'Minuman cincau hitam khas Pasundan dengan cita rasa segar dan manis alami dari gula merah.',
                'about' => '<strong>Es Cincau Pasundan</strong> di Bendokerep, Bae, Kudus adalah kedai minuman yang populer dengan harga terjangkau dan menu cincau alami.',
                'rating' => 4.7,
            ],
            [
                'name' => 'Jasa Tulis Kudus',
                'slug' => 'jasa-tulis-kudus',
                'category' => 'Jasa',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'jasatulis_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Jasa Tulis Kudus"',
                'hero_subtitle' => 'Melayani jasa pengetikan, cetak dokumen, dan administrasi harian.',
                'description' => 'Layanan pengetikan, cetak dokumen, dan administrasi yang buka 24 jam di Kudus.',
                'about' => '<strong>Jasa Tulis Kudus</strong> merupakan layanan pengetikan dan cetak dokumen yang berlokasi di Panjang, Bae, Kudus. Pelayanan cepat dan buka selama 24 jam membuatnya cocok untuk kebutuhan mendesak seperti tugas sekolah, administrasi, dan cetak cepat.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Resto MVR Kudus',
                'slug' => 'resto-mvr-kudus',
                'category' => 'Makanan',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'restomvr_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Resto MVR Kudus"',
                'hero_subtitle' => 'Restoran modern dengan aneka hidangan lezat dan suasana nyaman untuk berkumpul bersama keluarga dan teman.',
                'description' => 'Restoran modern yang menyajikan hidangan lezat dengan suasana nyaman untuk keluarga dan teman.',
                'about' => '<strong>Resto MVR Kudus</strong> adalah restoran modern di Kecamatan Bae yang menawarkan berbagai menu lezat, mulai dari masakan Indonesia hingga western, dengan suasana nyaman dan pelayanan ramah.',
                'rating' => 4.6,
            ],
            [
                'name' => 'VJO Cafe and Bistro',
                'slug' => 'vjo-cafe-bistro',
                'category' => 'Makanan',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'vjocafe_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "VJO Cafe and Bistro"',
                'hero_subtitle' => 'Cafe dan bistro bergaya modern yang menyajikan aneka hidangan lezat dan minuman kekinian dengan suasana nyaman.',
                'description' => 'Cafe dan bistro modern dengan menu lengkap dan suasana nyaman untuk nongkrong.',
                'about' => '<strong>VJO Cafe and Bistro</strong> adalah tempat nongkrong favorit di Bae, Kudus, dengan konsep modern, menu beragam, dan suasana yang cocok untuk keluarga maupun anak muda.',
                'rating' => 4.8,
            ],
            [
                'name' => 'Toko Al Maira',
                'slug' => 'toko-al-maira',
                'category' => 'Barang',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'tokoalmaira_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Toko Al Maira"',
                'hero_subtitle' => 'Toko bahan makanan yang menyediakan berbagai kebutuhan dapur harian dengan harga terjangkau dan kualitas terjamin.',
                'description' => 'Toko sembako lengkap dengan harga terjangkau dan kualitas terjamin.',
                'about' => '<strong>Toko Al Maira</strong> adalah toko bahan makanan di Bae yang menyediakan berbagai kebutuhan dapur sehari-hari seperti beras, minyak, gula, dan bumbu masak dengan harga bersaing.',
                'rating' => 4.5,
            ],
            [
                'name' => 'Siskanuna Boutique',
                'slug' => 'siskanuna-boutique',
                'category' => 'Lainnya',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'siskanuna_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Siskanuna Boutique"',
                'hero_subtitle' => 'Toko pakaian wanita yang menawarkan berbagai busana modern, hijab, dan aksesoris dengan desain elegan dan harga terjangkau.',
                'description' => 'Boutique pakaian wanita dengan koleksi modern dan harga terjangkau.',
                'about' => '<strong>Siskanuna Boutique</strong> menawarkan berbagai busana wanita, hijab, dan aksesoris dengan desain elegan dan kualitas premium, cocok untuk semua kalangan.',
                'rating' => 4.7,
            ],
            [
                'name' => 'Terebatik',
                'slug' => 'terebatik',
                'category' => 'Lainnya',
                'kecamatan' => 'Bae',
                'hero_image' => $baseUrl . 'terebatik_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Terebatik"',
                'hero_subtitle' => 'Toko pakaian yang menjual berbagai koleksi batik khas Kudus dengan desain modern dan kualitas terbaik.',
                'description' => 'Koleksi batik khas Kudus dengan desain modern dan kualitas premium.',
                'about' => '<strong>Terebatik</strong> adalah toko batik di Bae yang menawarkan berbagai koleksi batik tulis dan cap dengan motif khas Kudus dan desain kekinian.',
                'rating' => 4.9,
            ],

            // DAWE
            [
                'name' => 'Swike Dawe Restaurant',
                'slug' => 'swike-dawe-restaurant',
                'category' => 'Makanan',
                'kecamatan' => 'Dawe',
                'hero_image' => $baseUrl . 'swikedawe_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Swike Dawe Restaurant"',
                'hero_subtitle' => 'Restoran khas Kudus yang menyajikan swike lezat dengan resep tradisional.',
                'description' => 'Restoran legendaris dengan menu swike (kodok kuah tauco) khas Kudus.',
                'about' => '<strong>Swike Dawe Restaurant</strong> adalah salah satu tempat kuliner khas Kudus yang terkenal dengan menu swike — kodok kuah tauco — dan telah menjadi destinasi lokal sejak lama.',
                'rating' => 4.3,
            ],
            [
                'name' => 'WEKATE GANK',
                'slug' => 'wekate-gank',
                'category' => 'Minuman',
                'kecamatan' => 'Dawe',
                'hero_image' => $baseUrl . 'wekategank_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "WEKATE GANK"',
                'hero_subtitle' => 'Kedai minuman kekinian dengan berbagai pilihan topping dan rasa.',
                'description' => 'Kedai minuman modern dengan berbagai topping dan rasa unik.',
                'about' => '<strong>WEKATE GANK</strong> adalah kedai minuman kekinian di Dawe yang menyajikan minuman dengan berbagai topping dan rasa yang bisa disesuaikan selera.',
                'rating' => 4.6,
            ],
            [
                'name' => 'Rumah Makan Mak Kiyem',
                'slug' => 'rumah-makan-mak-kiyem',
                'category' => 'Makanan',
                'kecamatan' => 'Dawe',
                'hero_image' => $baseUrl . 'makkiyem_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Rumah Makan Mak Kiyem"',
                'hero_subtitle' => 'Tempat makan dengan cita rasa masakan Jawa rumahan yang otentik.',
                'description' => 'Warung makan khas Kudus dengan menu rumahan dan lodeh khas.',
                'about' => '<strong>Rumah Makan Mak Kiyem</strong> adalah warung makan populer di Desa Cendono, Kec. Dawe, Kudus yang menyediakan menu makan malam hingga pagi, dengan suasana santai dan rasa masakan rumahan yang khas.',
                'rating' => 4.2,
            ],
            [
                'name' => 'Jasa Angkut & Pasir & Bata Merah Jumbo',
                'slug' => 'jasa-angkut-dan-pasir-bata-merah-jumbo',
                'category' => 'Jasa',
                'kecamatan' => 'Dawe',
                'hero_image' => $baseUrl . 'jasaangkut_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Jasa Angkut & Pasir & Bata Merah Jumbo"',
                'hero_subtitle' => 'Menyediakan layanan angkut material bangunan dan kebutuhan konstruksi.',
                'description' => 'Layanan angkut pasir, bata merah jumbo, dan material bangunan lainnya.',
                'about' => '<strong>Jasa Angkut & Pasir & Bata Merah Jumbo</strong> merupakan penyedia layanan pengiriman bahan bangunan dan material konstruksi di wilayah Kudus dan sekitarnya. Layanan meliputi pengantaran pasir, bata merah jumbo, serta jasa angkut berbagai kebutuhan proyek secara efisien dan profesional.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Ayam Geprek Sa’i Dawe',
                'slug' => 'ayam-geprek-sai',
                'category' => 'Makanan',
                'kecamatan' => 'Dawe',
                'hero_image' => $baseUrl . 'ayamgepreksai_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Ayam Geprek Sa’i Dawe"',
                'hero_subtitle' => 'Ayam geprek dengan level pedas sesuai selera dan harga bersahabat.',
                'description' => 'Ayam geprek renyah dengan sambal pedas yang bisa dipilih tingkat kepedasannya.',
                'about' => '<strong>Ayam Geprek Sa’i Dawe</strong> menyajikan ayam geprek dengan sambal pedas menggoda dan bumbu khas rumahan yang gurih, cocok untuk semua kalangan.',
                'rating' => 4.3,
            ],
            [
                'name' => 'Warung Makan Sendang Mulia',
                'slug' => 'warung-makan-sendang-mulia',
                'category' => 'Makanan',
                'kecamatan' => 'Dawe',
                'hero_image' => $baseUrl . 'sendangmulia_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Makan Sendang Mulia"',
                'hero_subtitle' => 'Rumah makan yang menyajikan aneka hidangan rumahan lezat dengan cita rasa khas dan suasana nyaman.',
                'description' => 'Rumah makan dengan menu rumahan lengkap dan suasana nyaman.',
                'about' => '<strong>Warung Makan Sendang Mulia</strong> adalah rumah makan di Dawe yang menyajikan aneka hidangan rumahan dengan cita rasa khas dan suasana yang nyaman untuk makan bersama keluarga.',
                'rating' => 4.5,
            ],
            [
                'name' => 'Toko ADIB AZKA',
                'slug' => 'toko-adib-azka',
                'category' => 'Barang',
                'kecamatan' => 'Dawe',
                'hero_image' => $baseUrl . 'tokoadibazka_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Toko ADIB AZKA"',
                'hero_subtitle' => 'Toko perlengkapan rumah tangga yang menyediakan berbagai kebutuhan harian dengan harga terjangkau.',
                'description' => 'Toko perlengkapan rumah tangga lengkap dengan harga terjangkau.',
                'about' => '<strong>Toko ADIB AZKA</strong> menyediakan berbagai kebutuhan rumah tangga seperti peralatan dapur, alat kebersihan, dan barang harian lainnya dengan harga bersaing.',
                'rating' => 4.4,
            ],
            [
                'name' => 'Toko Sri Dawe',
                'slug' => 'toko-sri-dawe',
                'category' => 'Barang',
                'kecamatan' => 'Dawe',
                'hero_image' => $baseUrl . 'tokosridawe_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Toko Sri Dawe"',
                'hero_subtitle' => 'Toko bahan makanan yang menyediakan berbagai kebutuhan dapur, bumbu, dan sembako lengkap dengan harga bersahabat.',
                'description' => 'Toko sembako lengkap dengan harga bersahabat dan kualitas terjamin.',
                'about' => '<strong>Toko Sri Dawe</strong> adalah toko bahan makanan di Dawe yang menyediakan berbagai kebutuhan dapur, bumbu, dan sembako lengkap dengan harga terjangkau.',
                'rating' => 4.6,
            ],
            [
                'name' => 'Arfan Outfit Kudus',
                'slug' => 'arfan-outfit-kudus',
                'category' => 'Lainnya',
                'kecamatan' => 'Dawe',
                'hero_image' => $baseUrl . 'arfanoutfitkudus_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Arfan Outfit Kudus"',
                'hero_subtitle' => 'Toko pakaian yang menyediakan berbagai busana trendi dan nyaman untuk segala usia.',
                'description' => 'Toko pakaian trendi dengan koleksi untuk pria, wanita, dan anak.',
                'about' => '<strong>Arfan Outfit Kudus</strong> menawarkan berbagai busana trendi dan nyaman untuk segala usia, mulai dari pakaian kasual hingga formal.',
                'rating' => 4.7,
            ],
            [
                'name' => 'Dinda Store DS',
                'slug' => 'dinda-store-ds',
                'category' => 'Lainnya',
                'kecamatan' => 'Dawe',
                'hero_image' => $baseUrl . 'dindastore_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Dinda Store DS"',
                'hero_subtitle' => 'Toko pakaian yang menyediakan berbagai busana trendi, modern, dan nyaman untuk segala usia.',
                'description' => 'Toko pakaian modern dengan koleksi lengkap dan harga terjangkau.',
                'about' => '<strong>Dinda Store DS</strong> adalah toko pakaian di Dawe yang menyediakan berbagai busana trendi, modern, dan nyaman untuk semua kalangan.',
                'rating' => 4.5,
            ],

            // GEBOG
            [
                'name' => 'Warung Makan Mbah Sapar',
                'slug' => 'warung-makan-mbah-sapar',
                'category' => 'Makanan',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'mbahsapar_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Makan Mbah Sapar"',
                'hero_subtitle' => 'Warung makan legendaris dengan menu khas Kudus yang menggugah selera.',
                'description' => 'Warung makan khas Kudus dengan sop daging kerbau dan jamu tradisional.',
                'about' => '<strong>Warung Makan Mbah Sapar</strong> adalah warung makan di Desa Gondosari, Kec. Gebog, Kabupaten Kudus yang dikenal sebagai tempat sarapan favorit.',
                'rating' => 4.5,
            ],
            [
                'name' => 'Nasi Uduk dan Nasi Kuning Gang Satu',
                'slug' => 'nasi-uduk-dan-nasi-kuning-gang-satu',
                'category' => 'Makanan',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'nasiuduk_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Nasi Uduk dan Nasi Kuning Gang Satu"',
                'hero_subtitle' => 'Menyajikan nasi uduk dan nasi kuning dengan lauk variatif setiap hari.',
                'description' => 'Warung sarapan dengan nasi uduk dan nasi kuning lauk lengkap.',
                'about' => '<strong>Nasi Uduk dan Nasi Kuning Gang Satu</strong> adalah warung sarapan populer di Gebog, Kudus yang buka sejak pagi dengan cita rasa gurih dan lauk beragam.',
                'rating' => 4.9,
            ],
            [
                'name' => 'Sari Rasa Bakso Malvinas',
                'slug' => 'sari-rasa-bakso-malvinas',
                'category' => 'Makanan',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'baksomalvinas_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Sari Rasa Bakso Malvinas"',
                'hero_subtitle' => 'Bakso urat dengan kuah kaldu gurih dan porsi mengenyangkan.',
                'description' => 'Bakso dengan kuah gurih dan daging sapi pilihan.',
                'about' => '<strong>Sari Rasa Bakso Malvinas</strong> merupakan kedai bakso favorit warga Kudus yang dikenal dengan kuah kaldunya yang gurih dan porsi besar.',
                'rating' => 4.5,
            ],
            [
                'name' => 'Warung Makan Mak Ru',
                'slug' => 'warung-makan-mak-ru',
                'category' => 'Makanan',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'warungmakanmakru_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Makan Mak Ru"',
                'hero_subtitle' => 'Menu masakan rumahan lengkap dengan sambal khas Kudus.',
                'description' => 'Nikmati berbagai pilihan masakan rumahan khas Kudus.',
                'about' => '<strong>Warung Makan Mak Ru</strong> dikenal dengan hidangan rumahan lezat seperti sayur lodeh, tempe goreng, ayam opor, dan sambal khas Kudus.',
                'rating' => 4.4,
            ],
            [
                'name' => 'Kasehito Works',
                'slug' => 'kasehito-works',
                'category' => 'Jasa',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'kasehitoworks_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Kasehito Works"',
                'hero_subtitle' => 'Menyediakan jasa desain, sablon, dan percetakan lokal berkualitas.',
                'description' => 'Layanan desain, sablon, dan percetakan berkualitas tinggi.',
                'about' => '<strong>Kasehito Works</strong> merupakan penyedia jasa pengeditan video, desain grafis, sablon, dan percetakan yang berfokus pada hasil berkualitas dan visual storytelling yang kuat.',
                'rating' => 4.3,
            ],
            [
                'name' => 'Basina Food',
                'slug' => 'basina-food',
                'category' => 'Makanan',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'basina_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Basina Food"',
                'hero_subtitle' => 'Rumah makan yang menyajikan aneka hidangan lezat khas rumahan.',
                'description' => 'Rumah makan dengan menu rumahan lezat dan porsi melimpah.',
                'about' => '<strong>Basina Food</strong> adalah rumah makan di Gebog yang menyajikan aneka hidangan khas rumahan dengan cita rasa autentik dan suasana nyaman.',
                'rating' => 4.6,
            ],
            [
                'name' => 'Campaign Coffee',
                'slug' => 'campaign-coffee',
                'category' => 'Minuman',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'campaigncoffee_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Campaign Coffee"',
                'hero_subtitle' => 'Kedai kopi modern dengan cita rasa autentik dan suasana nyaman.',
                'description' => 'Kedai kopi dengan suasana nyaman dan kopi autentik.',
                'about' => '<strong>Campaign Coffee</strong> adalah kedai kopi modern di Gebog yang menyajikan kopi dengan cita rasa autentik dan suasana nyaman untuk nongkrong.',
                'rating' => 4.8,
            ],
            [
                'name' => 'Toko TNA JAYA',
                'slug' => 'toko-tna-jaya',
                'category' => 'Barang',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'tokotnajaya_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Toko TNA JAYA"',
                'hero_subtitle' => 'Toko bahan makanan lengkap dengan harga terjangkau dan kualitas terjamin.',
                'description' => 'Toko sembako lengkap dengan harga terjangkau.',
                'about' => '<strong>Toko TNA JAYA</strong> menyediakan berbagai bahan makanan harian dengan harga terjangkau dan kualitas terjamin.',
                'rating' => 4.5,
            ],
            [
                'name' => 'Toko Teguh Sudarsono',
                'slug' => 'toko-teguh-sudarsono',
                'category' => 'Barang',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'tokoteguhsudarsono_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Toko Teguh Sudarsono"',
                'hero_subtitle' => 'Toko bahan makanan harian yang menyediakan kebutuhan dapur lengkap dan berkualitas.',
                'description' => 'Toko bahan makanan dengan kebutuhan dapur lengkap.',
                'about' => '<strong>Toko Teguh Sudarsono</strong> adalah toko bahan makanan di Gebog yang menyediakan kebutuhan dapur lengkap dan berkualitas dengan harga bersaing.',
                'rating' => 4.4,
            ],
            [
                'name' => 'Nilna Dion Collection',
                'slug' => 'nilna-dion-collection',
                'category' => 'Lainnya',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'nilnadioncollection_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Nilna Dion Collection"',
                'hero_subtitle' => 'Toko pakaian modern yang menyediakan berbagai busana stylish dan nyaman untuk semua kalangan.',
                'description' => 'Toko pakaian modern dengan koleksi stylish dan nyaman.',
                'about' => '<strong>Nilna Dion Collection</strong> menawarkan berbagai busana stylish dan nyaman untuk pria, wanita, dan anak dengan harga terjangkau.',
                'rating' => 4.7,
            ],
            [
                'name' => 'Toko Kastimah',
                'slug' => 'toko-kastimah',
                'category' => 'Barang',
                'kecamatan' => 'Gebog',
                'hero_image' => $baseUrl . 'tokokastimah_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Toko Kastimah"',
                'hero_subtitle' => 'Toko bahan makanan harian yang menyediakan kebutuhan dapur lengkap dengan harga terjangkau.',
                'description' => 'Toko sembako dengan kebutuhan dapur lengkap dan harga terjangkau.',
                'about' => '<strong>Toko Kastimah</strong> menyediakan berbagai kebutuhan dapur harian seperti beras, minyak, gula, dan bumbu masak dengan harga terjangkau.',
                'rating' => 4.5,
            ],

            // JATI
            [
                'name' => 'Cakrawala Sego Sambel',
                'slug' => 'cakrawala-sego-sambel',
                'category' => 'Makanan',
                'kecamatan' => 'Jati',
                'hero_image' => $baseUrl . 'cakrawala_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Cakrawala Sego Sambel"',
                'hero_subtitle' => 'Sego sambel khas dengan berbagai lauk pedas yang menggoda selera.',
                'description' => 'Warung makan malam dengan sego sambel dan lauk goreng khas.',
                'about' => '<strong>Cakrawala Sego Sambel</strong> adalah rumah makan di Jl. Jend. Ahmad Yani No.1, Getas Pejaten, Kudus yang terkenal dengan sego sambel dan lauk gorengnya.',
                'rating' => 4.4,
            ],
            [
                'name' => 'Nasi Opor Sunggingan',
                'slug' => 'nasi-opor-sunggingan',
                'category' => 'Makanan',
                'kecamatan' => 'Jati',
                'hero_image' => $baseUrl . 'oporsungginan_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Nasi Opor Sunggingan"',
                'hero_subtitle' => 'Opor ayam lembut dengan kuah santan kental dan bumbu khas Kudus.',
                'description' => 'Nasi opor ayam dengan kuah santan gurih dan bumbu rempah.',
                'about' => '<strong>Nasi Opor Sunggingan</strong> merupakan salah satu kuliner khas Kudus yang terkenal dengan opor ayamnya yang gurih dan lembut.',
                'rating' => 4.5,
            ],
            [
                'name' => 'Warung Enthog Pak Badi',
                'slug' => 'warung-enthog-pak-badi',
                'category' => 'Makanan',
                'kecamatan' => 'Jati',
                'hero_image' => $baseUrl . 'enthogpakbadi_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Enthog Pak Badi"',
                'hero_subtitle' => 'Spesialis olahan enthog dengan sambal korek pedas menggugah selera.',
                'description' => 'Nikmati kelezatan daging enthog dengan bumbu rempah khas.',
                'about' => '<strong>Warung Enthog Pak Badi</strong> merupakan kuliner legendaris di Kudus yang terkenal dengan olahan enthog berbumbu rempah kuat.',
                'rating' => 4.6,
            ],
            [
                'name' => 'Jasa Powder Coating & Platting Kudus',
                'slug' => 'jasa-powder-coating-dan-platting-kudus',
                'category' => 'Jasa',
                'kecamatan' => 'Jati',
                'hero_image' => $baseUrl . 'powdercoating_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Jasa Powder Coating & Platting Kudus"',
                'hero_subtitle' => 'Melayani coating dan platting untuk berbagai kebutuhan industri dan otomotif.',
                'description' => 'Spesialis powder coating & chrome plating dengan hasil rapi.',
                'about' => '<strong>Jasa Powder Coating & Platting Kudus</strong> adalah solusi lengkap untuk kebutuhan finishing logam berkualitas premium di Kudus dan sekitarnya.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Kedai Es Bang Maman',
                'slug' => 'kedai-es-bang-maman',
                'category' => 'Minuman',
                'kecamatan' => 'Jati',
                'hero_image' => $baseUrl . 'esbangmaman_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Kedai Es Bang Maman"',
                'hero_subtitle' => 'Es segar berbagai rasa dengan topping buah dan jelly favorit anak muda.',
                'description' => 'Kedai es dengan berbagai pilihan minuman segar dan topping.',
                'about' => '<strong>Kedai Es Bang Maman</strong> merupakan tempat favorit warga Kudus untuk menikmati minuman dingin segar di siang hari dengan berbagai topping.',
                'rating' => 4.9,
            ],
            [
                'name' => 'Gravitasi Teras Muria',
                'slug' => 'gravitasi-teras-muria',
                'category' => 'Makanan',
                'kecamatan' => 'Jati',
                'hero_image' => $baseUrl . 'gravitasiterasmuria_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Gravitasi Teras Muria"',
                'hero_subtitle' => 'Restoran dengan pemandangan indah di lereng Muria yang menyajikan aneka hidangan lezat dan suasana nyaman.',
                'description' => 'Restoran dengan view Muria dan hidangan lezat.',
                'about' => '<strong>Gravitasi Teras Muria</strong> adalah restoran di lereng Gunung Muria yang menawarkan pemandangan indah dan aneka hidangan lezat dengan suasana nyaman.',
                'rating' => 4.8,
            ],
            [
                'name' => 'Toko Kliwon',
                'slug' => 'toko-kliwon',
                'category' => 'Barang',
                'kecamatan' => 'Jati',
                'hero_image' => $baseUrl . 'tokokliwon_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Toko Kliwon"',
                'hero_subtitle' => 'Toko perlengkapan rumah tangga yang menyediakan berbagai kebutuhan dapur dan alat harian dengan harga terjangkau.',
                'description' => 'Toko perlengkapan rumah tangga dengan harga terjangkau.',
                'about' => '<strong>Toko Kliwon</strong> menyediakan berbagai kebutuhan dapur dan alat harian dengan harga terjangkau dan kualitas baik.',
                'rating' => 4.5,
            ],
            [
                'name' => 'Toko Happy Kids',
                'slug' => 'toko-happy-kids',
                'category' => 'Lainnya',
                'kecamatan' => 'Jati',
                'hero_image' => $baseUrl . 'tokohappykids_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Toko Happy Kids"',
                'hero_subtitle' => 'Toko pakaian anak yang menyediakan berbagai busana lucu, nyaman, dan berkualitas untuk si kecil.',
                'description' => 'Toko pakaian anak dengan koleksi lucu dan nyaman.',
                'about' => '<strong>Toko Happy Kids</strong> menyediakan berbagai busana anak yang lucu, nyaman, dan berkualitas untuk si kecil.',
                'rating' => 4.7,
            ],
            [
                'name' => 'Nobby Kudus Extension Mall',
                'slug' => 'nobby-kudus-extension',
                'category' => 'Lainnya',
                'kecamatan' => 'Jati',
                'hero_image' => $baseUrl . 'nobbykudusextension_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Nobby Kudus Extension Mall"',
                'hero_subtitle' => 'Toko pakaian modern yang menawarkan berbagai koleksi busana trendi untuk pria dan wanita dengan gaya kekinian.',
                'description' => 'Toko pakaian modern dengan gaya kekinian.',
                'about' => '<strong>Nobby Kudus Extension Mall</strong> menawarkan berbagai koleksi busana trendi untuk pria dan wanita dengan gaya kekinian dan harga terjangkau.',
                'rating' => 4.6,
            ],

            // JEKULO
            [
                'name' => 'Jus Pojokan',
                'slug' => 'jus-pojokan',
                'category' => 'Minuman',
                'kecamatan' => 'Jekulo',
                'hero_image' => $baseUrl . 'juspojokan_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Jus Pojokan"',
                'hero_subtitle' => 'Jus segar berbagai rasa yang cocok dinikmati saat siang hari.',
                'description' => 'Jus buah segar dengan berbagai rasa alami.',
                'about' => '<strong>Jus Pojokan</strong> merupakan kedai minuman di Jekulo yang menyajikan aneka jus buah segar dengan rasa alami dan harga terjangkau.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Kedai Twins Seblak Bandung n Juice Jekulo',
                'slug' => 'kedai-twins-seblak-bandung-juice-jekulo',
                'category' => 'Minuman',
                'kecamatan' => 'Jekulo',
                'hero_image' => $baseUrl . 'kedaytwins_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Kedai Twins Seblak Bandung n Juice Jekulo"',
                'hero_subtitle' => 'Kedai seblak dan jus kekinian khas Bandung dengan cita rasa lokal.',
                'description' => 'Kedai seblak dan jus dengan cita rasa khas Bandung.',
                'about' => '<strong>Kedai Twins</strong> menghadirkan menu spesial Seblak Bandung dengan cita rasa pedas nikmat serta pilihan jus buah segar di Jekulo.',
                'rating' => 4.1,
            ],
            [
                'name' => 'Lentog Tanjung Bang Saiful',
                'slug' => 'lentog-tanjung-bang-saiful',
                'category' => 'Makanan',
                'kecamatan' => 'Jekulo',
                'hero_image' => $baseUrl . 'lentogbangsyaiful_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Lentog Tanjung Bang Saiful"',
                'hero_subtitle' => 'Lentog khas Kudus dengan cita rasa gurih yang legendaris.',
                'description' => 'Lentog dengan sayur lodeh dan sambal khas Kudus.',
                'about' => '<strong>Lentog Tanjung Bang Saiful</strong> merupakan salah satu kuliner khas Kudus yang terkenal dengan kelezatan lentognya yang gurih dan autentik.',
                'rating' => 4.6,
            ],
            [
                'name' => 'Berkah Es Buah',
                'slug' => 'berkah-es-buah',
                'category' => 'Minuman',
                'kecamatan' => 'Jekulo',
                'hero_image' => $baseUrl . 'berkahesbuah_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Berkah Es Buah"',
                'hero_subtitle' => 'Es buah segar dengan campuran jelly dan susu, favorit semua kalangan.',
                'description' => 'Es buah segar dengan sirup dan susu kental manis.',
                'about' => '<strong>Berkah Es Buah</strong> adalah tempat favorit untuk menikmati es buah segar di Jekulo dengan campuran buah tropis dan susu.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Warnet Jaya Sentosa',
                'slug' => 'warnet-jaya-sentosa',
                'category' => 'Jasa',
                'kecamatan' => 'Jekulo',
                'hero_image' => $baseUrl . 'warnetjayasentosa_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warnet Jaya Sentosa"',
                'hero_subtitle' => 'Warnet dengan koneksi cepat dan nyaman untuk bermain maupun bekerja.',
                'description' => 'Warnet dengan PC gaming dan koneksi internet cepat.',
                'about' => '<strong>Warnet Jaya Sentosa</strong> adalah pilihan utama bagi gamer dan pelajar di Jekulo dengan fasilitas lengkap dan suasana nyaman.',
                'rating' => 4.8,
            ],
            [
                'name' => 'Warung Mie Dadat Pak Karnan',
                'slug' => 'warung-mie-dadat',
                'category' => 'Makanan',
                'kecamatan' => 'Jekulo',
                'hero_image' => $baseUrl . 'warungmiedadat_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Mie Dadat Pak Karnan"',
                'hero_subtitle' => 'Warung mie legendaris yang menyajikan aneka mie rebus dan goreng dengan cita rasa khas dan porsi mengenyangkan.',
                'description' => 'Warung mie legendaris dengan cita rasa khas dan porsi besar.',
                'about' => '<strong>Warung Mie Dadat Pak Karnan</strong> adalah warung mie legendaris di Jekulo yang menyajikan aneka mie rebus dan goreng dengan cita rasa khas.',
                'rating' => 4.7,
            ],
            [
                'name' => 'Toko Risfan Snack - Pusat Grosir Snack Lengkap di Kudus',
                'slug' => 'toko-risfan-snack',
                'category' => 'Barang',
                'kecamatan' => 'Jekulo',
                'hero_image' => $baseUrl . 'tokorisfan_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Toko Risfan Snack"',
                'hero_subtitle' => 'Toko bahan makanan dan grosir snack lengkap yang menyediakan berbagai camilan, makanan ringan, dan kebutuhan dapur dengan harga terjangkau.',
                'description' => 'Pusat grosir snack lengkap dengan harga terjangkau.',
                'about' => '<strong>Toko Risfan Snack</strong> adalah pusat grosir snack di Jekulo yang menyediakan berbagai camilan, makanan ringan, dan kebutuhan dapur dengan harga terjangkau.',
                'rating' => 4.6,
            ],
            [
                'name' => 'Js Muslim Collection Kudus',
                'slug' => 'js-muslim-collection',
                'category' => 'Lainnya',
                'kecamatan' => 'Jekulo',
                'hero_image' => $baseUrl . 'jsmuslim_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Js Muslim Collection Kudus"',
                'hero_subtitle' => 'Toko pakaian muslim yang menyediakan berbagai busana syar’i, gamis, dan hijab modern dengan desain elegan dan harga bersahabat.',
                'description' => 'Toko pakaian muslim dengan koleksi syar’i dan modern.',
                'about' => '<strong>Js Muslim Collection Kudus</strong> menyediakan berbagai busana syar’i, gamis, dan hijab modern dengan desain elegan dan harga bersahabat.',
                'rating' => 4.8,
            ],
            [
                'name' => 'Kios Hjh Zaroah',
                'slug' => 'kios-hjh',
                'category' => 'Lainnya',
                'kecamatan' => 'Jekulo',
                'hero_image' => $baseUrl . 'kioshjh_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Kios Hjh Zaroah"',
                'hero_subtitle' => 'Toko pakaian yang menyediakan berbagai busana muslim, mukena, dan perlengkapan ibadah dengan kualitas bagus dan harga terjangkau.',
                'description' => 'Toko perlengkapan ibadah dan pakaian muslim.',
                'about' => '<strong>Kios Hjh Zaroah</strong> menyediakan berbagai busana muslim, mukena, dan perlengkapan ibadah dengan kualitas bagus dan harga terjangkau.',
                'rating' => 4.5,
            ],

            // KALIWUNGU
            [
                'name' => 'Jahe Rempah Leggit',
                'slug' => 'jahe-rempah-leggit',
                'category' => 'Minuman',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'jaherempahreggit_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Jahe Rempah Leggit"',
                'hero_subtitle' => 'Minuman jahe hangat dengan campuran rempah alami khas Kudus.',
                'description' => 'Minuman jahe hangat dengan rempah alami dan madu.',
                'about' => '<strong>Jahe Rempah Leggit</strong> menghadirkan minuman tradisional berbasis jahe dan rempah pilihan yang hangat dan menyehatkan.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Warung Makan Bu Carik',
                'slug' => 'warung-makan-bu-carik',
                'category' => 'Makanan',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'warungmakanbucarik_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Makan Bu Carik"',
                'hero_subtitle' => 'Warung makan sederhana dengan menu rumahan yang lezat dan murah.',
                'description' => 'Warung makan dengan menu rumahan lezat dan harga murah.',
                'about' => '<strong>Warung Makan Bu Carik</strong> menyajikan berbagai masakan tradisional khas Kudus, mulai dari lontong sayur, nasi pecel, hingga lauk pauk rumah.',
                'rating' => 4.1,
            ],
            [
                'name' => 'Tehatea Indonesia',
                'slug' => 'tehatea-indonesia',
                'category' => 'Minuman',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'tehatea_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Tehatea Indonesia"',
                'hero_subtitle' => 'Gerai teh kekinian dengan berbagai varian rasa dan topping menarik.',
                'description' => 'Minuman teh premium dengan varian hangat & dingin.',
                'about' => '<strong>Tehatea Indonesia</strong> adalah gerai minuman teh kekinian yang menggabungkan tradisi rasa Indonesia dengan sentuhan modern.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Warung Makan 2 Putra',
                'slug' => 'warung-makan-2-putra',
                'category' => 'Makanan',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'warungmakan2putra_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Makan 2 Putra"',
                'hero_subtitle' => 'Tempat makan dengan menu ayam goreng dan sambal khas.',
                'description' => 'Warung makan dengan ayam goreng dan sambal khas.',
                'about' => '<strong>Warung Makan 2 Putra</strong> menyajikan berbagai masakan khas Kudus dengan resep rumahan, terutama ayam goreng dan sambal khas.',
                'rating' => 4.6,
            ],
            [
                'name' => 'Jasa Angkut Barang',
                'slug' => 'jasa-angkut-barang',
                'category' => 'Jasa',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'jasaangkutbarang_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Jasa Angkut Barang"',
                'hero_subtitle' => 'Layanan angkut cepat dan aman untuk kebutuhan pindahan dan kiriman.',
                'description' => 'Layanan angkut barang dengan tenaga profesional dan kendaraan lengkap.',
                'about' => '<strong>Jasa Angkut Barang</strong> menyediakan layanan angkut barang dengan tenaga profesional, kendaraan sesuai kebutuhan, dan harga transparan.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Sego Sambel Lek Kas 2',
                'slug' => 'sego-sambel-lek-kas2',
                'category' => 'Makanan',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'segosambel_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Sego Sambel Lek Kas 2"',
                'hero_subtitle' => 'Rumah makan yang menyajikan sego sambel pedas nikmat dengan lauk beragam dan cita rasa khas rumahan.',
                'description' => 'Sego sambel pedas dengan lauk beragam dan cita rasa khas.',
                'about' => '<strong>Sego Sambel Lek Kas 2</strong> adalah rumah makan di Kaliwungu yang menyajikan sego sambel pedas nikmat dengan lauk beragam dan cita rasa khas rumahan.',
                'rating' => 4.7,
            ],
            [
                'name' => 'Toko Jamaah',
                'slug' => 'toko-jamaah',
                'category' => 'Barang',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'tokojamaah_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Toko Jamaah"',
                'hero_subtitle' => 'Toko bahan makanan yang menyediakan berbagai kebutuhan dapur dan sembako dengan harga terjangkau.',
                'description' => 'Toko sembako dengan kebutuhan dapur lengkap dan harga terjangkau.',
                'about' => '<strong>Toko Jamaah</strong> menyediakan berbagai kebutuhan dapur dan sembako dengan harga terjangkau dan kualitas terjamin.',
                'rating' => 4.5,
            ],
            [
                'name' => 'MM Amanah',
                'slug' => 'mm-amanah',
                'category' => 'Barang',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'mmamanah_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "MM Amanah"',
                'hero_subtitle' => 'Minimarket yang menyediakan berbagai kebutuhan harian, mulai dari sembako hingga produk rumah tangga dengan harga bersahabat.',
                'description' => 'Minimarket lengkap dengan kebutuhan harian dan harga bersahabat.',
                'about' => '<strong>MM Amanah</strong> adalah minimarket di Kaliwungu yang menyediakan berbagai kebutuhan harian, mulai dari sembako hingga produk rumah tangga dengan harga bersahabat.',
                'rating' => 4.6,
            ],
            [
                'name' => 'Toko Van Helen Serba 35000',
                'slug' => 'toko-van-helen',
                'category' => 'Lainnya',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'tokovanhelen_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Toko Van Helen Serba 35000"',
                'hero_subtitle' => 'Toko pakaian yang menawarkan berbagai busana trendi dan aksesori dengan harga terjangkau, hanya Rp35.000-an.',
                'description' => 'Toko pakaian serba Rp35.000 dengan koleksi trendi.',
                'about' => '<strong>Toko Van Helen Serba 35000</strong> menawarkan berbagai busana trendi dan aksesori dengan harga terjangkau, hanya Rp35.000-an.',
                'rating' => 4.7,
            ],
            [
                'name' => 'Lina Family',
                'slug' => 'lina-family',
                'category' => 'Lainnya',
                'kecamatan' => 'Kaliwungu',
                'hero_image' => $baseUrl . 'linafamily_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Lina Family"',
                'hero_subtitle' => 'Toko pakaian yang menyediakan berbagai busana keluarga dengan model modern dan harga bersahabat.',
                'description' => 'Toko pakaian keluarga dengan model modern dan harga bersahabat.',
                'about' => '<strong>Lina Family</strong> menyediakan berbagai busana keluarga dengan model modern dan harga bersahabat, cocok untuk semua anggota keluarga.',
                'rating' => 4.5,
            ],

            // KOTA KUDUS
            [
                'name' => 'Susu Moeria',
                'slug' => 'susu-moeria',
                'category' => 'Minuman',
                'kecamatan' => 'Kudus Kota',
                'hero_image' => $baseUrl . 'susumoeria_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Susu Moeria"',
                'hero_subtitle' => 'Susu murni dengan berbagai varian rasa khas Kudus.',
                'description' => 'Susu murni segar dengan berbagai varian rasa khas.',
                'about' => '<strong>Susu Moeria</strong> merupakan produsen sekaligus penjual susu murni segar yang berlokasi di Kudus dengan berbagai varian rasa.',
                'rating' => 4.4,
            ],
            [
                'name' => 'Ramboo Chicken',
                'slug' => 'ramboo-chicken',
                'category' => 'Makanan',
                'kecamatan' => 'Kudus Kota',
                'hero_image' => $baseUrl . 'ramboo_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Ramboo Chicken"',
                'hero_subtitle' => 'Ayam geprek dengan sambal korek yang pedas dan menggugah selera.',
                'description' => 'Ayam geprek dengan sambal korek pedas khas Kudus.',
                'about' => '<strong>Ramboo Chicken</strong> adalah usaha kuliner populer di Krandon, Kudus yang terkenal dengan ayam geprek dan sambal koreknya.',
                'rating' => 4.5,
            ],
            [
                'name' => 'Es Gempol Pak Masykur',
                'slug' => 'es-gempol-pak-masykur',
                'category' => 'Minuman',
                'kecamatan' => 'Kudus Kota',
                'hero_image' => $baseUrl . 'gempol_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Es Gempol Pak Masykur"',
                'hero_subtitle' => 'Minuman tradisional Kudus dengan gempol segar dan santan manis.',
                'description' => 'Es gempol dengan santan gurih dan gula merah manis.',
                'about' => '<strong>Es Gempol Pak Masykur</strong> merupakan minuman tradisional khas Kudus yang telah melegenda dengan cita rasa klasik.',
                'rating' => 4.7,
            ],
            [
                'name' => 'Sultan Barber Top',
                'slug' => 'sultan-barber-top',
                'category' => 'Jasa',
                'kecamatan' => 'Kudus Kota',
                'hero_image' => $baseUrl . 'sultanbarbertop_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Sultan Barber Top"',
                'hero_subtitle' => 'Barbershop modern dengan pelayanan profesional, tempat nyaman, dan hasil cukur rapi bergaya kekinian.',
                'description' => 'Barbershop modern dengan layanan premium dan hasil rapi.',
                'about' => '<strong>Sultan Barber Top</strong> adalah barbershop profesional yang mengutamakan kualitas layanan dan kenyamanan pelanggan di Kota Kudus.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Soto Kudus Bu Jatmi',
                'slug' => 'soto-kudus-bu-jatmi',
                'category' => 'Makanan',
                'kecamatan' => 'Kudus Kota',
                'hero_image' => $baseUrl . 'sotokudusbujatmi_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Soto Kudus Bu Jatmi"',
                'hero_subtitle' => 'Warung legendaris dengan cita rasa soto khas Kudus yang gurih dan autentik sejak puluhan tahun.',
                'description' => 'Soto khas Kudus legendaris dengan cita rasa autentik.',
                'about' => '<strong>Soto Kudus Bu Jatmi</strong> adalah warung makan yang telah lama dikenal masyarakat Kudus karena kelezatan soto khasnya yang gurih dan autentik.',
                'rating' => 4.5,
            ],
            [
                'name' => 'Treend Steak Kudus',
                'slug' => 'treend-steak-kudus',
                'category' => 'Makanan',
                'kecamatan' => 'Kudus Kota',
                'hero_image' => $baseUrl . 'treendsteak_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Treend Steak Kudus"',
                'hero_subtitle' => 'Restoran steak modern yang menyajikan aneka daging premium dengan cita rasa lezat dan harga bersahabat.',
                'description' => 'Restoran steak dengan daging premium dan harga bersahabat.',
                'about' => '<strong>Treend Steak Kudus</strong> adalah restoran steak modern di Kota Kudus yang menyajikan aneka daging premium dengan cita rasa lezat.',
                'rating' => 4.7,
            ],
            [
                'name' => 'Larees Jaya Electronics',
                'slug' => 'larees-jaya-electronics',
                'category' => 'Barang',
                'kecamatan' => 'Kudus Kota',
                'hero_image' => $baseUrl . 'lareesjaya_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Larees Jaya Electronics"',
                'hero_subtitle' => 'Toko elektronik lengkap yang menyediakan berbagai peralatan rumah tangga dan gadget dengan harga bersaing.',
                'description' => 'Toko elektronik lengkap dengan harga bersaing.',
                'about' => '<strong>Larees Jaya Electronics</strong> menyediakan berbagai peralatan rumah tangga dan gadget dengan harga bersaing dan kualitas terjamin.',
                'rating' => 4.6,
            ],
            [
                'name' => 'Es Coklat Cokot Kudus',
                'slug' => 'es-coklat-cokot-kudus',
                'category' => 'Minuman',
                'kecamatan' => 'Kudus Kota',
                'hero_image' => $baseUrl . 'escoklatcokotkudus_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Es Coklat Cokot Kudus"',
                'hero_subtitle' => 'Minuman coklat kekinian dengan rasa creamy dan manis pas, favorit anak muda Kudus.',
                'description' => 'Es coklat creamy dengan rasa manis pas dan topping.',
                'about' => '<strong>Es Coklat Cokot Kudus</strong> adalah minuman coklat kekinian dengan rasa creamy dan manis pas, favorit anak muda Kudus.',
                'rating' => 4.8,
            ],
            [
                'name' => 'Richie Store Kudus',
                'slug' => 'richie-store-kudus',
                'category' => 'Lainnya',
                'kecamatan' => 'Kudus Kota',
                'hero_image' => $baseUrl . 'richiestore_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Richie Store Kudus"',
                'hero_subtitle' => 'Toko pakaian trendi yang menyediakan berbagai busana stylish dan nyaman untuk semua usia.',
                'description' => 'Toko pakaian trendi untuk semua usia.',
                'about' => '<strong>Richie Store Kudus</strong> menyediakan berbagai busana stylish dan nyaman untuk semua usia dengan harga terjangkau.',
                'rating' => 4.7,
            ],

            // MEJOBO
            [
                'name' => 'XGAM_Tech',
                'slug' => 'xgam-tech',
                'category' => 'Jasa',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'xgamtech_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "XGAM_Tech"',
                'hero_subtitle' => 'Layanan servis laptop, komputer, dan rakit PC profesional.',
                'description' => 'Servis laptop, komputer, dan rakit PC dengan harga bersahabat.',
                'about' => '<strong>XGAM_Tech</strong> adalah penyedia jasa servis komputer dan laptop yang berlokasi di Mejobo, Kudus dengan layanan profesional.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Jasa Las dan Bubut Mulyo Rejo',
                'slug' => 'jasa-las-dan-bubut-mulyo-rejo',
                'category' => 'Jasa',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'jasalas_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Jasa Las dan Bubut Mulyo Rejo"',
                'hero_subtitle' => 'Layanan las dan bubut untuk kebutuhan industri dan rumah tangga.',
                'description' => 'Jasa las dan bubut dengan hasil kuat dan presisi.',
                'about' => '<strong>Jasa Las dan Bubut Mulyo Rejo</strong> merupakan bengkel logam profesional di Mejobo yang melayani berbagai kebutuhan pengerjaan logam.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Putra Kalimosodo',
                'slug' => 'putra-kalimosodo',
                'category' => 'Jasa',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'kalimosodo_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Putra Kalimosodo"',
                'hero_subtitle' => 'Penyedia jasa transportasi dan material bangunan terpercaya.',
                'description' => 'Jasa angkut material bangunan dengan armada lengkap.',
                'about' => '<strong>Putra Kalimosodo</strong> merupakan penyedia material bangunan dan jasa transportasi yang berpengalaman di wilayah Mejobo, Kudus.',
                'rating' => 5.0,
            ],
            [
                'name' => 'Ikan Bakar Nasuky Mubarok Jepang',
                'slug' => 'ikan-bakar-nasuky-mubarok-jepang',
                'category' => 'Makanan',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'ikanbakar_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Ikan Bakar Nasuky Mubarok Jepang"',
                'hero_subtitle' => 'Ikan bakar khas Kudus dengan sambal pedas menggoda.',
                'description' => 'Ikan bakar segar dengan bumbu rempah khas Nusantara.',
                'about' => '<strong>Ikan Bakar Nasuky Mubarok Jepang</strong> adalah tempat makan populer di kawasan Jepang, Mejobo, Kudus yang menyajikan ikan bakar segar.',
                'rating' => 4.1,
            ],
            [
                'name' => 'RM Bu Sarah',
                'slug' => 'rm-bu-sarah',
                'category' => 'Makanan',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'rmbusarah_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "RM Bu Sarah"',
                'hero_subtitle' => 'Rumah makan keluarga dengan masakan tradisional Jawa.',
                'description' => 'Rumah makan dengan masakan rumahan khas Jawa.',
                'about' => '<strong>RM Bu Sarah</strong> merupakan salah satu rumah makan populer di Mejobo yang menyajikan menu masakan rumahan khas Jawa.',
                'rating' => 4.3,
            ],
            [
                'name' => 'Sate Kambing Pak Brewok Pekeng',
                'slug' => 'sate-kambing-pak-brewok',
                'category' => 'Makanan',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'satekambing_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Sate Kambing Pak Brewok Pekeng"',
                'hero_subtitle' => 'Warung sate khas yang menyajikan sate kambing empuk dengan bumbu lezat dan cita rasa khas Kudus.',
                'description' => 'Sate kambing empuk dengan bumbu lezat dan khas Kudus.',
                'about' => '<strong>Sate Kambing Pak Brewok Pekeng</strong> adalah warung sate khas di Mejobo yang menyajikan sate kambing empuk dengan bumbu lezat.',
                'rating' => 4.8,
            ],
            [
                'name' => 'Loh Jinawi Olshop (Lapak Gelang Tasbih)',
                'slug' => 'loh-jinawi',
                'category' => 'Barang',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'lohjinawi_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Loh Jinawi Olshop"',
                'hero_subtitle' => 'Toko barang antik dan unik yang menjual gelang tasbih, aksesoris klasik, serta koleksi bernuansa tradisional.',
                'description' => 'Toko gelang tasbih dan aksesoris tradisional unik.',
                'about' => '<strong>Loh Jinawi Olshop</strong> adalah toko barang antik dan unik yang menjual gelang tasbih, aksesoris klasik, dan koleksi bernuansa tradisional.',
                'rating' => 4.7,
            ],
            [
                'name' => 'Toko Auralia Jaya',
                'slug' => 'toko-auralia',
                'category' => 'Barang',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'tokoauralia_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Toko Auralia Jaya"',
                'hero_subtitle' => 'Toko swalayan yang menyediakan berbagai kebutuhan sehari-hari, mulai dari bahan pokok hingga perlengkapan rumah tangga.',
                'description' => 'Toko swalayan lengkap dengan kebutuhan sehari-hari.',
                'about' => '<strong>Toko Auralia Jaya</strong> adalah toko swalayan di Mejobo yang menyediakan berbagai kebutuhan sehari-hari dengan harga terjangkau.',
                'rating' => 4.5,
            ],
            [
                'name' => 'Sekar Modiste',
                'slug' => 'sekar-modiste',
                'category' => 'Lainnya',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'sekar_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Sekar Modiste"',
                'hero_subtitle' => 'Toko pakaian yang menyediakan berbagai busana wanita, jasa jahit, dan modifikasi pakaian dengan desain elegan.',
                'description' => 'Toko pakaian wanita dengan jasa jahit dan modifikasi.',
                'about' => '<strong>Sekar Modiste</strong> menyediakan berbagai busana wanita, jasa jahit, dan modifikasi pakaian dengan desain elegan dan berkualitas.',
                'rating' => 4.6,
            ],
            [
                'name' => 'Hasna Fashion 01',
                'slug' => 'hasna-fashion',
                'category' => 'Lainnya',
                'kecamatan' => 'Mejobo',
                'hero_image' => $baseUrl . 'hasna_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Hasna Fashion 01"',
                'hero_subtitle' => 'Toko pakaian yang menyediakan berbagai busana muslim dan modern dengan harga terjangkau.',
                'description' => 'Toko pakaian muslim dan modern dengan harga terjangkau.',
                'about' => '<strong>Hasna Fashion 01</strong> menyediakan berbagai busana muslim dan modern dengan harga terjangkau dan kualitas baik.',
                'rating' => 4.5,
            ],

            // UNDAAN
            [
                'name' => 'Queen Seblak Prasmanan',
                'slug' => 'queen-seblak-prasmanan',
                'category' => 'Makanan',
                'kecamatan' => 'Undaan',
                'hero_image' => $baseUrl . 'queenseblak_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Queen Seblak Prasmanan"',
                'hero_subtitle' => 'Seblak dengan berbagai topping dan level pedas yang bisa dipilih.',
                'description' => 'Seblak prasmanan dengan aneka topping dan tingkat kepedasan sesuai selera.',
                'about' => '<strong>Queen Seblak Prasmanan</strong> adalah kedai seblak di Undaan, Kudus yang menyajikan seblak prasmanan dengan berbagai pilihan topping seperti kerupuk, sosis, bakso, dan mie, serta tingkat kepedasan yang bisa disesuaikan.',
                'rating' => 4.6,
            ],
            [
                'name' => 'Ayam Geprek Mak Ginting',
                'slug' => 'ayam-geprek-mak-ginting',
                'category' => 'Makanan',
                'kecamatan' => 'Undaan',
                'hero_image' => $baseUrl . 'geprekmakginting_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Ayam Geprek Mak Ginting"',
                'hero_subtitle' => 'Ayam geprek renyah dengan sambal pedas khas Kudus.',
                'description' => 'Ayam geprek dengan sambal pedas khas dan porsi mengenyangkan.',
                'about' => '<strong>Ayam Geprek Mak Ginting</strong> adalah warung makan di Undaan yang terkenal dengan ayam geprek renyah dan sambal pedas khas Kudus, cocok untuk pecinta makanan pedas.',
                'rating' => 4.5,
            ],
            [
                'name' => 'Warung Sate & Gule Pak Sugiyo',
                'slug' => 'warung-sate-dan-gule-pak-sugiyo',
                'category' => 'Makanan',
                'kecamatan' => 'Undaan',
                'hero_image' => $baseUrl . 'warungsatedangule_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Warung Sate & Gule Pak Sugiyo"',
                'hero_subtitle' => 'Sate kambing empuk dan gule gurih khas Kudus.',
                'description' => 'Sate kambing dan gule dengan bumbu rempah khas dan daging empuk.',
                'about' => '<strong>Warung Sate & Gule Pak Sugiyo</strong> menyajikan sate kambing empuk dan gule gurih dengan resep turun-temurun khas Kudus, cocok untuk makan malam bersama keluarga.',
                'rating' => 4.7,
            ],
            [
                'name' => 'MJ Teknik',
                'slug' => 'mj-teknik',
                'category' => 'Jasa',
                'kecamatan' => 'Undaan',
                'hero_image' => $baseUrl . 'mjteknik_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "MJ Teknik"',
                'hero_subtitle' => 'Layanan instalasi listrik dan servis alat rumah tangga.',
                'description' => 'Jasa instalasi listrik dan servis elektronik rumah tangga profesional.',
                'about' => '<strong>MJ Teknik</strong> adalah penyedia jasa instalasi listrik, servis AC, kulkas, dan alat rumah tangga lainnya di Undaan, Kudus dengan tenaga ahli dan harga terjangkau.',
                'rating' => 4.8,
            ],
            [
                'name' => 'Fotocopy & Jasa Travel',
                'slug' => 'fotocopy-dan-jasa-travel',
                'category' => 'Jasa',
                'kecamatan' => 'Undaan',
                'hero_image' => $baseUrl . 'fotocopy_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Fotocopy & Jasa Travel"',
                'hero_subtitle' => 'Layanan fotokopi cepat dan travel antar kota.',
                'description' => 'Jasa fotokopi, print, dan travel antar kota dengan pelayanan cepat.',
                'about' => '<strong>Fotocopy & Jasa Travel</strong> menyediakan layanan fotokopi, print dokumen, serta jasa travel antar kota di wilayah Undaan dan sekitarnya dengan harga bersahabat.',
                'rating' => 4.6,
            ],
            [
                'name' => 'Ngabus Rejo',
                'slug' => 'ngabus-rejo',
                'category' => 'Barang',
                'kecamatan' => 'Undaan',
                'hero_image' => $baseUrl . 'ngabusrejo_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Ngabus Rejo"',
                'hero_subtitle' => 'Toko bahan makanan yang menyediakan berbagai kebutuhan dapur lengkap dengan harga bersahabat dan kualitas terbaik.',
                'description' => 'Toko sembako lengkap dengan harga terjangkau dan kualitas terjamin.',
                'about' => '<strong>Ngabus Rejo</strong> adalah toko bahan makanan di Undaan yang menyediakan berbagai kebutuhan dapur sehari-hari seperti beras, minyak, gula, dan bumbu masak dengan harga bersaing.',
                'rating' => 4.5,
            ],
            [
                'name' => 'Nano Distro',
                'slug' => 'nano-distro',
                'category' => 'Lainnya',
                'kecamatan' => 'Undaan',
                'hero_image' => $baseUrl . 'nanodistro_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Nano Distro"',
                'hero_subtitle' => 'Toko pakaian pria yang menjual berbagai koleksi fashion kasual dan streetwear dengan gaya modern dan harga terjangkau.',
                'description' => 'Distro pakaian pria dengan gaya kasual dan streetwear modern.',
                'about' => '<strong>Nano Distro</strong> adalah toko pakaian pria di Undaan yang menawarkan koleksi kasual, kaos, jaket, dan streetwear dengan desain modern dan harga terjangkau.',
                'rating' => 4.7,
            ],
            [
                'name' => 'Ilbabalanos Store',
                'slug' => 'ilbabalanos',
                'category' => 'Lainnya',
                'kecamatan' => 'Undaan',
                'hero_image' => $baseUrl . 'ilbabalanos_hero.webp',
                'hero_title' => 'Informasi Lengkap tentang UMKM "Ilbabalanos Store"',
                'hero_subtitle' => 'Toko pakaian yang menyediakan berbagai busana modern dan kasual untuk pria maupun wanita dengan harga bersahabat.',
                'description' => 'Toko pakaian modern dan kasual untuk pria dan wanita.',
                'about' => '<strong>Ilbabalanos Store</strong> menyediakan berbagai busana modern dan kasual untuk pria dan wanita dengan desain kekinian dan harga bersahabat di Undaan, Kudus.',
                'rating' => 4.6,
            ],
        ];

        foreach ($umkms as $data) {
            $category = Category::where('name', $data['category'])->first();

            if ($category) {
                Umkm::updateOrCreate(
                    ['slug' => $data['slug']],
                    [
                        'category_id' => $category->id,
                        'kecamatan' => $data['kecamatan'],
                        'name' => $data['name'],
                        'hero_image' => $data['hero_image'],
                        'hero_title' => $data['hero_title'],
                        'hero_subtitle' => $data['hero_subtitle'],
                        'description' => $data['description'],
                        'about' => $data['about'],
                        'rating' => $data['rating'],
                        'status' => 'active',
                    ]
                );
            }
        }
    }
}